### PR TITLE
fixed cooldown option on KillAura

### PR DESCRIPTION
**Pull request by FDPUser443**
It should fix https://github.com/CCBlueX/LiquidBounce/issues/1033

Video: https://youtu.be/In2DQuD65bE

### CODE REVIEW

**Comment by CzechHek** [comment]
Yeah, just break hurt time to fix that.

What about also checking if target should get attacked, depending on its hurt time, but not doing this check for rotations and blocking.

**Comment by FDPUser443** [comment]
There are already target hurtTime check (if target should get attacked, depending on his hurt time) [onRender3D method]: 
`        if (currentTarget != null && attackTimer.hasTimePassed(attackDelay) && currentTarget!!.hurtTime <= hurtTimeValue.get()) {
            clicks++
            attackTimer.reset()
            attackDelay = randomClickDelay(minCPS.get(), maxCPS.get())
        }`

**Comment by FDPUser443** [comment]
There is other problem. This fix doen't work for players and ignores target's hurttime (if target is player) because of raycast.
So, I'm converting it to a draft;

**Comment by CzechHek** [comment]
> There is other problem. This fix doen't work for players and ignores target's hurttime (if target is player) because of raycast. So, I'm converting it to a draft;

Yes, because you removed hurt time check :-D


> There are already target hurtTime check (if target should get attacked, depending on his hurt time) [onRender3D method]: ` if (currentTarget != null && attackTimer.hasTimePassed(attackDelay) && currentTarget!!.hurtTime <= hurtTimeValue.get()) { clicks++ attackTimer.reset() attackDelay = randomClickDelay(minCPS.get(), maxCPS.get()) }`

That only resets attackDelay

**Comment by FDPUser443** [comment]
> There is other problem. This fix doen't work for players and ignores target's hurttime (if target is player) because of raycast. So, I'm converting it to a draft;

Well, the previous version worked fine in singleplayer but struggled with anticheats in multiplayer; Some anticheats, like AAC can spawn invisible mobs near the target;
image
Now, it should work;


> That only resets attackDelay

There is already a condition ["currentTarget!!.hurtTime <= hurtTimeValue.get()"] which checks target's hurttime and if it's false we won't receive clicks for an attack [clicks++]. In the result we will be able to aim and block but not hit;

**Comment by ghost** [comment]
What's the status of this?

**Comment by FDPUser443** [comment]
I will create another PR about this;

**Pull request closed without merging**
