### PR TITLE
Fix Fly[Hypixel Mode]

### PR DESCRIPTION
**Pull request by CrackFileso**
Fix Banned in hypixel

### CODE REVIEW

**Comment by CrackFileso** [comment]
There Might be some bugs that caused the failed damage
Pls check it

**Comment by scorpion3013** [comment]
1. The old version of that fly still works (like 70% of the time). https://streamable.com/uw1pv
2. Your version is weird :axothonk: https://streamable.com/r8rzw 
3. Pls make sure that the version is compileable before making a pull.

**Comment by CrackFileso** [comment]
@scorpion3013 Sorry for that.Beca i have no time to check it.
I am busy with my curriculums
Maybe I will improve it this weekend.Thanks

**Comment by Soulplexis** [comment]
> 1. The old version of that fly still works (like 70% of the time). https://streamable.com/uw1pv
> 2. Your version is weird :axothonk: https://streamable.com/r8rzw
> 3. Pls make sure that the version is compileable before making a pull.

can you update autosettings to whatever you used

**Comment by CrackFileso** [comment]
Closed.Gradle Build is Slow because of THE GREAT FIRE WALL.
2kb/s download speed.
Anyway the key point is to damage also in the air When you start to jump(Distance to Ground = 0.1)

**Pull request closed without merging**
