### PR TITLE
[LEGACY] Improved Velocity

### PR DESCRIPTION
**Pull request by CzechHek**
Added LimitMaxMotion value to Simple mode.
* has MaxXZMotion, MaxYMotion subvalues
* also limits explosion's velocities

Fixed explosion velocity handling, previously it only increased velocity unless both horizontal and vertical distances were set to 0.

Fixed hasReceivedVelocity not detecting when player got knocked back in a single direction only.

### CODE REVIEW

**Comment by CzechHek** [comment]
One more thing came up to my mind, will add later.

**Comment by guosic** [comment]
Could you add a mode that doesn't cause horizontal deceleration and has a non-zero vertical direction, just like in the video?

https://github.com/CCBlueX/LiquidBounce/assets/101028480/ea449dba-6e20-4067-bd13-902a23fd09c3

**Comment by CzechHek** [comment]
> Could you add a mode that doesn't cause horizontal deceleration and has a non-zero vertical direction, just like in the video?
> 
>  2023-10-21_22-12-14.mp4

Doesn't just simple mode, horizontal 0, vertical x do this?

**Comment by guosic** [comment]
> 
> Doesn't just simple mode, horizontal 0, vertical x do this?

This setting is intended to make the horizontal deceleration more visible.

https://github.com/CCBlueX/LiquidBounce/assets/101028480/5b5645cb-43e7-451a-b657-5669d352229d

**Pull request merged**
