### PR TITLE
Small Regen typo fix.

### PR DESCRIPTION
**Pull request by ghost**
`player.health >= 0` implies that he is alive

_Originally posted by @superblaubeere27 in https://github.com/CCBlueX/LiquidBounce/pull/534#discussion_r653429483_

Not actually.

### CODE REVIEW

**Comment by superblaubeere27** [comment]
👍🏻  I would merge it, but for some reason the CI doesn't seem to be willing to compile this

**Comment by ghost** [comment]
It sends this error: 
> org/eclipse/core/runtime/IAdaptable has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by ghost** [comment]
I think the auto build needs to be updated to 1.17

> 👍🏻 I would merge it, but for some reason the CI doesn't seem to be willing to compile this

**Comment by 1zun4secondary** [comment]
Yes, this might be the case. Please wait for https://github.com/CCBlueX/LiquidBounce/tree/nextgen_1.17 to be done.

**Comment by 1zun4secondary** [comment]
Please merge the new changes from the nextgen branch into your pull request to fix the building issue.
https://github.com/CCBlueX/LiquidBounce/runs/2885107056
https://github.com/CCBlueX/LiquidBounce/commit/5551db87d307dcefd8486b65dca47290c606ba85

**Pull request merged**
