### PR TITLE
LEGACY: Added Grimplace Disabler

### PR DESCRIPTION
**Pull request by skatoot**

### CODE REVIEW

**Comment by EclipsesDev** [comment]
question is, does it required specific version or like a viaversion thingy?

**Comment by Razzy52** [comment]
> question is, does it required specific version or like a viaversion thingy?

I believe this is from Github's issue list. Pretty sure it states that it should work on all versions

**Comment by EclipsesDev** [comment]
> > question is, does it required specific version or like a viaversion thingy?
> 
> I believe this is from Github's issue list. Pretty sure it states that it should work on all versions

hmm ok.. how does it work? like i've tested it, but see no difference

**Comment by EclipsesDev** [comment]
might need to fix this, since its not quite right..?

**Pull request merged**
