### PR TITLE
feat: Grim 2.3.65 NoWeb

### PR DESCRIPTION
**Pull request by ManInMyVan**
bypasses the experimental checks now

### CODE REVIEW

**Comment by 1zun4** [comment]
I was not able to confirm the bypass on eu.loyisa.cn or anticheat-test.com
Is this version specific?

**Comment by ManInMyVan** [comment]
> I was not able to confirm the bypass on eu.loyisa.cn or anticheat-test.com

what exactly happened?

> Is this version specific?

no

**Comment by 1zun4** [comment]
ok tf works now, when i tried it didnt work and flagged for break packets but now it just works xd

**Comment by ManInMyVan** [comment]
> ok tf works now, when i tried it didnt work and flagged for break packets but now it just works xd

You probably disabled BreakOnWorld

**Pull request merged**
