### PR TITLE
fix: correct blend function

### PR DESCRIPTION
**Pull request by ccetl**

### CODE REVIEW

**Comment by ccetl** [comment]
Ok this does not help the alpha is still wrong.

**Comment by 1zun4** [comment]
This would have also broken the blending fr. There is a reason this is on ONE

**Comment by ccetl** [comment]
> This would have also broken the blending fr. There is a reason this is on ONE

It changed nothing when i tested it, didn't break anything nor fix anything...

**Comment by 1zun4** [comment]
> > This would have also broken the blending fr. There is a reason this is on ONE
> 
> It changed nothing when i tested it, didn't break anything nor fix anything...

It's hard to see but you can make it out on thin text, logos and bright background.

**Pull request closed without merging**
