### PR TITLE
[LEGACY] TimerRange Small Changes

### PR DESCRIPTION
**Pull request by EclipsesDev**
Removed unnecessary condition as these already covered by EntityUtils

### CODE REVIEW

**Comment by EclipsesDev** [comment]
@CzechHek is this correct?

**Comment by CzechHek** [comment]
Don't even need to filter by entity living base.

**Comment by EclipsesDev** [comment]
> Don't even need to filter by entity living base.

like this "private fun getAllLivingEntities() = mc.theWorld.loadedEntityList
        .filter { EntityUtils.isSelected(it, true) }
        
        private fun getNearestEntityInRange(): Entity? {
        val player = mc.thePlayer

        val entitiesInRange = getAllLivingEntities()
            .filter { player.getDistanceToEntityBox(it) <= rangeValue }

        return entitiesInRange.minByOrNull { player.getDistanceToEntityBox(it) }
    }"

**Comment by EclipsesDev** [comment]
> Don't even need to filter by entity living base.

like this? 

/**
     * Get all living entities in the world.
     */
    private fun getAllLivingEntities() = mc.theWorld.loadedEntityList
        .filter { EntityUtils.isSelected(it, true) }

    /**
     * Find the nearest living entity in range.
     */
    private fun getNearestEntityInRange(): EntityLivingBase? {
        val player = mc.thePlayer

        val entitiesInRange = getAllLivingEntities()
            .filterIsInstance<EntityLivingBase>()
            .filter { player.getDistanceToEntityBox(it) <= rangeValue }

        return entitiesInRange.minByOrNull { player.getDistanceToEntityBox(it) }
    }

**Comment by EclipsesDev** [comment]
@mems01 ig this is ready to be merged

**Pull request merged**
