### PR TITLE
NEXTGEN: small improvements

### PR DESCRIPTION
**Pull request by be4dev**
* vulcan glide now doesn't flag and glides better
* added autodisable option to blink
* added old mode back to clip module

### CODE REVIEW

**Comment by 1zun4** [comment]
I do not agree with adding back the old clip, since there is .vclip and I doubt there is any purpose for the old one compared to the new one, which does the exact same but with requiring a wall between.

**Comment by be4dev** [comment]
> I do not agree with adding back the old clip, since there is .vclip and I doubt there is any purpose for the old one compared to the new one, which does the exact same but with requiring a wall between.

.vclip and hclip aren't bindable, on vulcan for example you can clip 10 b up with 1 flag, so if you are ever stuck somewhere  (have no blocks) or want to fly to another island you will have to do .vclip 10 which isn't very convenient

**Comment by Razzy52** [comment]
> > I do not agree with adding back the old clip, since there is .vclip and I doubt there is any purpose for the old one compared to the new one, which does the exact same but with requiring a wall between.
> 
> .vclip and hclip aren't bindable, on vulcan for example you can clip 10 b up with 1 flag, so if you are ever stuck somewhere (have no blocks) or want to fly to another island you will have to do .vclip 10 which isn't very convenient

which is why your able to glide on the vulcan highjump module

**Comment by be4dev** [comment]
> > > I do not agree with adding back the old clip, since there is .vclip and I doubt there is any purpose for the old one compared to the new one, which does the exact same but with requiring a wall between.
> > 
> > 
> > .vclip and hclip aren't bindable, on vulcan for example you can clip 10 b up with 1 flag, so if you are ever stuck somewhere (have no blocks) or want to fly to another island you will have to do .vclip 10 which isn't very convenient
> 
> which is why your able to glide on the vulcan highjump module

to use highjump you need to be on ground, to clip you don't (and it still would bypass, sometimes even without flags)

**Pull request merged**
