### PR TITLE
Added ReachAura

### PR DESCRIPTION
**Pull request by commandblock2**
A sometimes glitchy module ReachAura(TpAura or InfiniteAura). Only for vanilla servers.

### CODE REVIEW

**Comment by NurMarvin** [comment]
Looks fine for now, since we're only making InDev builds at the moment, but we'll have to make it less glitchy till b72. Merging.

**Comment by kawaiinekololis** [comment]
I'm currently optimizing the reach aura. It's a lot of code to optimize but ... I'll try my best. ^^

**Comment by kawaiinekololis** [comment]
I'm sorry. I think I'll have to revert this pull request. The aura itself is just too broken.
I tried to solve the issues, but it's too much code. I'll have to do it myself.
Still thank you for your pull request.

**Comment by commandblock2** [comment]
I must admit the code was indeed shitty, I was noob and too anxious to make a pull request because I won't be able to work on it for a while for a exam. I do understand that you reverted the commit for it's code quality, I was planning to refactor it but I didn't have that much time. I will still try to improve it if I have extra time. 
btw I can see some of the problems come from the targetmode, it probably needs to be rewritten. It is should be better if there is a list for previous targets(like killaura) than removing targets from the list.

**Comment by kawaiinekololis** [comment]
We could add your pull request as draft. Just create a new pull request, so I can create a draft.

**Pull request merged**
