### PR TITLE
Optimize Rendering stuff

### LINKED ISSUE #3730: [IMPROVE] Renderer improvements
## What was done?
- Optimize constant texts in FontRenderer
- Optimize volatile text by using Tesselator
- Optimize 2D-ESP
- Replace too small Tessellator usages with Immediate-mode
- Optimize large Tesselator calls

### ESP
- Box + Otherbox: 25% faster
- 2D (Old): 30% faster
### FontRenderer
- Average: 93% faster
- On compiling new text (occurs at only one frame): 200% slower
- Best case: 96% faster
### Modules which benefit from FontRenderer optimization (ClickGUI, Nametags, HUD, etc.)
- Nametags: ~80% faster
- ClickGUI: 95% faster
- HUD (Arraylist, TabGUI, Effects): 80% faster
### Tracers
- ~40% faster

### PR DESCRIPTION
**Pull request by superblaubeere27**
Closes CCBlueX/LiquidBounce1.8-Issues#3730

## TODO
- [x] Optimize constant texts in FontRenderer
- [x] Optimize volatile text by using Tesselator
- [x] Optimize 2D-ESP
- [x] Replace too small Tessellator usages with Immediate-mode
- [x] Optimize large Tesselator calls

### CODE REVIEW

**Comment by superblaubeere27** [comment]
## Conclusion
This patch reduces the CPU-Heaviness of the renderer which allows slower CPUs to get massive gains. On my desktop it made the client faster (on a server with usual modules turned on) by 5 FPS (In the ClickGUI ~13 FPS).
## Performance gains
### ESP
- Box + Otherbox: 25% faster
- 2D (Old): 30% faster
### FontRenderer
- Average: 93% faster
- On compiling new text (occurs at only one frame): 200% slower
- Best case: 96% faster
## Modules which benefit from FontRenderer optimization (ClickGUI, Nametags, HUD, etc.)
- Nametags: ~80% faster
- ClickGUI: 95% faster
- HUD (Arraylist, TabGUI, Effects): 80% faster
### Tracers
- ~40% faster

**Review by NurMarvin — APPROVED** [review]

**Review by 1zun4 — APPROVED** [review]

**Comment by kawaiinekololis** [comment]
Just one thing: Could you clean up your code in the future?

**Comment by superblaubeere27** [comment]
> 
> 
> Just one thing: Could you clean up your code in the future?

Uh what do you mean?

**Comment by kawaiinekololis** [comment]
`net.ccbluex.liquidbounce.ui.font.FontRenderer.assumeNonVolatile = false`

```
//        System.out.println("Time spent rendering texts " + FontRenderer.Companion.getTimeTakenRenderingFonts() / 1000 + "us");
//        FontRenderer.Companion.setTimeTakenRenderingFonts(0);
```

**Comment by superblaubeere27** [comment]
@kawaiinekololis I removed the commented out code and I renamed the `FontRenderer` to `AWTFontRenderer` to prevent confusion, removed those explicit identifiers.

**Comment by superblaubeere27** [comment]
@kawaiinekololis Fixed

**Pull request merged**
