### PR TITLE
NEXTGEN: Update config system

### PR DESCRIPTION
**Pull request by be4dev**
* you can add date, time and author to configs now
* you can list available local configs
* support for online configs (add online or local at the end (.config list online / .config load exampleName online))

### CODE REVIEW

**Comment by gabrielvicenteYT** [comment]
Maybe add .cloudconfig list ?

**Comment by 1zun4** [comment]
> Maybe add .cloudconfig list ?

The API does not have any configs yet therefore the endpoint will likely not respond with anything.

**Comment by Razzy52** [comment]
> > Maybe add .cloudconfig list ?
> 
> The API does not have any configs yet therefore the endpoint will likely not respond with anything.

Wouldn't it make sense just to add it for future proofing?

**Comment by be4dev** [comment]
> > > Maybe add .cloudconfig list ?
> > 
> > 
> > The API does not have any configs yet therefore the endpoint will likely not respond with anything.
> 
> Wouldn't it make sense just to add it for future proofing?

well, I am actually using liquidcloud fork for this data, that's how I test it

**Pull request merged**
