### PR TITLE
Added New Velocity Mode

### PR DESCRIPTION
**Pull request by NCPUser**
Bypass Mineblaze,CheatMine And Etс.

### CODE REVIEW

**Comment by be4dev** [comment]
> Bypass Mineblaze,CheatMine And Etс.

bruh, this is just legit jumping

**Comment by CzechHek** [comment]
Does it even stop jumping?

**Comment by ghost** [comment]
Does it even JUMP?

**Comment by NCPUser** [comment]
yes is 0.00000012 reduce

**Comment by ghost** [comment]
I don't think this will make the user jump. You send an input update BEFORE the actual input update is called, therefore still setting the jump input to false. I assume you don't understand what this means so in short it means you still don't jump.

**Comment by be4dev** [comment]
> I don't think this will make the user jump. You send an input update BEFORE the actual input update is called, therefore still setting the jump input to false. I assume you don't understand what this means so in short it means you still don't jump.

yep, plus I have a better one, which actually reduces your knockback, I will finish my pr as soon as my math teacher decides, that we might have a few things at home, other then solving really big equations

**Comment by NCPUser** [comment]
Closed is a shit code.

**Pull request closed without merging**
