### PR TITLE
feat: matrix timer speed

### PR DESCRIPTION
**Pull request by ghost**
works on lastest matrix
you can have fun on shotbow.net
https://www.youtube.com/watch?v=HZvUusU0EW4

### CODE REVIEW

**Comment by ghost** [comment]
this seems to be skidded and not going to works on actual matrix, go on a test server and use that lol

**Comment by EclipsesDev** [comment]
🤦

**Comment by ghost** [comment]
https://streamable.com/lymh7u

**Comment by ghost** [comment]
its not even skidded

**Comment by ghost** [comment]
even if it works what the point when custom speed exist

**Pull request closed without merging**
