### PR TITLE
Added NoScoreboard module.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by derech1e** [comment]
I think NoScoreboard should be in the nextgen version a part of the custom HUD editor. If you want to hide the scoreboard, you can then just remove or hide the element in the editor parallel to the other scoreboard options. In this case the module is  henceforth superfluous.

**Comment by Teals53** [comment]
right

**Comment by ghost** [comment]
It more fits in the render category personally, but it's up to them.

**Comment by 1zun4secondary** [comment]
No Scoreboard is not required. It was added when there was no way of moving around the scoreboard.

**Pull request closed without merging**
