### PR TITLE
Fixed modules that utilize CpsScheduler being flagged on anticheats on target switch.

### PR DESCRIPTION
**Pull request by ghost**
So basically in dumb talk, if for example a module is automatically hitting a player with 6 CPS, then you re-enable the module and hit a player again, it will hit with almost double the CPS, causing anticheats to detect you for it.

Video to demonstrate what I mean:
https://streamable.com/ghmavv

EDIT: Maybe it's just CpsScheduler in need of an improvement.

### CODE REVIEW

**Comment by 1zun4secondary** [comment]
Yes, but you literally defeated the purpose of CpsScheduler.  Minecraft counts the clicks of your mouse until the next tick and will do multiple clicks in one tick. It is more likely that we should improve the scheduler instead of removing it.

**Comment by ghost** [comment]
Yeah, I noticed that CPS is now less than the requested amount. Perhaps I should close this PR?

**Comment by 1zun4secondary** [comment]
How much CPS did you set? It seems NCP is counting more than 15 clicks, which is way too much for legit users.

**Comment by ghost** [comment]
I tried 20-20 CPS, but it gave a maximum of 13.

**Comment by 1zun4secondary** [comment]
With CPS Scheduler or without?

**Comment by ghost** [comment]
Without it, if you mean replacing the `repeat` part with an if statement.

**Comment by 1zun4secondary** [comment]
Yes, this is pretty much normal because it is milliseconds based and not ticks based and without the repeat it will not work correctly and miss a few clicks.

**Comment by 1zun4secondary** [comment]
But when you set like 10cps with CPS Scheduler (with repeat) does it still flag? I don't remember having any issues with it when I was making it and I did test it on every major anticheat.

**Comment by ghost** [comment]
Yes, it does flag if I re-enable the module like I did in the video. What I notice is that at whatever CPS it is set to, it almost doubles it if you do that "trick"

**Comment by 1zun4secondary** [comment]
Ok very weird. Should not happen, but I'll look into it when I'm back to nextgen.

**Comment by ghost** [comment]
Forgot to mention, there's also a problem when setting CPS values to 1-1, it hits once then never hits again.

**Comment by ghost** [comment]
Did a few tests with c45f037, and I can say that there are no issues anymore. Sudden CPS increase doesn't occur, 1-1 CPS making the function "freeze" is fixed, plus the code is simplified.

**Comment by 1zun4secondary** [comment]
Looks good, but I'll have to try it.

**Comment by ghost** [comment]
Here, a video in case you are busy:

https://streamable.com/9v8w88

**Pull request merged**
