### PR TITLE
refactor(theme): Completely rewrite the default theme

### PR DESCRIPTION
**Pull request by NurMarvin**
This PR completely rewrites the default theme to make it easier to maintain.

Some notable changes are:

- Vite instead of Rollup
- React instead of Svelte
- TypeScript instead of JavaScript
- Single router-based project instead of multiple independent projects

At the moment the client is unable to render the built theme for some unknown reason, but I will fix this while finishing the rest of the theme. Some parts of the theme also still use TailwindCSS, but I will move everything to CSS Modules in due time.

Here's a quick video of the current progress:

https://github.com/CCBlueX/LiquidBounce/assets/17235016/44dcc488-e742-4fc6-8f20-c869d957299f

Fixes #1442

### CODE REVIEW

**Comment by Ell1ott** [comment]
Those animations look 🔥

**Comment by NurMarvin** [comment]
https://github.com/CCBlueX/LiquidBounce/assets/17235016/c747ca6e-7be6-4cab-b99a-b7752f8efd22

**Comment by NurMarvin** [comment]
https://github.com/CCBlueX/LiquidBounce/assets/17235016/ac5503dd-fc30-4957-ad76-bdd415be19c5

**Comment by be4dev** [comment]
> thorium_1SyCV3x3q5.mp4

looks wonderful, but can this color at the bottom of the gui at 0:15 be fully dark? Would be really nice (since the whole clickgui is dark themed)

**Comment by AWKohler** [comment]
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

**Comment by 1zun4** [comment]
https://github.com/CCBlueX/LiquidBounce/assets/12410754/6752a7e1-d3c5-46e0-aee5-74a030c15351

**Comment by AWKohler** [comment]
Screenshot 2024-02-11 at 11 08 01 AM
the theme is not attaching when building the jar. The zipped theme file is missing from the jar, causing issues.

**Comment by SenkJu** [comment]
I think this pull request can now be closed?

**Comment by AWKohler** [comment]
> I think this pull request can now be closed?

why? This looks so good

**Comment by superblaubeere27** [comment]
> > I think this pull request can now be closed?
> 
> why? This looks so good

Yes it looks good and @NurMarvin put a lot of effort into it, but it was never finished.

Since we have another equal version of the UI we don't need this anymore

**Pull request closed without merging**
