### PR TITLE
make session login text box have a big limit to fit session token

### PR DESCRIPTION
**Pull request by 182exe**
[issue](https://github.com/CCBlueX/LiquidBounce/issues/1821)

idk if this will work yet

### CODE REVIEW

**Comment by EclipsesDev** [comment]
well have u test it out? and does it work?

**Comment by 182exe** [comment]
i will be real here
i literally do not have a java ide installed

**Comment by EclipsesDev** [comment]
welp I don't even have session token so i couldn't test it out, maybe @mems01?

**Comment by ghost** [comment]
The author should always test what they make.

**Comment by EclipsesDev** [comment]
you seems to be the only one who's having this issue, so ig you're the one who supposed to test it

**Comment by 182exe** [comment]
i tested it
it works now

**Pull request merged**
