### PR TITLE
LEGACY: Added FakeItem RenderUtils

### LINKED ISSUE #1605: [FEATURE] Silent AutoTool
### LiquidBounce Branch

Legacy

### Describe your feature request.

Would be awesome if someone make a Silent mode for AutoTool, but as you can know auto tool work so that when mining certain block it will changed to what tool are needed, but silent AutoTool would allow you to change the tool server-sided, without changing the tool your holding currently in client sided..

### Additional context

I've tried making this, but failed since it change the tool server sided but the mining speed didn't sync. So if someone could make it, that would be nice 👍

### PR DESCRIPTION
**Pull request by gaoyu06**
More improvements needs to be done.
1. AutoTool should switch back to former item before switching after digging
2. Hotbar selection also needs to keep fake item slot.

### CODE REVIEW

**Comment by gaoyu06** [comment]
#1605 The PR is based on this issue

**Comment by gaoyu06** [comment]
this is the video: https://drive.google.com/file/d/1FumLdwbubp5ZzLQh5M57ltzrHw4jobOg/view?usp=sharing

**Comment by EclipsesDev** [comment]
Thank you for actually adding this ♥️

**Comment by EclipsesDev** [comment]
Is this ready for merge? @SuperSkidder

**Comment by gaoyu06** [comment]
> Is this ready for merge? @SuperSkidder

no, I need to fix some bugs.
I will @You when it is ready.

**Comment by EclipsesDev** [comment]
> > Is this ready for merge? @SuperSkidder
> 
> no, I need to fix some bugs. I will @you when it is ready.

Ah ok 👍

**Comment by gaoyu06** [comment]
@EclipsesDev This feature was almost done, and I have tested it. You can merge it, but I recommend you to test it further to check if it would conflict with other modules.

**Comment by EclipsesDev** [comment]
> @EclipsesDev This feature was almost done, and I have tested it. You can merge it, but I recommend you to test it further to check if it would conflict with other modules.

I will check it out when I'm home

**Comment by EclipsesDev** [comment]
@SuperSkidder K after checking, i've some suggestion to make.. is it done purposely or why don't u make it so in 3rd person it also stays as the original slot? and It would be nice too if u implement this on other modules that are using server slot.. like scaffold spoof autoblock and other modules too maybe. But overall its looking good 👍

**Comment by gaoyu06** [comment]
I'll implement 3rd perspective later.
Other modules like Scaffold are good enough I think, it's not necessay to use this method to spoof slot.

**Comment by EclipsesDev** [comment]
> I'll implement 3rd perspective later. Other modules like Scaffold are good enough I think, it's not necessay to use this method to spoof slot.

Alright then ig I'll merge after u implement the 3rd person mode

**Comment by doesDeveloper** [comment]
Merge now please

**Comment by EclipsesDev** [comment]
> Merge now please

Just wait for @SuperSkidder next commit, and it should be ready for merge

**Comment by EclipsesDev** [comment]
So @SuperSkidder how's it?

**Comment by gaoyu06** [comment]
> So @SuperSkidder how's it?

um I'm busy on study now. You can merge it now and I will make another PR to implement undone thing later.

**Comment by gaoyu06** [comment]
> > So @SuperSkidder how's it?
> 
> um I'm busy on study now. You can merge it now and I will make another PR to implement undone thing later.

I'll have time to do like next week or even longer

**Comment by EclipsesDev** [comment]
Alright

**Pull request merged**
