### PR TITLE
AAC4.4.2 velocity

### PR DESCRIPTION
**Pull request by be4dev**
very useful

### CODE REVIEW

**Comment by 1zun4secondary** [comment]
Please note on which version of AAC this bypass was made and tested. Thank you!

**Comment by be4dev** [comment]
> Please note on which version of AAC this bypass was made and tested. Thank you!

done, if I understood you correctly

**Comment by 1zun4secondary** [comment]
Yes but please do not name the mode AACv4, but rather something like AAC4.4.2

**Comment by be4dev** [comment]
> Yes but please do not name the mode AACv4, but rather something like AAC4.4.2

done, btw legacy has AACv4 mode, so I thought, that this name is ok

**Pull request merged**
