### PR TITLE
New shortcuts parser and shortcuts serialization.

### PR DESCRIPTION
**Pull request by Fr3shTea**

### CODE REVIEW

**Comment by Marco09MC** [comment]
ffs was working too on saving and loading the shortcuts

**Comment by Fr3shTea** [comment]
xD

**Comment by Fr3shTea** [comment]
; is a statement end, not a separator. But I don't think it's a big problem.

**Comment by Marco09MC** [comment]
well the way you are saving the shortcuts doesn't look quite good.
I'm gonna merge it and take some changes.

**Comment by Fr3shTea** [comment]
ok

**Comment by Marco09MC** [comment]
big sad

**Comment by Fr3shTea** [comment]
I hope my shitcode isn't too bad. xd

**Comment by Marco09MC** [comment]
btw you don't have to use companion object in a class
you can just write object instead of class


to

**Comment by Marco09MC** [comment]
object in kotlin just means a singleton in java

**Comment by Fr3shTea** [comment]
I know. I'm just autist.

**Comment by Marco09MC** [comment]
I'm not sure if the parser is over engineered. Like it doesn't matter. I don't see any difference between the old one and the new one, it's just more code. xd

**Comment by Fr3shTea** [comment]
Well, old parser had some bugs. AFAIK it's failed when

**Pull request merged**
