### PR TITLE
Reverted fuckery

### PR DESCRIPTION
**Pull request by yorik100**
Backtrack now works!

### CODE REVIEW

**Comment by CzechHek** [comment]
What about not just reverting it but fixing it?

Code is objectively worse and stop pushing 100 commits.

Are you sure that the original code works correctly, cause I see no difference in logic after looking at it like 3 times?

**Comment by yorik100** [comment]
> What about not just reverting it but fixing it?
> 
> Code is objectively worse and stop pushing 100 commits.
> 
> Are you sure that the original code works correctly, cause I see no difference in logic after looking at it like 3 times?

It was completely broken, unusable https://github.com/CCBlueX/LiquidBounce/issues/1641

**Comment by EclipsesDev** [comment]
> What about not just reverting it but fixing it?
> 
> Code is objectively worse and stop pushing 100 commits.
> 
> Are you sure that the original code works correctly, cause I see no difference in logic after looking at it like 3 times?

yeah my guy really don't want to just make new branch or delete the old one instead

**Comment by CzechHek** [comment]
image

See the problem now, gotta push it again cause this changes made it as effective as before.

**Pull request merged**
