### PR TITLE
Fix JIT errors for ScriptAPI

### PR DESCRIPTION
**Pull request by LTBlueLatios**
- Modified required libraries
- Removed Marco's botnet /s

### CODE REVIEW

**Comment by LTBlueLatios** [comment]
Video of me testing: https://youtu.be/vUlUYgnobqc?si=0-9c80etS8R8IQI3

**Comment by superblaubeere27** [comment]
Wait... This works? We tried for like forever :o

**Comment by LTBlueLatios** [comment]
Yep, it works. What makes this funny is the fact that the issues simply comes from a lack of necessary libraries. _Thanks for the very useful documentation, Graal._

Idk if it requires for the user to have GraalVM physically installed on their system. Someone is going to have to check, I only tested this with Fabric's runClient task.

**Comment by liquidsquid1** [comment]
> Yep, it works. What makes this funny is the fact that the issues simply comes from a lack of necessary libraries. _Thanks for the very useful documentation, Graal._
> 
> Idk if it requires for the user to have GraalVM physically installed on their system. Someone is going to have to check, I only tested this with Fabric's runClient task.

The thing is, the fabric runClient class uses GraalVM by default on the system, whereas regular minecraft installs do not. *(don’t quote me on this one)*

**Comment by LTBlueLatios** [comment]
I have just confirmed that GraalVM needs to be physically present on the user's machine in order for this to work.

**Comment by 1zun4** [comment]
> I have just confirmed that GraalVM needs to be physically present on the user's machine in order for this to work.

Yes, but this is not a problem as LiquidLauncher can install GraalVM automatically.

**Comment by 1zun4** [comment]
> Wait... This works? We tried for like forever :o

Not really. We already have the same changes here: https://github.com/CCBlueX/LiquidBounce/tree/graaljs_jit
But here comes the actual issue: We have no working remapper for JIT.

**Pull request closed without merging**
