### PR TITLE
feat: Minecraft 1.21.3

### PR DESCRIPTION
**Pull request by 1zun4**

### CODE REVIEW

**Review by DataM0del — APPROVED** [review]
Seems to already support it :skull: (or at least I can join 1.21.3-only servers, also it displays 1.21.1-1.21.3 in the title bar I think)

**Comment by 1zun4** [comment]
> Seems to already support it 💀 (or at least I can join 1.21.3-only servers, also it displays 1.21.1-1.21.3 in the title bar I think)

No it does not. The client still runs on 1.21.1. You are able to join 1.21.3 because of ViaFabricPlus.

**Comment by DataM0del** [comment]
> > Seems to already support it 💀 (or at least I can join 1.21.3-only servers, also it displays 1.21.1-1.21.3 in the title bar I think)
> 
> No it does not. The client still runs on 1.21.1. You are able to join 1.21.3 because of ViaFabricPlus.

Oh...

**Comment by DataM0del** [comment]
I'm trying to rebase to resolve the conflicts. Currently finished 1b4e929bcb75aa8e614813e9cd52ef32715c0bd5. Will open a PR once I'm done, hopefully I don't break something (:skull:)
**edit**: currently solving conflicts in 204e9faa0

**Comment by DataM0del** [comment]
Rebased! Will push it to my fork and open a PR

**Comment by DataM0del** [comment]
Opened the PR, apparently it can't automatically merge: #4464
**edit**: "solved" the "conflicts" (aka did nothing other than just accept my code) via the conflicts UI. You can merge it now I guess

**Review by DataM0del — APPROVED** [review]
Other than the conflicts (#4464 fixes them because I rebased it), Looks Good To Me :tm:.

**Comment by DataM0del** [comment]
GitHub :rofl:
image
solution: just "resolve" the "conflicts" by accepting only the changes from this branch

**Comment by 1zun4** [comment]
i think because I rebased instead of merged

**Comment by 1zun4** [comment]
The PR is still work in progress and will take a lot of time to be completed, so working on merge conflicts does not make much sense yet.

**Review by DataM0del — APPROVED** [review]

**Comment by DataM0del** [comment]
it launches, however... (I don't have the Fabric API installed, but it doesn't look like that matters)
```log
[18:40:29] [Render thread/ERROR]: Exception while executing handler.
java.lang.IllegalAccessError: class net.ccbluex.liquidbounce.integration.browser.BrowserDrawer tried to access protected field net.minecraft.class_4668.field_53128 (net.ccbluex.liquidbounce.integration.browser.BrowserDrawer and net.minecraft.class_4668 are in unnamed module of loader 'knot' @74235045)
	at knot/net.ccbluex.liquidbounce.integration.browser.BrowserDrawer.browserTextureLayer$lambda$5(BrowserDrawer.kt:127) ~[liquidbounce-0.17.1.jar:?]
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
	at knot/net.minecraft.class_156$2.apply(class_156.java:1001) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_332.method_25295(class_332.java:440) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_332.method_25293(class_332.java:430) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_332.method_25302(class_332.java:426) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_332.method_25290(class_332.java:422) ~[client-intermediary.jar:?]
	at knot/net.ccbluex.liquidbounce.integration.browser.BrowserDrawer.renderTexture(BrowserDrawer.kt:143) ~[liquidbounce-0.17.1.jar:?]
	at knot/net.ccbluex.liquidbounce.integration.browser.BrowserDrawer.handleScreenRender$lambda$2(BrowserDrawer.kt:75) ~[liquidbounce-0.17.1.jar:?]
	at knot/net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:205) [liquidbounce-0.17.1.jar:?]
	at knot/net.minecraft.class_757.handler$zeb000$liquidbounce$hookScreenRender(class_757.java:1024) [client-intermediary.jar:?]
	at knot/net.minecraft.class_757.method_3192(class_757.java:549) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1523(class_310.java:1352) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1514(class_310.java:933) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:265) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?]
```

**Comment by 1zun4** [comment]
"PR is still a work in progress" - did you get that?

**Comment by DataM0del** [comment]
More conflicts :money_mouth_face::money_mouth_face::money_mouth_face:
There hasn't really been any new commits other than fixing conflicts, this PR stalled from what I can see.

**Comment by DataM0del** [comment]
#4477

**Comment by DataM0del** [comment]
I'm working on this in my branch, **it's not just fixing conflicts**, I added a weather rendering mixin and whatever else because fixing stuff because yes. Might make a PR for this but I want to fix a few more things.
Also, minimap crash moment (no "This PR is a draft - did you get that?" excuse, but not sure if this issue exists in upstream (don't think so))

**Comment by 1zun4** [comment]
Likely replaced by https://github.com/CCBlueX/LiquidBounce/pull/4722

**Pull request closed without merging**
