### PR TITLE
Change HUD's UI to (rounded) Parallelogram

### PR DESCRIPTION
**Pull request by nercone-dev**
### Idea
I wanted to make the UI close to the concept image

### Changes
Change the UI of the HUD to a parallelogram

### Comment
In the concept image, the HUD was a parallelogram, but now it is rectangular.
I made the HUD a parallelogram and sent this pull request.
This pull request was developed in collaboration with ChatGPT, so there may be mistakes.
I haven't been able to test because I don't have an environment where I can test.
If you are unnecessary or mistaken, please reject it.

### CODE REVIEW

**Comment by 1zun4** [comment]
I will try it out later. :)

**Comment by Ell1ott** [comment]
image
well...

**Comment by nercone-dev** [comment]
**Thank you for the test.**
The shape was _strange_...
You can see the edges of the image...
I'll try to fix it.
(I'm Japanese, so my English may be strange, but please understand)

**Comment by 1zun4** [comment]
I will close this pull request due to inactivity as well as this was already tested by @SenkJu when he was implementing the HUD. I cannot remember exactly, but something did not work out as intended.

**Pull request closed without merging**
