### PR TITLE
NEXTGEN: proper altmanager

### PR DESCRIPTION
**Pull request by be4dev**
this will take a lot of time + code is shit (got pure html skills, but since ui part seems to be stuck, why not to try?)

if any one got/can create a proper theAltening svg icon pls send it to me

### CODE REVIEW

**Comment by be4dev** [comment]
> this will take a lot of time + code is shit (got pure html skills, but since ui part seems to be stuck, why not to try?)
> 
> if any one got/can create a proper theAltening svg icon pls send it to me

this is how it looks now 
image

**Comment by 1zun4** [comment]
Neat. Good start.

**Comment by Ell1ott** [comment]
> if any one got/can create a proper theAltening svg icon pls send it to me

svg:

thealtening
result:
image

**Comment by CzechHek** [comment]
> > if any one got/can create a proper theAltening svg icon pls send it to me
> 
> svg:
> 
> thealtening result: image

mojang login has been fully deprecated for some months now

**Comment by be4dev** [comment]
> > > if any one got/can create a proper theAltening svg icon pls send it to me
> > 
> > 
> > svg:
> > thealtening result: image
> 
> mojang login has been fully deprecated for some months now

minecraft login is cracked login basically

**Comment by 1zun4** [comment]
Thank you for the work, but the most promosing PR for the future GUI system is going to be https://github.com/CCBlueX/LiquidBounce/pull/1442

**Pull request closed without merging**
