### PR TITLE
refactor(legacy): cleaned up code

### PR DESCRIPTION
**Pull request by Coccocoahelper**
Makes the code a bit more like next-gen, not fully ready (I don't know how to rebase)

### CODE REVIEW

**Comment by EclipsesDev** [comment]
If you're ready, you can undraft it

**Comment by Coccocoahelper** [comment]
> If you're ready, you can undraft it

Ya, can you rebase it? I have 1 last big change to do.

**Comment by 1zun4** [comment]
Just as small hint. Simply saying "Cleaned up & port code" is very useless for the end-user and changelog writer to understand what you have changed. In the future, if you add a feature, mark it with "feat: autotool onlysneak option" and for cleaning up code a seperate PR with for example: "refactor: cleaned up code".
This will make tracking progress easier and also for maintainers to allow merging PRs that might be not ready but contain already ready to merge features.

**Comment by Coccocoahelper** [comment]
> Just as small hint. Simply saying "Cleaned up & port code" is very useless for the end-user and changelog writer to understand what you have changed. In the future, if you add a feature, mark it with "feat: autotool onlysneak option" and for cleaning up code a seperate PR with for example: "refactor: cleaned up code". This will make tracking progress easier and also for maintainers to allow merging PRs that might be not ready but contain already ready to merge features.

Thank you for that suggestion. Sorry about that, it's just that I'm used to doing it all at once in my repositories.

**Comment by 1zun4** [comment]
> > Just as small hint. Simply saying "Cleaned up & port code" is very useless for the end-user and changelog writer to understand what you have changed. In the future, if you add a feature, mark it with "feat: autotool onlysneak option" and for cleaning up code a seperate PR with for example: "refactor: cleaned up code". This will make tracking progress easier and also for maintainers to allow merging PRs that might be not ready but contain already ready to merge features.
> 
> Thank you for that suggestion. Sorry about that, it's just that I'm used to doing it all at once in my repositories.

Yes understandable, but it is very important for a bigger project such as LiquidBounce to maintain commit message quality. In this case it is only for Legacy, so I am not too worried about it, but in the end it is still someone else that has to write the changelog (mostly me). 

At least we are far from being as bad as this...:
image

**Comment by Coccocoahelper** [comment]
> > > Just as small hint. Simply saying "Cleaned up & port code" is very useless for the end-user and changelog writer to understand what you have changed. In the future, if you add a feature, mark it with "feat: autotool onlysneak option" and for cleaning up code a seperate PR with for example: "refactor: cleaned up code". This will make tracking progress easier and also for maintainers to allow merging PRs that might be not ready but contain already ready to merge features.
> > 
> > 
> > Thank you for that suggestion. Sorry about that, it's just that I'm used to doing it all at once in my repositories.
> 
> Yes understandable, but it is very important for a bigger project such as LiquidBounce to maintain commit message quality. In this case it is only for Legacy, so I am not too worried about it, but in the end it is still someone else that has to write the changelog (mostly me).
> 
> At least we are far from being as bad as this...: image

Neither am I, but my repositories sure have a different commit style: 
image

FYI: FDPClient is being recoded by Zywl, it's no longer going to be skidded, but that is awful; if I said “Jesus Christ” right now, it wouldn't be in vain…

Bonus: If you want, I can start writing the changelogs, like I did few versions ago!

**Comment by 1zun4** [comment]
> Bonus: If you want, I can start writing the changelogs, like I did few versions ago!

Sure, just let me know and @EclipsesDev contact me whenever you think a version is ready for release. I want to make sure that everything goes right.

**Comment by Coccocoahelper** [comment]
> > Bonus: If you want, I can start writing the changelogs, like I did few versions ago!
> 
> Sure, just let me know and @EclipsesDev contact me whenever you think a version is ready for release. I want to make sure that everything goes right.

Honestly, I think that b92 should take its time; after all, it's 20 builds after b72, likely the most used LiquidBounce legacy version EVER.

**Pull request merged**
