### PR TITLE
added resetVL

### PR DESCRIPTION
**Pull request by larryngton2**
resets your violations on old anticheats

### CODE REVIEW

**Comment by 1zun4** [comment]
With older anti-cheats you mean?

**Comment by larryngton2** [comment]
> With older anti-cheats you mean?

ncp and maybe some other shit one

**Comment by larryngton2** [comment]
on ncp i tried using vanilla fly a bit untill i flagged when sneaking nomally, toggled on resetvl and i wasnt flagging at all anymore

**Comment by Cosmic-SC** [comment]
seriously how do you manage to flag ncp and who uses vanilla fly on ncp

**Comment by Cosmic-SC** [comment]
this module was useful for hypixel _once upon a time_ but its pointless on anything nowadays (also the name's really misleading and people might use it on any anticheat to "reset their vl" if they flag)

**Comment by larryngton2** [comment]
> this module was useful for hypixel _once upon a time_ but its pointless on anything nowadays (also the name's really misleading and people might use it on any anticheat to "reset their vl" if they flag)

then why do most new clients have it? and liquidbounce in general isnt retard-proof btw

**Comment by larryngton2** [comment]
> seriously how do you manage to flag ncp and who uses vanilla fly on ncp

i used it as a test / example.

**Comment by Cosmic-SC** [comment]
> > this module was useful for hypixel _once upon a time_ but its pointless on anything nowadays (also the name's really misleading and people might use it on any anticheat to "reset their vl" if they flag)
> 
> then why do most new clients have it? and liquidbounce in general isnt retard-proof btw

I don't know what "modern" client has it, but the argument is still the same: you can't use this on 99.9% of the anticheats (if you really do need to reset your vl (if that still works on anything), just jump manually). Anyway, it's up to Izuna to merge this. I've made my point and stand by it.

**Comment by liquidsquid1** [comment]
> > > this module was useful for hypixel _once upon a time_ but its pointless on anything nowadays (also the name's really misleading and people might use it on any anticheat to "reset their vl" if they flag)
> > 
> > 
> > then why do most new clients have it? and liquidbounce in general isnt retard-proof btw
> 
> I don't know what "modern" client has it, but the argument is still the same: you can't use this on 99.9% of the anticheats (if you really do need to reset your vl (if that still works on anything), just jump manually). Anyway, it's up to Izuna to merge this. I've made my point and stand by it.

So we should remove vanilla fly because it doesn’t bypass? I really do not see your point here.

**Comment by larryngton2** [comment]
> > > this module was useful for hypixel _once upon a time_ but its pointless on anything nowadays (also the name's really misleading and people might use it on any anticheat to "reset their vl" if they flag)
> > 
> > 
> > then why do most new clients have it? and liquidbounce in general isnt retard-proof btw
> 
> I don't know what "modern" client has it, but the argument is still the same: you can't use this on 99.9% of the anticheats (if you really do need to reset your vl (if that still works on anything), just jump manually). Anyway, it's up to Izuna to merge this. I've made my point and stand by it.

"just jump manually" yes but with resetvl you can do that like 5x faster? i dont really get your point here. thats like saying that cheststealer should be removed because you can steal chests manually

**Comment by Cosmic-SC** [comment]
As I said, it's up to @1zun4; I don't merge PRs. I just gave my opinion.

**Comment by 1zun4** [comment]
I have adjusted the module description and now it should be clear.

**Pull request merged**
