### PR TITLE
chore(legacy): A Legacy-Fabric implementation of the client.

### PR DESCRIPTION
**Pull request by ghost**
This aims to improve performance, such as removing micro stutters, increasing fps and allowing support for better performance mods.

This is on a super duper early stage as the first steps have been done on a smart phone. The rest need to be done on an actual computer with an IDE, something that I do not have due to my current situation at this moment.

### CODE REVIEW

**Comment by EclipsesDev** [comment]
🙏

**Comment by opZywl** [comment]
ye

**Comment by azureskylines** [comment]
haven't had the chance to look at this, but i assume it's a full switch to LF. wouldn't it be more efficient to use a toolchain like Essential Loom or Deftu Gradle Toolkit (based on Essential Loom)

should provide the ability to have both Forge and Legacy Fabric seamlessly in the same project (and same binary), along with the benefits of up-to-date gradle

**Comment by ghost** [comment]
It seems Essential Loom does not support older versions?
IMG_1606


Unless I am wrong.

**Comment by Cosmic-SC** [comment]
> It seems Essential Loom does not support older versions? IMG_1606
> 
> Unless I am wrong.

check deftu gradle toolkit

**Comment by Cosmic-SC** [comment]
here's an example mod implementing it
https://github.com/koxx12-dev/Example-Forge-1.8.9

**Comment by ghost** [comment]
> here's an example mod implementing it
> https://github.com/koxx12-dev/Example-Forge-1.8.9

Does that make the mod a fabric type while still keeping the forge code as it is or what?

**Comment by Coccocoahelper** [comment]
> > It seems Essential Loom does not support older versions? IMG_1606
> > Unless I am wrong.
> 
> check deftu gradle toolkit

It doesn't, either

**Comment by azureskylines** [comment]
> It seems Essential Loom does not support older versions?
> IMG_1606
> 
> 
> Unless I am wrong.

it does, you can just set it to use 1.8, i've made several 1.8 projects with it

**Comment by azureskylines** [comment]
> > here's an example mod implementing it
> > https://github.com/koxx12-dev/Example-Forge-1.8.9
> 
> Does that make the mod a fabric type while still keeping the forge code as it is or what?

it provides a dev env for both, lets you use the same mappings, etc

**Comment by 1zun4** [comment]
A reminder that Forge support must be guaranteed.

**Comment by ghost** [comment]
Unless we make two separate branches, I don’t see us finding another way.

**Comment by EclipsesDev** [comment]
> Unless we make two separate branches, I don’t see us finding another way.

pretty sure there's a way to make it support both fabric & forge idk how, gabriel knows it

**Comment by Coccocoahelper** [comment]
> > Unless we make two separate branches, I don’t see us finding another way.
> 
> pretty sure there's a way to make it support both fabric & forge idk how, gabriel knows it

Deftu's Gradle Toolkit does the trick. But you'll still need to port Forge-only code.

**Comment by ghost** [comment]
Let’s just make two separate branches and update them for each commit that is done. I am not at home to experiment with things like Deftu’s Gradle Toolkit. If there is anyone experienced in that field, I would have no issue with anyone doing a different implementation. My plan is to finish this implementation.

**Comment by azureskylines** [comment]
> Let’s just make two separate branches and update them for each commit that is done. I am not at home to experiment with things like Deftu’s Gradle Toolkit. If there is anyone experienced in that field, I would have no issue with anyone doing a different implementation. My plan is to finish this implementation.

whenever this implementation gets finished, i'll see what i can do to move it to DGT or similar
Preprocessor should cover mapping changes between forge and fabric once it's all moved to Yarn so it would maily just be buildscript changes, and abstracting away anything potentially loader dependent to move to the per-loader modules
either way, it is both possible and achievable

**Comment by Coccocoahelper** [comment]
> > Let’s just make two separate branches and update them for each commit that is done. I am not at home to experiment with things like Deftu’s Gradle Toolkit. If there is anyone experienced in that field, I would have no issue with anyone doing a different implementation. My plan is to finish this implementation.
> 
> whenever this implementation gets finished, i'll see what i can do to move it to DGT or similar Preprocessor should cover mapping changes between forge and fabric once it's all moved to Yarn so it would maily just be buildscript changes, and abstracting away anything potentially loader dependent to move to the per-loader modules either way, it is both possible and achievable

We're gonna need help with that. Some fields are private, and the per-loader modules are hard to do.

**Comment by azureskylines** [comment]
> > > Let’s just make two separate branches and update them for each commit that is done. I am not at home to experiment with things like Deftu’s Gradle Toolkit. If there is anyone experienced in that field, I would have no issue with anyone doing a different implementation. My plan is to finish this implementation.
> > 
> > whenever this implementation gets finished, i'll see what i can do to move it to DGT or similar Preprocessor should cover mapping changes between forge and fabric once it's all moved to Yarn so it would maily just be buildscript changes, and abstracting away anything potentially loader dependent to move to the per-loader modules either way, it is both possible and achievable
> 
> We're gonna need help with that. Some fields are private, and the per-loader modules are hard to do.

private fields and methods can both be interacted with via accessors and invokers (see: [2xsaiko/mixin-cheatsheet](https://github.com/2xsaiko/mixin-cheatsheet)), and what is there hard about per-loader modules? DGT's multiversion plugin automatically generates them and sets them up (see: [Deftu/ModTemplate](https://github.com/Deftu/ModTemplate))

**Comment by opZywl** [comment]
action continue?

**Comment by ghost** [comment]
Replacing Forge code with Fabric code one by one is not a wise choice. Azure also said that his idea to make it support both Forge and Fabric turned out to be a dead end.

**Pull request closed without merging**
