### PR TITLE
Added Regen module.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by 1zun4secondary** [comment]
The spartan mode is basically timer and speed 9. The modes should be removed and a timer option added.

**Comment by 1zun4secondary** [comment]
Timer should reset itself when regen is not regenerating.

**Comment by ghost** [comment]
> The spartan mode is basically timer and speed 9. The modes should be removed and a timer option added.

Done. Also removed the food option because if you have 0 food level, your HP will instead drop faster.

**Comment by 1zun4secondary** [comment]
uhm...
image
what?

This is not what I mean. It should reset itself when the regeneration process is done. What you did doesn't do anything.
I would do it myself but I don't have my IDE installed right now, so yeah.

**Comment by ghost** [comment]
Is this perhaps what you want?

EDIT: If not, then you can do it your own method.

**Pull request merged**
