### PR TITLE
LEGACY: StaffDetector

### PR DESCRIPTION
**Pull request by EclipsesDev**

### CODE REVIEW

**Comment by 1zun4** [comment]
I would not recommend hard-coding their names into the code. Instead they should be loaded remotely from for example the LiquidCloud.

**Comment by EclipsesDev** [comment]
i thought of that, tho idk how to do so 😅

**Comment by superblaubeere27** [comment]
At least put it in a resource. Like `resources/staffdetector/blocksmc-staff.txt`

**Comment by EclipsesDev** [comment]
> At least put it in a resource. Like `resources/staffdetector/blocksmc-staff.txt`

alright

**Pull request merged**
