### PR TITLE
Updated Autoarmor & created recode branch

### PR DESCRIPTION
**Pull request by derech1e**
- updated ModuleCategory
- added startDelay
- added dropOld option
- added Item Damage comparision
- added TestCase-Module to check if Autoarmor works (only dev build)

### CODE REVIEW

**Comment by yorik100** [comment]
Still doesn't fix the major AutoArmor bug that makes it stuck https://github.com/CCBlueX/LiquidBounce-Issues/issues/3909
Could be easily fixed if AutoArmor was dropping the armor instead of putting it off

**Comment by derech1e** [comment]
> Still doesn't fix the major AutoArmor bug that makes it stuck [CCBlueX/LiquidBounce-Issues#3909](https://github.com/CCBlueX/LiquidBounce-Issues/issues/3909)
> Could be easily fixed if AutoArmor was dropping the armor instead of putting it off

I know, it was not my intention to fix this bug. I want to push this recode forward. I also added a drop option, that can be activated manually. If you have better solutions, then create a PR in this branch and add them.

**Comment by yorik100** [comment]
> 
> 
> > Still doesn't fix the major AutoArmor bug that makes it stuck [CCBlueX/LiquidBounce-Issues#3909](https://github.com/CCBlueX/LiquidBounce-Issues/issues/3909)
> > Could be easily fixed if AutoArmor was dropping the armor instead of putting it off
> 
> I know, it was not my intention to fix this bug. I want to push this recode forward. I also added a drop option, that can be activated manually. If you have better solutions, then create a PR in this branch and add them.

I didn't read drop old, my bad

**Comment by yorik100** [comment]
Not clear at all tbh

**Comment by derech1e** [comment]
> Not clear at all tbh

It is **WIP**
Why is that so hard to understand?

**Comment by yorik100** [comment]
Why is there armor in InventoryCleaner?

**Comment by derech1e** [comment]
I realized that a whole recode is needed after all. The structure and mode of operation of the InventoryCleaner should be changed. More on the Todo comment in InventoryCleaner.kt. I'll close probably this PR and restart the work on the recode. Do you have any special ideas or wishes @kawaiinekololis? Is someone else already working on it? Does it make sense to replace AutoArmor and InventoryCleaner with an InventoryManager?

**Comment by Teals53** [comment]
image

**Comment by Teals53** [comment]
for about stack limits

**Comment by yorik100** [comment]
> 
> 
> I realized that a whole recode is needed after all. The structure and mode of operation of the InventoryCleaner should be changed. More on the Todo comment in InventoryCleaner.kt. I'll close probably this PR and restart the work on the recode. Do Does it make sense to replace AutoArmor and InventoryCleaner with an InventoryManager?

No, I want to be able to use only one at a time, it'd be terrible to combine both

**Comment by kawaiinekololi** [comment]
> I realized that a whole recode is needed after all. The structure and mode of operation of the InventoryCleaner should be changed. More on the Todo comment in InventoryCleaner.kt. I'll close probably this PR and restart the work on the recode. Do you have any special ideas or wishes @kawaiinekololi ? Is someone else already working on it? Does it make sense to replace AutoArmor and InventoryCleaner with an InventoryManager?

No, I don't think so. But I don't like the idea of replacing AutoArmor and InventoryCleaner with a InventoryManager.

**Comment by Teals53** [comment]
but why its closed ? @derech1e

**Pull request closed without merging**
