### PR TITLE
Proper Fly rework

### PR DESCRIPTION
**Pull request by CzechHek**
Replaces https://github.com/CCBlueX/LiquidBounce/pull/1136, rewritten from scratch, has nothing in common with it.

Improved code of all modes.
* fully rewritten Redesky mode (like wtf was that)

Fixed multiple old bugs:
* timer management in Hypixel mode
* minimal neruxvace value
* boosthypixel detecting player rotation instead of server flags, also made it turn itself off instead of just stopping to work
* fixed marker being in player's head with boosthypixel mode
* fixed smoothvanilla stopping motion when disabled, when it should rather act like vanilla creative fly
* fixed isFlying capability getting disabled even when a player was flying before enabling the module (presumably in Creative)
* more...

Added optional argument "stopWhenNoInput" to MovementUtils.strafe(), it is self-explanatory.
* used in fly modes

Added infix +, -, *, /, vector support into MathExtensions.
* used in fly modes

Rearranged modes of Fly and Speed in ClickGUI.

Refactored speeds package to speedmodes, added flymodes package.

Made SpeedMode fully open and not abstract.
* removed unnecessary empty overrides of the previously abstract methods

Converted Speed modes to objects.

Changed modes getter to a constant field, since speed modes and fly modes are made up of objects and immutable.

Added mc.thePlayer.stopXZ() and mc.thePlayer.stop().
* sets motions to 0
* used in fly modes

### CODE REVIEW

**Comment by CzechHek** [comment]
@gabrielvicenteYT You can add your new modes or whatever in here.

**Comment by gabrielvicenteYT** [comment]
@CzechHek Amazing work, but can I keep working on my version of it? Just trying to also learn a bit more of Java, LMAO.

**Comment by CzechHek** [comment]
> Just trying to also learn a bit more of Java, LMAO.

You should.

**Comment by ghost** [comment]
This usually happens when you use an IDE, @gabrielvicenteYT.

**Comment by gabrielvicenteYT** [comment]
> This usually happens when you use an IDE, @gabrielvicenteYT.

Seems like I'm not that lucky, not using an IDE works better for me; except github.dev, of course

**Comment by ghost** [comment]
> Seems like I'm not that lucky, not using an IDE works better for me; except github.dev, of course

No, you're just afraid to explore the stuff that it provides. Have it from a dude who thought `toLong()` was a syntax error, Man up and install it, you will NOT regret it.

**Comment by gabrielvicenteYT** [comment]
> > Seems like I'm not that lucky, not using an IDE works better for me; except github.dev, of course
> 
> No, you're just afraid to explore the stuff that it provides. Have it from a dude who thought `toLong()` was a syntax error, Man up and install it, you will NOT regret it.

Hol' up, you thought ``toLong()`` was a syntax error?!? I'm p sure Long is just the 64 bit version of Integer…

**Pull request merged**
