### PR TITLE
refactor: code improvements

### PR DESCRIPTION
**Pull request by be4dev**
* optimized imports
* did some code refactoring (for example ModuleCriticals.kt)
* made some variables/functions private
* suppressed incorrect indexing
* reduced detekt baseline

### CODE REVIEW

**Comment by superblaubeere27** [comment]
It would be great if you could also reduce the amount of the code smells detekt detected

**Comment by be4dev** [comment]
guess it is done now, now someone should carefully check all the shit, I have done

**Comment by 1zun4** [comment]
Thank you. I will review it soon.

**Comment by 1zun4** [comment]
Ah shoot. Should have looked at it before doing so many changes again. Welp. Time for some merging.

**Comment by 1zun4** [comment]
So far so good... I guess it can be merged. Especially because the v0.2.0 release is far out, we can use the time until then to find every bug caused by this PR.

**Pull request merged**
