### PR TITLE
feat(legacy): BedPlates Module

### PR DESCRIPTION
**Pull request by opZywl**

### CODE REVIEW

**Comment by opZywl** [comment]
#3780  request

**Comment by EclipsesDev** [comment]
I'll restest it myself but not now, tomorrow 👍

**Comment by Cosmic-SC** [comment]
please optimize raven XD code (dont do the update rate thing its bad use some event that is fired when a block is placed instead) :pray:

**Comment by EclipsesDev** [comment]
> please optimize raven XD code (dont do the update rate thing its bad use some event that is fired when a block is placed instead) 🙏

wait is this from ravenxd?

**Comment by opZywl** [comment]
> please optimize raven XD code (dont do the update rate thing its bad use some event that is fired when a block is placed instead) 🙏

RavenXD what?

**Comment by EclipsesDev** [comment]
https://github.com/xia-mc/Raven-XD/blob/master/src/main/java/keystrokesmod/module/impl/render/BedPlates.java broo...

**Comment by Cosmic-SC** [comment]
> https://github.com/xia-mc/Raven-XD/blob/master/src/main/java/keystrokesmod/module/impl/render/BedPlates.java broo...

I thought lb legacy didnt have a strict "no-skid" policy...

**Comment by Cosmic-SC** [comment]
> > please optimize raven XD code (dont do the update rate thing its bad use some event that is fired when a block is placed instead) 🙏
> 
> RavenXD what?

RavenXD's code (they also stole that from some where probably)

**Comment by EclipsesDev** [comment]
> > https://github.com/xia-mc/Raven-XD/blob/master/src/main/java/keystrokesmod/module/impl/render/BedPlates.java broo...
> 
> I thought lb legacy didnt have a strict "no-skid" policy...

I didn't know but at first i had suspicion on the code format like its kinda ass ngl

**Comment by opZywl** [comment]
image
image
image
image

Well idk if it is skid this guy send me this code and say "I made it but need implements you can help and fix" you can translate all messages

**Comment by opZywl** [comment]
> > > please optimize raven XD code (dont do the update rate thing its bad use some event that is fired when a block is placed instead) 🙏
> 
> > 
> 
> > RavenXD what?
> 
> 
> 
> RavenXD's code (they also stole that from some where probably)

All raven is bad lol I never accessed this shits

**Comment by opZywl** [comment]
I don't know if it is "skid" but this guy create pull request and send this code

I'm reformatted all things

**Comment by Cosmic-SC** [comment]
lol that guy lied he definitely did not make this module it is infact from xd

**Comment by Cosmic-SC** [comment]
that person even sent the rect shader smh

**Comment by Coccocoahelper** [comment]
> > https://github.com/xia-mc/Raven-XD/blob/master/src/main/java/keystrokesmod/module/impl/render/BedPlates.java broo...
> 
> I thought lb legacy didnt have a strict "no-skid" policy...

I'm almost certain that using code from a GPLv3 project is not 'skidding' — at least if that project's authors don't oppose, and all due credits are given.

**Comment by opZywl** [comment]
so as not to have any inconvenience I think we will redo the module I apologize I actually received part of this by DM to discord the person said they had done it... however I do not deny that I redid a lot of things and adjusted a large part of it

**Comment by Cosmic-SC** [comment]
> > > https://github.com/xia-mc/Raven-XD/blob/master/src/main/java/keystrokesmod/module/impl/render/BedPlates.java broo...
> > 
> > 
> > I thought lb legacy didnt have a strict "no-skid" policy...
> 
> I'm almost certain that using code from a GPLv3 project is not 'skidding' — at least if that project's authors don't oppose, and all due credits are given.

copy paste from another client -> skidding. thats my definition. But zywl is not to blame ig since this was sent to him by some other guy

**Comment by 1zun4** [comment]
@Coccocoahelper 
> > > https://github.com/xia-mc/Raven-XD/blob/master/src/main/java/keystrokesmod/module/impl/render/BedPlates.java broo...
> > 
> > 
> > I thought lb legacy didnt have a strict "no-skid" policy...
> 
> I'm almost certain that using code from a GPLv3 project is not 'skidding' — at least if that project's authors don't oppose, and all due credits are given.

@opZywl Unless the original owner has provided the code and created the PR, we will not accept it. I consider this PR closed since you are unsure of the origin of the code. However, if you want to add BedPlates to Legacy, you can either write it from scratch (which is easy anyway) or take a look at the one from Nextgen and port it over.

@Cosmic-SC 
> > https://github.com/xia-mc/Raven-XD/blob/master/src/main/java/keystrokesmod/module/impl/render/BedPlates.java broo...
> 
> I thought lb legacy didnt have a strict "no-skid" policy...

Yes, we do. We do not take code if the original owner has not given permission to take the code, even if the license allows it.

**Pull request closed without merging**
