### PR TITLE
Hypixel Bypasses

### PR DESCRIPTION
**Pull request by aftery142**
Contains criticals, damage fly and tower for hypixel.

### CODE REVIEW

**Comment by scorpion3013** [comment]
isnt a c03 onground true needed before the jump?

**Comment by SpoilerRules** [comment]
cool.

**Comment by aftery142** [comment]
> 
> 
> isnt a c03 onground true needed before the jump?

wdym?

**Comment by lolmc1982** [comment]
.-.

**Comment by scorpion3013** [comment]
https://www.youtube.com/watch?v=3RyF0o7Tv_Q

**Comment by aftery142** [comment]
> 
> 
> https://www.youtube.com/watch?v=3RyF0o7Tv_Q

oh ye, forgot to add that, whoops

**Pull request merged**
