### PR TITLE
refactor: lazy loading translation files

### PR DESCRIPTION
**Pull request by MukjepScarlet**

### CODE REVIEW

**Comment by 1zun4** [comment]
This could introduce lag when it's being loaded. Loading all of them is not ideal, but I don't think it makes sense to only load when it's needed. Maybe at least load english since it's common language and the language that is specified.

**Comment by MukjepScarlet** [comment]
en_us and the current language (if present) will be loaded at client starting

**Comment by 1zun4** [comment]
> en_us and the current language (if present) will be loaded at client starting

Really? But where? Am I blind?

**Comment by MukjepScarlet** [comment]
In my test, the en_us and current language will be loaded (en_us at first), probably because of the `getCommonLanguage` call

**Comment by 1zun4** [comment]
Might specifiy it at the ClientResourceReloader

**Comment by MukjepScarlet** [comment]
Recovered

**Pull request merged**
