### PR TITLE
feat(legacy): Mitigation notification visuals to KillAura.

### PR DESCRIPTION
**Pull request by ghost**
* [ ] Polish the code
* [ ] Implement visual code to indicate mitigation (Red dots on top of user, anything that does not blind the user)
* [ ] Maybe test it a couple more times before merging

Could also be implemented as a module.

### CODE REVIEW

**Comment by DataM0del** [comment]
> Polish the code

is bro rewriting the code in Polish!?!??!!?

**Comment by ghost** [comment]
You are one funny guy, I give you that.

**Comment by ghost** [comment]
After many tests on different mini games, I came to the conclusion that this is not stable enough. Might work well on Gamster, but it won't on other servers.

**Comment by DataM0del** [comment]
RIP

**Pull request closed without merging**
