### PR TITLE
feat: better pointtracker

### PR DESCRIPTION
**Pull request by larryngton2**
- gaussianSpeed (allows the rotations to interpolate to the aim point given by the offset)
- gaussianTolerance (checks if your current aim is close to the aim point with a tolerance before updating, works well with gaussianSpeed)
- min / max gaussianFactor
- dynamicShrinkBox toggle (allows you to disable box shrinking based off of your move speed)
- dynamicGaussianFactor (scales gaussian offset by your movement speed so when you are standing still you offset less)
- dynamic box expand for gaussian

### CODE REVIEW

**Comment by 1zun4** [comment]
image

**Comment by larryngton2** [comment]
> image
> 

thanks, I'll work on moving the expand box thing onto gaussian offset (have you tested if it actually randomises though?)

**Comment by larryngton2** [comment]
wait how the fuck am i supposed to only expand the box the offset aims at

**Comment by 1zun4** [comment]
> wait how the fuck am i supposed to only expand the box the offset aims at

you check if the point of your offset is outside of the box, if so, put the min/max x y z to include your offset

**Pull request merged**
