### PR TITLE
[LEGACY] Recoding things to Kotlin

### PR DESCRIPTION
**Pull request by Coccocoahelper**
Very WIP, not even compiling yet [no IDE for me :(]

### CODE REVIEW

**Comment by EclipsesDev** [comment]
If you don't have IDE then how do u test this?

**Comment by Coccocoahelper** [comment]
> If you don't have IDE then how do u test this?

mainly by checking compile errors

**Comment by EclipsesDev** [comment]
Well no, what I meant was testing if there's no error and whether the modules still work or not

**Comment by EclipsesDev** [comment]
Well let me know if this is ready for merge

**Comment by EclipsesDev** [comment]
I'd suggest u to use IDE, since rn you can't really see much of the errors that u made.. well u can but only via build logs..

**Comment by EclipsesDev** [comment]
If you still want to make this, then make pr when u have IDE 👍

**Comment by Coccocoahelper** [comment]
> If you still want to make this, then make pr when u have IDE 👍

F

**Pull request closed without merging**
