### PR TITLE
Some storageesp fixes and autoclicker weapononly

### PR DESCRIPTION
**Pull request by SALTx**

### CODE REVIEW

**Comment by yorik100** [comment]
You should add an option to remove bots from tracers too, and nametags

**Comment by derech1e** [comment]
> You should add an option to remove bots from tracers too, and nametags

Maybe also an option, to hide bots fully. So that they not even rendered anymore.

**Comment by yorik100** [comment]
> 
> 
> > You should add an option to remove bots from tracers too, and nametags
> 
> Maybe also an option, to hide bots fully. So that they not even rendered anymore.

That'd be tricky as people can be bots for only like 1 ticks or so, if they get removed and then they're set as "non-bots" by the antibot, they won't reappear, the best thing would be to add an option like "If was bot for more than X ms then remove" slider and a "if X blocks away then remove", for example, if bot is 7 blocks away and was a bot for more than 10 000 ms then remove

**Comment by SALTx** [comment]
o wow im a fucking dumbass github phone app hard to use smh

**Comment by Teals53** [comment]
what ? what is that

**Comment by Teals53** [comment]
why u renaming modules why u disable rpc why u changed these stuff wtf r u doing ?

**Comment by Teals53** [comment]
ok nvm maybe wrong merge xD

**Comment by SALTx** [comment]
ya no shit i redid the pr

**Pull request closed without merging**
