### PR TITLE
[Legacy] A Small Fix For Switch Item NoSlow

### PR DESCRIPTION
**Pull request by Cosmic-SC**
do not send c08s in switchitem + why was it being sent in post???

### CODE REVIEW

**Comment by Auza2008** [comment]
I forgot. I copied an ncp code block (because of my laziness). But I forgot to delete c08.

**Comment by Cosmic-SC** [comment]
> I forgot. I copied an ncp code block (because of my laziness). But I forgot to delete c08.

so u skidded it 💀

**Comment by Auza2008** [comment]
no

**Comment by Auza2008** [comment]
I think you're missing the point

**Comment by Auza2008** [comment]
I didn't want to write another block of code so I copied line 75

**Comment by Cosmic-SC** [comment]
okay

**Pull request merged**
