### PR TITLE
Completely new ScriptAPI

### PR DESCRIPTION
**Pull request by SenkJu**
The new ScriptAPI is significantly more idiomatic and reduces the amount of unnecessary boilerplate code to an absolute minimum. It retains all features of the old script API.

Example:
```js
/// api_version=2
var script = registerScript({
    name: "MyCoolScript",
    version: "2.3.4",
    authors: ["Senk Ju", "Axolotl"]
});

script.registerModule({
    name: "TestModule",
    category: "Misc",
    description: "Just a test",
    settings: {
        mySetting: Setting.boolean({
            name: "MyBooleanSetting",
            default: true
        })
    }
}, function (module) {
    module.on("update", function () {
        if (module.settings.mySetting.get()) {
            Chat.print("Setting is enabled!");
        }
    });

    module.on("disable", function () {
        Chat.print("Disabled module");
    });
});

script.registerCommand({
    name: "testcommand",
    aliases: ["secretcommand"]
}, function(command) {
    command.on("execute", function(args) {
        if (args.length > 1) {
            Chat.print(args[1]);
        }
    });
});

script.registerTab({
    name: "ExampleTab",
    icon: "apple",
    items: [
        Item.create("dirt")
    ]
});
```

### CODE REVIEW

**Comment by SenkJu** [comment]
Don't merge this yet!

**Comment by superblaubeere27** [comment]
Can you put your changes on a branch on this repository next time? Would be nice since we could work on it too

**Comment by SenkJu** [comment]
Yeah, I thought so too. I will create a new branch for the new script API instead.

**Comment by SenkJu** [comment]
See #96

**Pull request closed without merging**
