### PR TITLE
[LEGACY] Strict RotStrafe for Scaffold

### PR DESCRIPTION
**Pull request by gabrielvicenteYT**
useful for Grim

### CODE REVIEW

**Comment by ghost** [comment]
what? why? who would want the strict mode on a module like Scaffold??

**Comment by gabrielvicenteYT** [comment]
> what? why? who would want the strict mode on a module like Scaffold??

Grim seems to flag Scaffold once in a while in certain occasions, and I also added the GodBridge rotation mode to Scaffold, but I'll be fixing it soon

**Comment by ghost** [comment]
Please remove the Strict mode, modules like Scaffold are never meant to have this option.

**Comment by gabrielvicenteYT** [comment]
> Please remove the Strict mode, modules like Scaffold are never meant to have this option.

It sometimes flags on Grim w/o this option, tho

**Comment by ghost** [comment]
Config issue.

**Comment by gabrielvicenteYT** [comment]
> Config issue.

Nope.

**Pull request closed without merging**
