### PR TITLE
Added Modern mode to BackTrack module

### PR DESCRIPTION
**Pull request by RtxOP**
Mems' solution.

### CODE REVIEW

**Comment by RtxOP** [comment]
Was tested on intave, karhu and grim

**Comment by gabrielvicenteYT** [comment]
Code looks way better than before. I approve.

**Comment by RtxOP** [comment]
Merge when?

**Comment by gabrielvicenteYT** [comment]
> Merge when?

They're telling you to make it a different module than the original backtrack.

**Comment by 1zun4** [comment]
> Merge when?

It would be good if you could leave the old backtrack intact, while adding the new one as a new mode or module. Otherwise seems fine, but I have not tested it yet.

**Comment by RtxOP** [comment]
That's about it

**Comment by RtxOP** [comment]
Maybe 2f6f71f was a mistake eh I'll look into it tmr

**Comment by RtxOP** [comment]
All bugs are fixed and is ready to be merged!!!!!

**Comment by RtxOP** [comment]
that's it

**Comment by ghost** [comment]
Thanks for the contribution. We finally see eye to eye.

**Comment by RtxOP** [comment]
W

**Pull request merged**
