### PR TITLE
(Japanese File | ja_jp.json) All values have been translated.

### PR DESCRIPTION
**Pull request by nercone-dev**
All values were translated manually.

### CODE REVIEW

**Comment by 1zun4** [comment]
Hello. Someone else made a PR before you addressing japanese translations and now this PR is conflicting.
https://github.com/CCBlueX/LiquidBounce/pull/2824

Can you please check the current translations and merge them together if needed?

**Review by 1zun4 — CHANGES_REQUESTED** [review]
Merge needed

**Comment by nercone-dev** [comment]
Sorry

**Comment by nercone-dev** [comment]
Please wait...

**Review by nercone-dev — COMMENTED** [review]
Would this be ok?

**Review by 1zun4 — APPROVED** [review]

**Comment by 1zun4** [comment]
Yes it is OK now. I removed the duplicate entries. I tried my best to decide which one is the "better one".

**Pull request merged**
