### PR TITLE
improve: CrystalAura

### LINKED ISSUE #4263: [FEATURE] Addition to Crystal Aura
### LiquidBounce Branch

Nextgen

### Describe your feature request.

A simple addition that would be nice to have is the ability to place crystals through walls, while this obviously won't bypass many anticheats having an option for it would be a nice thing to have

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ccetl**
- **fixes placing flagging some anti cheats**
- improved placement (wall range, places on any side)
- improved rotation options
- anti suicide
- improved loop
- improved (faster and more reliable) position finding
- the ability to use the offhand slot
- delay options
- less lag
Before:
image
After:
image

Depends on: #4277
Closes: #4263

### CODE REVIEW

**Comment by SuicidalEeper** [comment]
Highly appreciated, good job!

**Comment by SuicidalEeper** [comment]
Is something preventing this from being merged?

**Comment by ccetl** [comment]
> Is something preventing this from being merged?

Yes, but I'm working on it.

**Comment by SuicidalEeper** [comment]
Best of luck!

**Pull request merged**
