### PR TITLE
Smaller Dependecies Updates

### PR DESCRIPTION
**Pull request by Snowiiii**

### CODE REVIEW

**Comment by 1zun4** [comment]
Updating the Fabric Loader might cause trouble with for example Lunar Client.

**Comment by Snowiiii** [comment]
why it should ?

**Comment by 1zun4** [comment]
Because their Lunar Launcher uses outdated Fabric. I specifically downgraded Fabric because of this reason.

**Comment by Snowiiii** [comment]
Your are right, Lunar uses outdated libs, But all Deps i updates should not have any breaking changes and I think that not enough people really using LiquidBounce with Lunar Launcher that we should really Care.

**Comment by 1zun4** [comment]
> Your are right, Lunar uses outdated libs, But all Deps i updates should not have any breaking changes and I think that not enough people really using LiquidBounce with Lunar Launcher that we should really Care.

There are quite a few people using LiquidBounce with Lunar after I started using it myself in the videos. Since we gain nothing by updating the loader version or the FabricAPI (which we do not even use except for the ItemGroup feature), they should be kept to a minimum requirement.

**Pull request merged**
