### PR TITLE
Add glide mode to "Vulcan Highjump"

### PR DESCRIPTION
**Pull request by Razzy52**

### CODE REVIEW

**Comment by Razzy52** [comment]
am i missing something that i need to do?

**Comment by ghost** [comment]
I just need to know if it works.

**Comment by be4dev** [comment]
> am i missing something that i need to do?

this doesn't seem to be working, jump event gets called only when you jump, so glide option will work only 1 time (in fact it wouldn't, because of the falldistance check), so you need to implement it properly

**Comment by be4dev** [comment]
why do you call an event inside of another event?

**Comment by Razzy52** [comment]
> why do you call an event inside of another event?

Is that something that I shouldn't do? Seemed like it'd make sense but I have like no clue what I'm doing
anyways it's to separate when glide and when to jump are triggered. Only problem with this way is that the glide effect stays on even if the player has touched the ground again.

**Comment by be4dev** [comment]
> > why do you call an event inside of another event?
> 
> Is that something that I shouldn't do? Seemed like it'd make sense but I have like no clue what I'm doing anyways it's to separate when glide and when to jump are triggered. Only problem with this way is that the glide effect stays on even if the player has touched the ground again.

I mean it would be logical to create a var called shouldGlide, make it true, when you jump (place event outside of another event) this var becomes true, if it is true you glide (use repeatable) if you are on ground any time, it changes false, simple as that

**Comment by be4dev** [comment]
you shouldn't change highjump settings, you need to have setting called glide, which would be visible to user and var shouldGlide = false which won't be visible for user and you need to change shouldGlide, not glide option (don't forget to check  in glide part if glide and shouldGlide are both true)

**Comment by be4dev** [comment]
> you shouldn't change highjump settings, you need to have setting called glide, which would be visible to user and var shouldGlide = false which won't be visible for user and you need to change shouldGlide, not glide option (don't forget to check in glide part if glide and shouldGlide are both true)

plus why you use PlayerMoveEvent, when repeatable is better?

**Comment by Razzy52** [comment]
https://youtu.be/qqcaZht-xTw

**Comment by be4dev** [comment]
> https://youtu.be/qqcaZht-xTw

nice, but you will still always glide

**Comment by Razzy52** [comment]
> nice, but you will still always glide

i have no clue how to fix this, every solution i've tried just comes up with a worse problem

**Comment by be4dev** [comment]
> > nice, but you will still always glide
> 
> i have no clue how to fix this, every solution i've tried just comes up with a worse problem

https://github.com/Razzy52/LiquidBounce/pull/1
here you go, took a lot of time, cause github sometimes feels hard to use

**Comment by Razzy52** [comment]
gabriel's done the changes. will close

**Pull request closed without merging**
