### PR TITLE
Grim Noweb

### PR DESCRIPTION
**Pull request by Razzy52**
Same method can be used for Phases, Spiders, fastbreak, noliquid and a fair bit more

### CODE REVIEW

**Comment by Razzy52** [comment]
detekt :(

**Comment by 1zun4** [comment]
I don't like that the code for the bypass was implemented into the Mixin. PR on-hold until this is properly implemented.

**Comment by Razzy52** [comment]
I will fix this soonish, not sure how to do it otherwise considering there's no player.isinWeb or similar, and checking what block the player is in doesn't work properly for some reason or atleast the way I did it

**Comment by 1zun4** [comment]
Yeah, you are right. Let me know if you find a good way to do it, would be useful for https://github.com/CCBlueX/LiquidBounce/issues/2577 as well.

**Comment by Fyxar** [comment]
> I will fix this soonish, not sure how to do it otherwise considering there's no player.isinWeb or similar, and checking what block the player is in doesn't work properly for some reason or atleast the way I did it
you can check block at player bounding box to check this

**Comment by Razzy52** [comment]
accidental commits :skull:

**Comment by Razzy52** [comment]
@1zun4 do you want it like this?

**Comment by 1zun4** [comment]
Eh well not really, but better than nothing.

**Pull request merged**
