### PR TITLE
feat(legacy): noslow drop mode

### PR DESCRIPTION
**Pull request by EclipsesDev**
Closes: #4483

### CODE REVIEW

**Comment by EclipsesDev** [comment]
I will figure out tomorrow

**Comment by XeContrast** [comment]
After sending C07, we should stop UsingItem. I don't think it's cost-effective to discard too many items

**Comment by ManInMyVan** [comment]
> After sending C07, we should stop UsingItem. I don't think it's cost-effective to discard too many items

it doesn't (if eclipses "borrowed" my noslow correctly) drop an item every tick, it only drops one.

**Comment by XeContrast** [comment]
> > After sending C07, we should stop UsingItem. I don't think it's cost-effective to discard too many items
> 
> it doesn't (if eclipses "borrowed" my noslow correctly) drop an item every tick, it only drops one.

But long pressing will continue to throw out items, and people may not even instinctively click when they are nervous, and the simulation flag is also due to long pressing

**Comment by ManInMyVan** [comment]
> But long pressing will continue to throw out items

have you even read the code?
```kt
            if (isUsingItem && !hasDropped) { 
                 sendPacket(C07PacketPlayerDigging(DROP_ITEM, BlockPos.ORIGIN, EnumFacing.DOWN)) 
                 shouldNoSlow = false 
                 hasDropped = true
```

**Comment by XeContrast** [comment]
> > But long pressing will continue to throw out items
> 
> have you even read the code?
> 
> ```kotlin
>             if (isUsingItem && !hasDropped) { 
>                  sendPacket(C07PacketPlayerDigging(DROP_ITEM, BlockPos.ORIGIN, EnumFacing.DOWN)) 
>                  shouldNoSlow = false 
>                  hasDropped = true
> ```

OK,my bad

**Comment by EclipsesDev** [comment]
> > After sending C07, we should stop UsingItem. I don't think it's cost-effective to discard too many items
> 
> it doesn't (if eclipses "borrowed" my noslow correctly) drop an item every tick, it only drops one.

Did i do smth wrong?

**Comment by EclipsesDev** [comment]
it seems to not flag simulation if i keep jumping while eating

**Comment by ManInMyVan** [comment]
> > > After sending C07, we should stop UsingItem. I don't think it's cost-effective to discard too many items
> > 
> > it doesn't (if eclipses "borrowed" my noslow correctly) drop an item every tick, it only drops one.
> 
> Did i do smth wrong?

said "if" incase you did something wrong, I haven't tested this implementation

**Comment by ManInMyVan** [comment]
> it seems to not flag simulation if i keep jumping while eating

I've never experienced sim flags with my noslow

**Comment by EclipsesDev** [comment]
> > it seems to not flag simulation if i keep jumping while eating
> 
> I've never experienced sim flags with my noslow

https://streamable.com/dhytcd

**Comment by ManInMyVan** [comment]
> > > it seems to not flag simulation if i keep jumping while eating
> > 
> > I've never experienced sim flags with my noslow
> 
> https://streamable.com/dhytcd

Interesting, I think you did something wrong

**Comment by EclipsesDev** [comment]
> > > > it seems to not flag simulation if i keep jumping while eating
> > > 
> > > 
> > > I've never experienced sim flags with my noslow
> > 
> > 
> > https://streamable.com/dhytcd
> 
> Interesting, I think you did something wrong

https://tenor.com/view/my-honest-reaction-my-honest-reaction-gif-25652576

**Comment by XeContrast** [comment]
> > > > > it seems to not flag simulation if i keep jumping while eating
> > > > 
> > > > 
> > > > I've never experienced sim flags with my noslow
> > > 
> > > 
> > > https://streamable.com/dhytcd
> > 
> > 
> > Interesting, I think you did something wrong
> 
> https://tenor.com/view/my-honest-reaction-my-honest-reaction-gif-25652576

I ran this feature again, and there wasn't a simulation flag in at least 300 GApples I ate

**Comment by EclipsesDev** [comment]
> > > > > > it seems to not flag simulation if i keep jumping while eating
> > > > > 
> > > > > 
> > > > > I've never experienced sim flags with my noslow
> > > > 
> > > > 
> > > > https://streamable.com/dhytcd
> > > 
> > > 
> > > Interesting, I think you did something wrong
> > 
> > 
> > https://tenor.com/view/my-honest-reaction-my-honest-reaction-gif-25652576
> 
> I ran this feature again, and there wasn't a simulation flag in at least 300 GApples I ate

so it works for u?

**Comment by XeContrast** [comment]
> so it works for u?

yes

**Comment by EclipsesDev** [comment]
> > so it works for u?
> 
> yes

this pr and not the one on skidbounce?

**Comment by XeContrast** [comment]
> > > so it works for u?
> > 
> > 
> > yes
> 
> this pr and not the one on skidbounce?

yes

**Comment by EclipsesDev** [comment]
wth its a me issue ig..

**Comment by XeContrast** [comment]
> wth its a me issue ig..

Due to government restrictions, I am unable to access the website you posted, so I am unable to help you analyze the issue

**Comment by EclipsesDev** [comment]
> > wth its a me issue ig..
> 
> Due to government restrictions, I am unable to access the website you posted, so I am unable to help you analyze the issue

its a gif link xd

**Comment by EclipsesDev** [comment]
welp anyway ima merge this since it seems to be a "me" problem idk

**Comment by XeContrast** [comment]
> > > wth its a me issue ig..
> > 
> > 
> > Due to government restrictions, I am unable to access the website you posted, so I am unable to help you analyze the issue
> 
> its a gif link xd

I sometimes can't even access GitHub; XD

**Comment by Husky272** [comment]
This also works well for me

**Pull request merged**
