### PR TITLE
feat: add mospixel bypasses (because @liquidsquid1 won't open his PR again lol)

### PR DESCRIPTION
**Pull request by DataM0del**
I just took the [patch file from #3940](https://github.com/CCBlueX/LiquidBounce/pull/3940.patch), ran `git am 3940.patch`, pushed those, and removed a duplicate import & mode entry
@liquidsquid1 Feel free to open the PR again and I'll close this one.

### CODE REVIEW

**Comment by liquidsquid1** [comment]
the pr was closed because none of the bypasses were useful and they got outdated pretty quickly, no need for you to take my code and pull request it.

**Comment by DataM0del** [comment]
Vec3d destructuring broken momento

**Comment by liquidsquid1** [comment]
?

**Comment by DataM0del** [comment]
> ?

Check CI lol
Also, it should work because it works for the Damage module, but not for the flies?
image

**Comment by DataM0del** [comment]
> the pr was closed because none of the bypasses were useful and they got outdated pretty quickly, no need for you to take my code and pull request it.

last time I tested, the zoom fly worked. Also, if it's outdated, then update them!

**Comment by liquidsquid1** [comment]
or, hear me out, don’t try to contribute other people’s code which has outdated bypasses

**Comment by DataM0del** [comment]
> or, hear me out, don’t try to contribute other people’s code which has outdated bypasses

"the bypass is 1 month old, it's outdated, so lets not use it, it works, but it's outdated"

**Comment by liquidsquid1** [comment]
> > the pr was closed because none of the bypasses were useful and they got outdated pretty quickly, no need for you to take my code and pull request it.
> 
> last time I tested, the zoom fly worked. Also, if it's outdated, then update them!

I can update the bypasses when I start a new pull request with new bypasses. I have other servers to focus on and alot better bypasses to make.

**Comment by ccetl** [comment]
It should be up to @liquidsquid1 if he wants his code in the client.

**Comment by liquidsquid1** [comment]
> > or, hear me out, don’t try to contribute other people’s code which has outdated bypasses
> 
> "the bypass is 1 month old, it's outdated, so lets not use it, it works, but it's outdated"

It was made on one of my first days of mospixel, testing stuff out. I have since then made an almost full movement disabler and full timer disabler.

**Comment by DataM0del** [comment]
> > > or, hear me out, don’t try to contribute other people’s code which has outdated bypasses
> > 
> > 
> > "the bypass is 1 month old, it's outdated, so lets not use it, it works, but it's outdated"
> 
> It was made on one of my first days of mospixel, testing stuff out. I have since then made an almost full movement disabler and full timer disabler.

Those disablers aren't public, so what am I supposed to do, read your mind through the screen and send your code that I read through the screen and from your mind into a repository?

**Comment by liquidsquid1** [comment]
> > > > or, hear me out, don’t try to contribute other people’s code which has outdated bypasses
> > > 
> > > 
> > > "the bypass is 1 month old, it's outdated, so lets not use it, it works, but it's outdated"
> > 
> > 
> > It was made on one of my first days of mospixel, testing stuff out. I have since then made an almost full movement disabler and full timer disabler.
> 
> Those disablers aren't public, so what am I supposed to do, read your mind through the screen and send your code that I read through the screen and from your mind into a repository?

No, you are supposed to wait for me to finish whatever server I am currently working on bypasses for (currently it’s hylex*) and then I can upgrade and improve my current bypasses for other servers before pull requesting them.

**Comment by liquidsquid1** [comment]
Thanks izuna 👍

**Comment by DataM0del** [comment]
> > > > > or, hear me out, don’t try to contribute other people’s code which has outdated bypasses
> > > > 
> > > > 
> > > > "the bypass is 1 month old, it's outdated, so lets not use it, it works, but it's outdated"
> > > 
> > > 
> > > It was made on one of my first days of mospixel, testing stuff out. I have since then made an almost full movement disabler and full timer disabler.
> > 
> > 
> > Those disablers aren't public, so what am I supposed to do, read your mind through the screen and send your code that I read through the screen and from your mind into a repository?
> 
> No, you are supposed to wait for me to finish whatever server I am currently working on bypasses for (currently it’s hylex*) and then I can upgrade and improve my current bypasses for other servers before pull requesting them.

Well, why not just use what's public for now and use what's public while you're finishing other bypasses? Something is better than nothing (I do have a funny pulse timer that flags but it technically works but it's stupid and not as fast as this).

**Comment by DataM0del** [comment]
> It should be up to @liquidsquid1 if he wants his code in the client.

He opened a PR, he wanted it to be merged, but then he randomly deleted the head repository, and GitHub automatically closed it.

**Comment by liquidsquid1** [comment]
> > It should be up to @liquidsquid1 if he wants his code in the client.
> 
> He opened a PR, he wanted it to be merged, but then he randomly deleted the head repository, and GitHub automatically closed it.

I deleted the head repository because it was useless, so was my other bypasses in the fork. I instantly made a new fork and populated it with newer bypasses.

Unfortunately, you aren’t me. You don’t get to decide what happens with my code.

**Comment by ccetl** [comment]
> > It should be up to @liquidsquid1 if he wants his code in the client.
> 
> He opened a PR, he wanted it to be merged, but then he randomly deleted the head repository, and GitHub automatically closed it.

"wanted" != wants
He should decide what happens to his code. Although you can technically copy it, even tho he doesn't want it, as it's licensed under GPL 3.0, it's incredible rude and it won't get accepted here.

**Pull request closed without merging**
