### PR TITLE
fix(legacy): InventoryManager Memory Leak

### LINKED ISSUE #3206: [BUG] 2GB/s garbage collection rate on LiquidBounce Legacy
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

b93

### Operating System

Windows 11

### Minecraft Version

1.8 (Legacy)

### Describe the bug

Without any modules enabled, memory immediately starts allocating and garbage collecting at a rate of almost 2 gigabytes per second, causing severe lag spikes and an unusable experience.

No mods are enabled except LiquidBounce and OptiFine.
javaw_14lvuGpUVX
With VisualVM profiling, I can immediately see that these 3 functions allocate millions of objects per second and are likely the biggest culprit behind this.
image

### Steps to reproduce

Load latest LB legacy as mod
Launch with Forge
Profit

### Client Log

```shell
N/A
```

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by EclipsesDev**
An attempt to fixed #3206

Not sure if this is working, so someone can help me by testing this

### CODE REVIEW

**Comment by cicuka** [comment]
when off:
image
when on:
image

**Comment by EclipsesDev** [comment]
> when off: image when on: image

is that picture the opposite?

**Comment by cicuka** [comment]
it was kind of changing very rapidly

**Comment by cicuka** [comment]
on:
image
off:
image

its going up and down so i can't really send an accurate picture
maxiumum it hit was around 22000000B when on
and arond 18000000B when off

**Comment by EclipsesDev** [comment]
> on: image off: image
> 
> its going up and down so i can't really send an accurate picture maxiumum it hit was around 22000000B when on and arond 18000000B when off

So can u compare the build with this fixes, and the one without this fix?

**Comment by cicuka** [comment]
sorry for the late reply
image
the difference is obvious

**Comment by EclipsesDev** [comment]
> sorry for the late reply without fix: image with fix: image
> 
> the difference is obvious

great ig its working

**Comment by EclipsesDev** [comment]
Hopefully it works for everyone

**Comment by EclipsesDev** [comment]
ah shit it broke it

**Comment by EclipsesDev** [comment]
ok wait i fixed it

**Pull request merged**
