### PR TITLE
added flagcheck

### PR DESCRIPTION
**Pull request by larryngton2**
pretty basic, i tried porting the one on legacy and in turn i lost half of my braincells (still managed to port most of it)

### CODE REVIEW

**Comment by EclipsesDev** [comment]
:3

**Comment by larryngton2** [comment]
> :3

:33

**Comment by larryngton2** [comment]
i will not add ghostblock checks because they false allot

**Comment by larryngton2** [comment]
working on chat alerts rn

**Comment by larryngton2** [comment]
i HATE you detekt.

**Comment by larryngton2** [comment]
merge?

**Pull request merged**
