### PR TITLE
[LEGACY] Added RandomNames option to NameProtect

### PR DESCRIPTION
**Pull request by EclipsesDev**

### CODE REVIEW

**Comment by 1zun4** [comment]
Should this not be an option in NameProtect instead?

**Comment by EclipsesDev** [comment]
> Should this not be an option in NameProtect instead?

huh?

**Comment by EclipsesDev** [comment]
> Should this not be an option in NameProtect instead?

This is an option actually ;-;

**Comment by 1zun4** [comment]
> > Should this not be an option in NameProtect instead?
> 
> This is an option actually ;-;

Rip

**Comment by EclipsesDev** [comment]
> > > Should this not be an option in NameProtect instead?
> > 
> > 
> > This is an option actually ;-;
> 
> Rip

Why rip? I don't really understand what you tryna say here.. 😅

**Comment by 1zun4** [comment]
> > > > Should this not be an option in NameProtect instead?
> > > 
> > > 
> > > This is an option actually ;-;
> > 
> > 
> > Rip
> 
> Why rip? I don't really understand what you tryna say here.. 😅

I thought you said the option already exists, which makes this PR useless?

**Comment by EclipsesDev** [comment]
> > > > > Should this not be an option in NameProtect instead?
> > > > 
> > > > 
> > > > This is an option actually ;-;
> > > 
> > > 
> > > Rip
> > 
> > 
> > Why rip? I don't really understand what you tryna say here.. 😅
> 
> I thought you said the option already exists, which makes this PR useless?

Oh mb, thats not what i mean.. this is new option that i added to NameProtect actually

**Comment by 1zun4** [comment]
Omg I am stupid. I read NameTags and was like: huh? why in nametags. Sorry! My bad.

**Comment by EclipsesDev** [comment]
> Omg I am stupid. I read NameTags and was like: huh? why in nametags. Sorry! My bad.

No worries lol

**Comment by EclipsesDev** [comment]
@mems01 you can merge this one too

**Pull request merged**
