### PR TITLE
Added a few more modules.

### PR DESCRIPTION
**Pull request by ghost**
AntiLevitation and BoatFly module complete a requirement based on this [post.](https://github.com/CCBlueX/LiquidBounce/issues/364)

EDIT: Those modules I just added (ModuleFreeze + ModuleBedGodMode) also almost have to do with that no-clip bug, that's why I added a `//`. They would cause errors for `Val cannot be reassigned`.

Added SuperKnockback/Parkour/SkinDerp modules
Added a mode to Fly module.

### CODE REVIEW

**Comment by mems01** [comment]
What a... MESSY Pull Request.

**Comment by Teals53** [comment]
xD

**Comment by 1zuna-chan** [comment]
Don't worry. I'll merge it soon.

**Comment by mems01** [comment]
Removed PingSpoof, there's an incoming PR as of (4/2/2021) regarding that.

**Comment by 1zuna-chan** [comment]
If you're asking why I removed your anti levitation module. It works, but shouldn't be implemented this way. It should just cancel the motion of the levitation effect using Mixin.

**Comment by mems01** [comment]
Well, I have no idea how Mixins work, so I guess I should leave it to you.

**Pull request merged**
