### PR TITLE
fix(legacy): fix the LocalTheme command

### PR DESCRIPTION
**Pull request by Coccocoahelper**
Fix the LocalTheme command saving theme files without the .json file extension.

### CODE REVIEW

**Comment by EclipsesDev** [comment]
uhmm @Coccocoahelper so tell me exactly what does using `.json` file gonna do?

**Comment by EclipsesDev** [comment]
oh my bad

**Comment by EclipsesDev** [comment]
ok it work "sorta" but u gotta make it save themes in `.json` too since it will deem the themes file invalid if its not json.. same with delete, list commands

**Comment by Coccocoahelper** [comment]
> oh my bad

It's alright, just squash the commits and nobody's gonna notice.

**Comment by Coccocoahelper** [comment]
> ok it work "sorta" but u gotta make it save themes in `.json` too since it will deem the themes file invalid if its not json.. same with delete, list commands

Ok, but how do I remove the .json text from the list command?

**Comment by EclipsesDev** [comment]
> > oh my bad
> 
> It's alright, just squash the commits and nobody's gonna notice.

yeah, you just need to fix the issue that i mention above, then it should be ready

**Comment by Coccocoahelper** [comment]
> > > oh my bad
> > 
> > 
> > It's alright, just squash the commits and nobody's gonna notice.
> 
> yeah, you just need to fix the issue that i mention above, then it should be ready

I think it's done.

**Pull request merged**
