### PR TITLE
[LEGACY] Dynamic Values, fixes?

### PR DESCRIPTION
**Pull request by gabrielvicenteYT**
Ok, this is going to take a while.

### CODE REVIEW

**Comment by CzechHek** [comment]
Why should close delay be forced to 0 when max taking delay is set to 0?

**Comment by gabrielvicenteYT** [comment]
> Why should close delay be forced to 0 when max taking delay is set to 0?

It sometimes bugs out, at least randomly.

**Comment by 1zun4** [comment]
> > Why should close delay be forced to 0 when max taking delay is set to 0?
> 
> It sometimes bugs out, at least randomly.

random 0 0 should always return 0, if not, fix this, not do anything else.

**Comment by 1zun4** [comment]
Did you make sure that it only returns 0?

**Comment by gabrielvicenteYT** [comment]
> Did you make sure that it only returns 0?

I think that it does.

**Pull request merged**
