### PR TITLE
Karhu Velocity

### PR DESCRIPTION
**Pull request by RtxOP**

### CODE REVIEW

**Comment by RtxOP** [comment]
ignore the old commits being here

**Comment by superblaubeere27** [comment]
What does this do to reduce velocity?

**Comment by RtxOP** [comment]
> What does this do to reduce velocity?

Offset bounding box so you collide with it and reduce velocity

**Comment by ghost** [comment]
Yes, simulate collision by telling the client that there are blocks around you, cool. The question we should really be asking is, is this stolen code?

**Comment by RtxOP** [comment]
public bypass

**Comment by ghost** [comment]
Expected a better answer:

https://github.com/Spinyfish/Client-Hall-Of-Fame/blob/main/leaks/alan32/NOT_RISE_CLIENT-6.0-MAIN-FROM-GIT/client/src/main/java/com/alan/clients/module/impl/combat/velocity/KarhuVelocity.java

The code is very similar, no?

**Comment by RtxOP** [comment]
> Expected a better answer:
> 
> https://github.com/Spinyfish/Client-Hall-Of-Fame/blob/main/leaks/alan32/NOT_RISE_CLIENT-6.0-MAIN-FROM-GIT/client/src/main/java/com/alan/clients/module/impl/combat/velocity/KarhuVelocity.java
> 
> The code is very similar, no?

That's what a public bypass is

**Pull request closed without merging**
