### PR TITLE
Update ModuleSpoofer.kt

### PR DESCRIPTION
**Pull request by opZywl**
Lunar changed version brand

### CODE REVIEW

**Comment by EclipsesDev** [comment]
i mean whats the point tho? since lunar client update all the time, i mean if your willing to update it everytime then ig so

**Comment by opZywl** [comment]
> i mean whats the point tho? since lunar client update all the time, i mean if your willing to update it everytime then ig so

It would be pointless to maintain a lunar brand that doesn't work, the solution will be to update as usual

**Comment by opZywl** [comment]
other than that the old model is very old

**Comment by EclipsesDev** [comment]
> > i mean whats the point tho? since lunar client update all the time, i mean if your willing to update it everytime then ig so
> 
> It would be pointless to maintain a lunar brand that doesn't work, the solution will be to update as usual

meaning manual version update?

**Comment by EclipsesDev** [comment]
ig thats fine

**Comment by opZywl** [comment]
> > > i mean whats the point tho? since lunar client update all the time, i mean if your willing to update it everytime then ig so
> > 
> > 
> > It would be pointless to maintain a lunar brand that doesn't work, the solution will be to update as usual
> 
> meaning manual version update?

yes!!

**Pull request merged**
