### PR TITLE
KillAura MouseInertia

### PR DESCRIPTION
**Pull request by ghost**
MouseInertia simulates mouse inertia.
With MouseInertia, you can bypass polar ac.
This can be substituted for GaussianOffset and OutOfBox.
I don't know if it works on Intave etc.

https://www.youtube.com/watch?v=lKe3vt-l0mQ

### CODE REVIEW

**Comment by ghost** [comment]
> On the above video, I turned off guassianOffset and outOfBox

**Comment by Cosmic-SC** [comment]
what protocol version were you using in the video?

**Comment by ghost** [comment]
1.19.4

**Comment by Cosmic-SC** [comment]
ok thanks :)

**Comment by superblaubeere27** [comment]
Video looks good

**Comment by 182exe** [comment]
woah thats cool

**Comment by 1zun4** [comment]
I am sorry but what does this affect? From reviewing the code, all it changes is the rotation passed to the `facingEnemy` check.
I get the idea, but the implementation seems wrong. Or did I misunderstood the purpose?

Currently it is implement right before the attack:
image

But to affect the rotation itself it would be required to be implemented here:
image

**Pull request closed without merging**
