### PR TITLE
[LEGACY] Allow players to sneak while in an Inventory in InventoryMove

### PR DESCRIPTION
**Pull request by gabrielvicenteYT**
This will make the Intave InventoryMove option work, I think.

### CODE REVIEW

**Comment by 1zun4** [comment]
Oh, that should be an option. Not everyone wants to sneak within the inventory, can be quite annoying.

**Comment by CzechHek** [comment]
You know that shift clicking is a thing?

**Comment by EclipsesDev** [comment]
> Oh, that should be an option. Not everyone wants to sneak within the inventory, can be quite annoying.

yeah sneaking in inventory is sort of annoying

**Comment by gabrielvicenteYT** [comment]
Ok, time to quickly fix it up

**Comment by gabrielvicenteYT** [comment]
@1zun4 @CzechHek This should be fixed.

**Comment by gabrielvicenteYT** [comment]
erm, wtf

**Comment by Jpx3** [comment]
Interesting, thanks for reporting

**Pull request closed without merging**
