### PR TITLE
More module addition.

### PR DESCRIPTION
**Pull request by mems01**
AutoWalk: I would've also added the if statement `if (!mc.gameSettings.isKeyDown(mc.gameSettings.keyBindForward))` (1.8.9), but I didn't know how to code it the 1.16.5 way.

### CODE REVIEW

**Comment by 1zuna-chan** [comment]
It seems NoClip doesn't work. I'll try to find out why.

**Comment by mems01** [comment]
Could be probably because of that `player.noclip` thing. If so, there are also some other codes like `player.isdead` which don't really work as they are supposed to.

**Comment by 1zuna-chan** [comment]
Exactly. It's being overwritten by .

**Comment by mems01** [comment]
And probably not only that, but also some other ones. `player.isSleeping`, `player.sleepingTimer`, while I was trying to make the BedGodMode module.

**Comment by 1zuna-chan** [comment]
I fixed the issue by adding a new tick event caused by the "tickMovement" method.
https://github.com/CCBlueX/LiquidBounce/commit/1badd18d114e251496f3c10e061cfffe76bfb06a

**Comment by 1zuna-chan** [comment]
Now is the question... Should sequences base on the movement tick event instead of tick event?

**Comment by mems01** [comment]
That is something you should decide I guess, as you obviously have way more knowledge.

**Comment by 1zuna-chan** [comment]
https://github.com/CCBlueX/LiquidBounce/commit/f022896e01639a4369a0db85c91f26846deff2f8

**Comment by 1zuna-chan** [comment]
It makes more sense to use the movement tick instead of right at the top of the player tick.

**Pull request merged**
