### PR TITLE
CI: GitHub code scanning integration for detekt errors / warnings

### PR DESCRIPTION
**Pull request by DataM0del**
This PR pretty much just adds more QoL. Nothing really useful for anyone who isn't reviewing the code for PRs.
See https://docs.github.com/en/code-security/code-scanning/introduction-to-code-scanning/about-code-scanning#about-third-party-code-scanning-tools

I just stole it from the detekt docs, GitHub adds a little embed at the end of the line which shows the workflow and some other info from the SARIF file you give it.
Another tip that I discovered: If you click on the SARIF file that detekt generates, IntelliJ IDEA will show everything detekt found in the "Server-side Analysis" tab of the "Problems" view.
See https://detekt.dev/docs/introduction/reporting/#integration-with-github-code-scanning

### CODE REVIEW

**Comment by DataM0del** [comment]
intentionally triggering detekt for demonstration, that commit will be reverted immediately after the CI is done.

**Comment by DataM0del** [comment]
well, actually, that's a good demo.

**Comment by DataM0del** [comment]
now to revert the commit!

**Comment by DataM0del** [comment]
this is how it looks inline when viewing the commit diff (and probably the PR diff too)
image

**Comment by larryngton2** [comment]
nice

**Comment by 1zun4** [comment]
Good

**Pull request merged**
