### PR TITLE
1.16 InventoryMove and LiquidWalk

### PR DESCRIPTION
**Pull request by 2933968621**

### CODE REVIEW

**Comment by mems01** [comment]
Try inserting this code on ModuleManager: `import net.ccbluex.liquidbounce.features.module.modules.movement.ModuleInventoryMove`

**Comment by 2933968621** [comment]
> 您忘记在ModuleManager中插入以下代码： `import net.ccbluex.liquidbounce.features.module.modules.movement.ModuleInventoryMove`

yes,I forgot it

**Comment by mems01** [comment]
You also forgot to add the `.kt` extension on ModuleInventoryMove.

**Comment by 2933968621** [comment]
> You also forgot to add the `.kt` extension on ModuleInventoryMove.

omg...

**Comment by mems01** [comment]
Well, everyone does mistakes.

**Comment by 2933968621** [comment]
> 好吧，每个人都会犯错误。

= =

**Comment by 1zuna-chan** [comment]
LiquidWalk is missing many features and I probably do it myself, but thank you. I'll close this one because there is a separate pull request to your InventoryMove:
https://github.com/CCBlueX/LiquidBounce/pull/356

**Pull request closed without merging**
