### PR TITLE
[LEGACY] Added new modules "TimerRange" (Basic)

### PR DESCRIPTION
**Pull request by EclipsesDev**
Note: This TimerRange Code is still basic, although I might improve it or maybe someone else could.. So please don't expect it to work like other TimerRange Hack Client

But I guess this should be enough to bypass some AntiCheats like Verus, NCP, and others maybe. (only if configured correctly)

### CODE REVIEW

**Comment by EclipsesDev** [comment]
And yes, it doesn't have any advanced algorithm yet

**Comment by be4dev** [comment]
> Note: This TickBase Code is still basic, although I might improve it or maybe someone else could.. So please don't expect it to work like other TickBase Hack Client
> 
> But I guess this should be enough to bypass some AntiCheats like Verus, NCP, and others maybe. (only if configured correctly)

bruh, this is timerRange, not tickBase

**Comment by EclipsesDev** [comment]
> > Note: This TickBase Code is still basic, although I might improve it or maybe someone else could.. So please don't expect it to work like other TickBase Hack Client
> > But I guess this should be enough to bypass some AntiCheats like Verus, NCP, and others maybe. (only if configured correctly)
> 
> bruh, this is timerRange, not tickBase

owhh.. I guess I'll rename it, my bad.. but I'll do it tomorrow

**Comment by EclipsesDev** [comment]
Alr, renamed*

**Comment by EclipsesDev** [comment]
You know what, I'll recode and make the code a bit better and made some changes.. canceling pull request*

**Pull request closed without merging**
