### PR TITLE
[LEGACY] Added bounding box event for ScriptAPI

### PR DESCRIPTION
**Pull request by halflin**
This will allow scripts to have access to the bounding box event. This can be useful to make some speeds, flys or even velocitys.

### CODE REVIEW

**Comment by 1zun4** [comment]
The BlockBB event is called way too often for it to be used for the ScriptAPI. It was intentional to not be added and was removed due to performance reasons.

**Comment by halflin** [comment]
Maybe calling the event only for the player could be a way to do it.

**Comment by CzechHek** [comment]
Core library provides access to all events using hacky ways. Using onBB doesn't seem like a performance problem, it was used in some scripts. Even onText usage is viable: https://youtu.be/3H-7PM2gQag

**Comment by 1zun4** [comment]
> Maybe calling the event only for the player could be a way to do it.

"only the player?" You mean, blocks that surround the player? Hm no I dont like... 

> Core library provides access to all events using hacky ways. Using onBB doesn't seem like a performance problem, it was used in some scripts. Even onText usage is viable: https://youtu.be/3H-7PM2gQag

We have never measured it but my guess was that it would be called too often. But Nashorn does compile everything to Java anyway, so it might perform well enough.

**Comment by halflin** [comment]
> "only the player?" You mean, blocks that surround the player? Hm no I dont like...

Why would you want entities that aren't the player to call BlockBBEvent?

**Comment by 1zun4** [comment]
> > "only the player?" You mean, blocks that surround the player? Hm no I dont like...
> 
> Why would you want entities that aren't the player to call BlockBBEvent?

Ehm? BlockBB has nothing to do with entities or players. :laughing:

**Comment by halflin** [comment]
> Ehm? BlockBB has nothing to do with entities or players. 😆

On the method addCollisionBoxesToList on the Block mixin, i think it would be better to check if the colliding entity is the player, so it only calls the event for the player.

**Pull request closed without merging**
