### PR TITLE
feat: Scaffold block counter as HUD component

### PR DESCRIPTION
**Pull request by MukjepScarlet**
image

### CODE REVIEW

**Comment by MukjepScarlet** [comment]
#3930 
Another edition of #4112 
@ccetl

**Comment by Jucku** [comment]
Maybe also make an option to enable block display, which block is being placed/used.

**Comment by MukjepScarlet** [comment]
I don't know how to draw an item with web UI, it could be much easier with native.

**Comment by rejomy** [comment]
+1

**Review by 1zun4 — APPROVED** [review]
The code looks good. The implementation of displaying the block that is selected is fairly easy to add. Take a look at the implementation of the `BlockSetting`.

**Review by SenkJu — APPROVED** [review]
I made some modifications to the code and moved the element to the left of the crosshair by default.

image

**Pull request merged**
