### PR TITLE
Added FastUse module

### PR DESCRIPTION
**Pull request by ghost**
* FastUse and other modules which utilize the `PlayerMoveC2SPacket` packet do not work in Singleplayer or in 1.9+ versions. It does work on ViaVersion supported servers though.

### CODE REVIEW

**Comment by 1zun4secondary** [comment]
Please don't change anything on the InventoryCleaner. You just changed everything to inner class.

**Comment by ghost** [comment]
> Please don't change anything on the InventoryCleaner. You just changed everything to inner class.

there was an extra `}` on a function, which caused that weird icon, I don't think I caused something serious.

**Comment by 1zun4secondary** [comment]
No. This is not some weird icon. This just means that this is a kotlin file. Please revert this. You changed the entire structure of the file to inner classes.

**Comment by ghost** [comment]
Well your choice. I tested the module and it works as fine as it did without the changes, but whatever

**Pull request merged**
