### PR TITLE
[FEATURE] Legit Target Strafe for GrimCollide Speed

### PR DESCRIPTION
**Pull request by ghost**
Added an option for grim collide speed allow you to strafe around the other entity

### CODE REVIEW

**Comment by 1zun4** [comment]
code needs big clean-up

**Comment by ghost** [comment]
> code needs big clean-up
uh oh

**Comment by ghost** [comment]
I messed something up :)

**Comment by ghost** [comment]
ok should be opk noiw

**Comment by ghost** [comment]
closed, this is a mess, I will create a new one when everything is ok

**Comment by ghost** [comment]
this is also incomplete, will be reopen as a new pr

**Pull request closed without merging**
