### PR TITLE
GraalJS ScriptAPI integration

### PR DESCRIPTION
**Pull request by 1zun4secondary**
We hope to upgrade our ScriptAPI for Nextgen to [GraalJS](https://github.com/oracle/graaljs), which is a high performance implementation of the JavaScript programming language. It's also compatible with the [ECMAScript 2020](https://262.ecma-international.org/11.0/) specification.
The main issue with using a new engine is the remapping of Minecraft. It took us a while to figure out how to remap nashorn.
Now we decided to try GraalJS.

### CODE REVIEW

**Comment by banocean** [comment]
any updates?

**Comment by 1zun4secondary** [comment]
Not at the moment. @oceaann

**Comment by weewoo22** [comment]
Unrelated to changing the scripting backend, but would someone mind addressing the comment I made on https://github.com/CCBlueX/LiquidBounce/commit/f7f0071f80e05dec781b853120c1fcc4bc60173f#commitcomment-60410478 while Nashorn continues to be used in the meantime.

**Comment by banocean** [comment]
Is there deadline for this pr?

**Comment by 1zun4secondary** [comment]
Pull request replaced by https://github.com/CCBlueX/LiquidBounce/pull/916

**Pull request closed without merging**
