### PR TITLE
ncp lowhop

### PR DESCRIPTION
**Pull request by liquidsquid1**
The speed will be very customisable due to there being not many servers using just ncp, features for vulcan and verus to work too is included.

The task list will be completed per option, here is the list of options that will be in the speed.

- [ ] Ticks Until Fall (4..6)
- [ ] Lowhop Speed (0..0.5)
- [ ] Potion Modifier (0..0.1)
- [ ] Faster Fall (true/false)
- [ ] Horizontal Modification (true/false)
- [ ] Damage Strafe (0..3) (0 will disable the damage strafe)
- [ ] YPort (true/false)

### CODE REVIEW

**Comment by localpthebest** [comment]
skidded from nightx

**Comment by ion1x** [comment]
> skidded from nightx

if you are serious that value is an actual minecraft value which is why its exempt from verus

**Comment by localpthebest** [comment]
> > skidded from nightx
> 
> if you are serious that value is an actual minecraft value which is why its exempt from verus

bro does not know

**Comment by Some1whosAnonymous** [comment]
looks good

**Comment by ghost** [comment]
Skudded from augustus 45 degree speed

**Comment by liquidsquid1** [comment]
> Skudded from augustus 45 degree speed

?

**Comment by eonianisnoob** [comment]
skidded from nightx smh

**Comment by liquidsquid1** [comment]
> skidded from nightx smh

i haven’t even properly started yet? 😭

**Comment by larryngton2** [comment]
> > skidded from nightx smh
> 
> i haven’t even properly started yet? 😭

skidded from #3798 !!!!!!!!!!!!!!!!!!!

**Comment by 1zun4** [comment]
Is this still being completed or can it be closed?

**Comment by liquidsquid1** [comment]
> Is this still being completed or can it be closed?

I guess it can be closed, the current nocheatplus speed is good enough 🤷

**Pull request closed without merging**
