### PR TITLE
feat: module zoom

### PR DESCRIPTION
**Pull request by ccetl**

### CODE REVIEW

**Comment by 1zun4** [comment]
Maybe we should implement bind types e.g hold, toggle for this exact type of module. Bind system needs to be reworked anyway for mouse button support.

**Comment by superblaubeere27** [comment]
> Maybe we should implement bind types e.g hold, toggle for this exact type of module. Bind system needs to be reworked anyway for mouse button support.

`QuickPerspectiveSwap` would profit from that too.

**Comment by ccetl** [comment]
> > Maybe we should implement bind types e.g hold, toggle for this exact type of module. Bind system needs to be reworked anyway for mouse button support.
> 
> `QuickPerspectiveSwap` would profit from that too.

Yeah I already made that but didn't create a pull request yet.

**Comment by ccetl** [comment]
> > > Maybe we should implement bind types e.g hold, toggle for this exact type of module. Bind system needs to be reworked anyway for mouse button support.
> > 
> > 
> > `QuickPerspectiveSwap` would profit from that too.
> 
> Yeah I already made that but didn't create a pull request yet.

#4002

**Comment by 1zun4** [comment]
merge conflict

**Comment by ccetl** [comment]
> merge conflict

resolved

**Pull request merged**
