### PR TITLE
Telly scaffold and alternation

### PR DESCRIPTION
**Pull request by RtxOP**
Some things that need to be fixed:
 - update() is called twice because the player keeps falling and I took the easy way out.
 - Some might call how I implemented the telly cheap.
 Other than that the alternation is neatly implemented.

### CODE REVIEW

**Comment by ghost** [comment]
Great addition. However I'd like to point out a few things you could simplify:

* The update function is called twice because the other one is called on tick (line 396). If the mode is designed to work specifically every frame, then you're better off making a chosen mode check on line 396 and on the Render3D event.
* The if statement you made on the strafe event could also be moved to the TickEvent or the UpdateEvent, unless you have already tried it and they don't work.
> * Some might call how I implemented the telly cheap.

If it imitates an actual telly-bridger, then it's fine by me at least.

**Comment by RtxOP** [comment]
TODO:
 - Set pitch to 90 when facing player yaw to not flag for Rotation-Place on GrimAC. (how I implemented the telly doesnt allow me to do that)

**Comment by ghost** [comment]
Okay so I tested your mode and I noticed an issue with the keep rotation ticks. If it is too high it might not work as well?

**Comment by RtxOP** [comment]
> Okay so I tested your mode and I noticed an issue with the keep rotation ticks. If it is too high it might not work as well?

keep rotation should be on and keep ticks should be 1 at all times yes.

**Comment by gabrielvicenteYT** [comment]
I was BEGGING for this addition, thank god someone is doing this already.

**Comment by NCPUser** [comment]
Work On Intave B14,AAC 4.4.2?

**Comment by ghost** [comment]
Wonder about the bypasses later, at the moment he has to fix the issues.

**Comment by NCPUser** [comment]
okay im wait

**Comment by RtxOP** [comment]
That is as far as I can go with this for now.

**Comment by ghost** [comment]
@RtxOP The chances of falling were high because the client as default doesn't have that much search range. I have increased it to 3 blocks search for now, but beware the relatively high chance that scaffold might place blocks as if you spread butter on a bread when there are blocks around you.

I also renamed the options to something a bit more appropriate and user friendly. Oh and I also removed the update function from the render event because it's no longer needed. The tick event can achieve the same results. 👍

**Pull request merged**
