### PR TITLE
refactor(legacy) rename the `VulcanGhost` fly mode to `VulcanBlink`

### PR DESCRIPTION
**Pull request by Coccocoahelper**
If I was a new cheater, I'd be very confused by the current name; this pull request fixes that.

### CODE REVIEW

**Comment by EclipsesDev** [comment]
Unnecessary pull, infact the cheating community nows the fly as VulcanGhost

**Comment by EclipsesDev** [comment]
plus the bypass is not in the cancelling packet part.. its actually ghostblock fly like collide fly

**Comment by Coccocoahelper** [comment]
> plus the bypass is not in the cancelling packet part.. its actually ghostblock fly like collide fly

Wrong. The bypass depends on the cancelling packets part to trick Vulcan. Any normal airwalk fly (even Rewinside) + Blink can bypass Vulcan, given that it's used properly.

**Comment by EclipsesDev** [comment]
> > plus the bypass is not in the cancelling packet part.. its actually ghostblock fly like collide fly
> 
> Wrong. The bypass depends on the cancelling packets part to trick Vulcan. Any normal airwalk fly (even Rewinside) + Blink can bypass Vulcan, given that it's used properly.

Ok i agree with that, but I still don't think to necessarily changing its name 👍

**Pull request closed without merging**
