### PR TITLE
[LEGACY] colormixer and hud designer(module)

### PR DESCRIPTION
**Pull request by wxzex**

### CODE REVIEW

**Comment by wxzex** [comment]
colormixer from lb+ but still it is a cool visual

**Comment by gabrielvicenteYT** [comment]
A lot of stuff that you added is in Java (we use Kotlin when possible), you edited visuals that are not supposed to be changed, and you added a HUDDesigner module when there is a ClickGUI icon that does it. @mems01, reject this pull request.

**Comment by 1zun4** [comment]
Rejecting this PR due to removal of LiquidChat, Update Notifications, introducing non-sense modules, changing cloud parameters to non-official sources and so on.

**Comment by EclipsesDev** [comment]
💀

**Pull request closed without merging**
