### PR TITLE
fixed building

### PR DESCRIPTION
**Pull request by ghost**
Apparently this code somehow fixes that build.gradle error which is making LiquidBounce not load at all.

### CODE REVIEW

**Comment by ghost** [comment]
More information needed, sure. This is the error that occured to me yesterday and today:

```
Starting Gradle Daemon...
Gradle Daemon started in 1 s 387 ms
Configure project :
Fabric Loom: 0.9.41
The 'accessWidener' property has been deprecated, and has been replaced with 'accessWidenerPath'. This is scheduled to be removed in Loom 0.11.
The 'minecraft' property has been deprecated, and has been replaced with 'loom'. This is scheduled to be removed in Loom 0.11.
Deprecated Loom APIs were used in this build, making it incompatible with future versions of Loom. Use Gradle warning modes to control the verbosity of the warnings.
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.1-rc-2/userguide/command_line_interface.html#sec:command_line_warnings
FAILURE: Build completed with 2 failures.
1: Task failed with an exception.
-----------
Where:
Build file 'C:\Users\Heheboii\Desktop\New folder\liquidbounce\build.gradle' line: 48
What went wrong:
A problem occurred evaluating root project 'liquidbounce'.
No signature of method: build_5j1c22m2yqevf5xjj2zueb979.minecraft() is applicable for argument types: (build_5j1c22m2yqevf5xjj2zueb979$_run_closure2) values: [build_5j1c22m2yqevf5xjj2zueb979$_run_closure2@4feb2fca]
Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================
2: Task failed with an exception.
-----------
What went wrong:
A problem occurred configuring root project 'liquidbounce'.
No 'minecraft' dependency was specified!
Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================
Get more help at https://help.gradle.org
BUILD FAILED in 7s
```

And it got fixed by this code above.

**Comment by 1zun4secondary** [comment]
```
The 'accessWidener' property has been deprecated, and has been replaced with 'accessWidenerPath'. This is scheduled to be removed in Loom 0.11.
The 'minecraft' property has been deprecated, and has been replaced with 'loom'. This is scheduled to be removed in Loom 0.11.
```

I see.

**Comment by ghost** [comment]
I'm sure there might be a better method to fix this but at least this code fixed the problems.

**Comment by 1zun4secondary** [comment]
Doesn't matter if the building is broken anyway.

**Pull request merged**
