### PR TITLE
refactor(legacy): clean up code

### PR DESCRIPTION
**Pull request by Coccocoahelper**
Better code = better life.

### CODE REVIEW

**Comment by Coccocoahelper** [comment]
Please test this, it might improve the code a lot.

**Comment by EclipsesDev** [comment]
you need to test ur own pr

**Comment by 1zun4** [comment]
The whole PR be like
```diff
- val thePlayer = mc.thePlayer ?: return
+ val player = mc.thePlayer ?: return
```

**Comment by Coccocoahelper** [comment]
> The whole PR be like
> 
> ```diff
> - val thePlayer = mc.thePlayer ?: return
> + val player = mc.thePlayer ?: return
> ```

That's literally the point, lol.

**Comment by EclipsesDev** [comment]
oop why delete it, i accidentally deleted legacy branch xd, thats why the rest of the pr closed

**Pull request closed without merging**
