### PR TITLE
Improve default KillAura values

### PR DESCRIPTION
**Pull request by gabrielvicenteYT**
Helps bypass multiple Anti-Cheats, no longer hits like once per second!

### CODE REVIEW

**Comment by gabrielvicenteYT** [comment]
@kawaiinekololis

**Comment by 1zun4secondary** [comment]
These are defaults values, they are not supposed to bypass anything, only few very simple anti-cheats. Everything else should be configured via config or by the user.

**Comment by gabrielvicenteYT** [comment]
> These are defaults values, they are not supposed to bypass anything, only few very simple anti-cheats. Everything else should be configured via config or by the user.

Atleast there should be a default config that BYPASSES...

**Comment by 1zun4secondary** [comment]
No there should not. It is a default config which can be used on very basic anti-cheats, it is not intended to annoy the user by poor configurations.

**Pull request closed without merging**
