### PR TITLE
Nametag HealthColor

### PR DESCRIPTION
**Pull request by FengXiaoSkidGod**
The warehouse was damaged by me, so I resubmitted a Pull request

### CODE REVIEW

**Comment by ccetl** [comment]
Just sharing my thoughts on this:
You could interpolate from green to red instead of using yellow/red directly when the health drops below a certain level. This would also make it look nicer, less abrupt, when the health is slowly dropping.

**Comment by FengXiaoSkidGod** [comment]
> Just sharing my thoughts on this: You could interpolate from green to red instead of using yellow/red directly when the health drops below a certain level. This would also make it look nicer, less abrupt, when the health is slowly dropping.

Perhaps this is feasible, but other data in NameTag (such as ping) are written in red to yellow to green, so I followed the writing style of other data

**Comment by ccetl** [comment]
> > Just sharing my thoughts on this: You could interpolate from green to red instead of using yellow/red directly when the health drops below a certain level. This would also make it look nicer, less abrupt, when the health is slowly dropping.
> 
> Perhaps this is feasible, but other data in NameTag (such as ping) are written in red to yellow to green, so I followed the writing style of other data

Ping won't change that much.

**Comment by 1zun4** [comment]
The font renderer can take any color value you want, it is not restricted to the standard minecraft color codes - therefore it should just calculate a fade between green and red like Health ESP does. I will add my changes to this PR in the upcoming days.

**Comment by 1zun4** [comment]
Ok, because the client font renderer currently does not support Minecraft text components I decided this will do it for now.

**Pull request merged**
