### PR TITLE
added crystalaura module

### PR DESCRIPTION
**Pull request by ghost**
Now detects obsidian, places end crystal and then attacks it.

### CODE REVIEW

**Comment by ghost** [comment]
what about bedrock?

**Comment by ghost** [comment]
> what about bedrock?

Does bedrock support end crystals?

**Comment by ghost** [comment]
yes

**Comment by ghost** [comment]
Done.

**Comment by ghost** [comment]
Now it works only when an enemy is close to you depending on what range you have set. I also increased the minimum value of the range because not only is it safe, but also prevents a weird bug which makes it not work if the value is set under 3.

**Comment by ghost** [comment]
Ok

**Comment by ghost** [comment]
There's one more thing I would add in order to make this thing actually worth using and that would be placing as near as possible at the enemy's position. Unfortunately I cannot code such a thing even though I'm currently trying to find a way how.

**Comment by ghost** [comment]
Does it also check for obstructions between the player and the crystal?

**Comment by ghost** [comment]
> Does it also check for obstructions between the player and the crystal?

What do you mean by that?

**Comment by ghost** [comment]
Like, it won't place a crystal near the enemy if there are blocks inbetween where it's trying to place and the enemy

**Comment by ghost** [comment]
> Like, it won't place a crystal near the enemy if there are blocks inbetween where it's trying to place and the enemy

Yes, it won't.

**Comment by ghost** [comment]
Ok, I might try this out later

**Comment by ghost** [comment]
Gotta note that from this comment that I made: 

> There's one more thing I would add in order to make this thing actually worth using and that would be placing as near as possible at the enemy's position. Unfortunately I cannot code such a thing even though I'm currently trying to find a way how.

It won't "perform" well if there are like tons of players + bedrock/obsidian blocks around, due to the reason stated above.

**Comment by ghost** [comment]
Will it just be laggy or what?

**Comment by ghost** [comment]
> Will it just be laggy or what?

Nope. It will simply not place as near as possible at the enemy's position in order to get the most damage. What will it do instead is find the closest bedrock/obsidian block to you and place it which sucks when you are in a pvp situation.

**Comment by ghost** [comment]
Yea, auto crystal logic seems super hard

**Comment by ghost** [comment]
> Error: Execution failed for task ':remapSourcesJar'.
> org/eclipse/core/runtime/IProgressMonitor has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

The reason it fails to build... bruh

**Comment by 1zun4secondary** [comment]
Please wait for https://github.com/CCBlueX/LiquidBounce/tree/nextgen_1.17 to be done.

**Comment by 1zun4secondary** [comment]
Please merge the new changes from the nextgen branch into your pull request to fix the building issue.
https://github.com/CCBlueX/LiquidBounce/runs/2885107056
https://github.com/CCBlueX/LiquidBounce/commit/5551db87d307dcefd8486b65dca47290c606ba85

**Pull request merged**
