### PR TITLE
Added AutoGapple module.

### PR DESCRIPTION
**Pull request by ghost**
* Supports FastUse module + its modes. (Obviously???)
* Took 6 hours to make due to a weird bug which made it not cancel eat + switch slots.
* Checks for health + absorption amount so it doesn't use more apples to reach the health value.
* Switches back to previous slot when there are no more golden apples.

### CODE REVIEW

**Comment by 1zun4secondary** [comment]
Please merge the new changes from the nextgen branch into your pull request to fix the building issue.
https://github.com/CCBlueX/LiquidBounce/runs/2885107056
https://github.com/CCBlueX/LiquidBounce/commit/5551db87d307dcefd8486b65dca47290c606ba85

**Comment by ENDER1355** [comment]
gj on doing it

im not gonna release my pvp land disabler because rerd is gonna fix it

**Review by 1zun4secondary — APPROVED** [review]
Works fine but could be better.

**Comment by ENDER1355** [comment]
Nice

**Pull request merged**
