### PR TITLE
Fake Autoblock mode is affected by blockrate

### PR DESCRIPTION
**Pull request by gabrielvicenteYT**
I made the Integer value show while in the fake autoblock mode, since it affects it anyways.

### CODE REVIEW

**Comment by CzechHek** [comment]
`!in setOf("Off")` -> `!= "Off"`

**Comment by gabrielvicenteYT** [comment]
Thanks!

**Comment by CzechHek** [comment]
unintentional?

I could include this in https://github.com/CCBlueX/LiquidBounce/pull/923 if you wanted.

**Comment by gabrielvicenteYT** [comment]
The fake autoblock mode should still be affected by blockrate like this, so yeah, include it in your pull request, it'll make it better.

**Pull request closed without merging**
