### PR TITLE
iOS? woah

### PR DESCRIPTION
**Pull request by CzechHek**
iOS -> macOS

### CODE REVIEW

**Comment by CzechHek** [comment]
nvm someone already made a pull request, how are people this active?

**Comment by ghost** [comment]
Lol

**Comment by ENDER1355** [comment]
Liquidbounce on iOS :thinking:

**Comment by ghost** [comment]
> Liquidbounce on iOS 🤔

Pojav launcher 😆

**Comment by ENDER1355** [comment]
> > Liquidbounce on iOS 🤔
> 
> Pojav launcher 😆

Will LB's Render engine work though?

**Comment by ghost** [comment]
Definitely not, it doesn't even work on macos or Linux rn lol

**Comment by ghost** [comment]
There is a pojav for iOS, the phone needs to be jailbroken tho

**Pull request closed without merging**
