### PR TITLE
more intave bypasses

### PR DESCRIPTION
**Pull request by larryngton**
- [x] made the intave consumable noslow only send c07 when needed
- [x] intave sword noslow
- [x] intave noweb (from legacy)
- [ ] intave speed by (@liquidsquid1)

### CODE REVIEW

**Comment by larryngton** [comment]
nvm, the noslow works fine as it is

**Comment by liquidsquid1** [comment]
@larryngton I will be away from my pc for a while, can this be merged without the speed?

**Comment by larryngton** [comment]
> @larryngton I will be away from my pc for a while, can this be merged without the speed?

alright liquidskid :3

**Comment by larryngton** [comment]
how the fuck do I make this ready for review from my phone

**Comment by liquidsquid1** [comment]
> > @larryngton I will be away from my pc for a while, can this be merged without the speed?
> 
> alright liquidskid :3

🤫

**Comment by 1zun4** [comment]
all bypasses confirmed to be working on gommehd.net

**Pull request merged**
