### PR TITLE
Add tag

### PR DESCRIPTION
**Pull request by RtxOP**

### CODE REVIEW

**Comment by CzechHek** [comment]
For God's sake, get that .contains() out of here.

**Comment by RtxOP** [comment]
why

**Comment by CzechHek** [comment]
Wait isn't that yellow underline bothering you saying that you should use packet.soundName as well?

packet.soundName == "name"

**Comment by RtxOP** [comment]
I use vs code

**Comment by CzechHek** [comment]
Improved it locally:

```kotlin
private val nonDelayedSoundSubstrings = arrayOf("game.player.hurt", "game.player.die")

is S29PacketSoundEffect -> if (nonDelayedSoundSubstrings in packet.soundName) return
```

This can be closed or whatever, I will push my version soon.

**Pull request closed without merging**
