### PR TITLE
Added ProjectilePuncher module.

### PR DESCRIPTION
**Pull request by ghost**
I would've made it tons better by somehow checking if the Fireball was thrown from a teammate but for some reason it always returned null to both the `entity.owner` + `entity.ownerUuid`. At least it will shoot back everything coming on the player's way.

### CODE REVIEW

**Comment by ghost** [comment]
Renamed the module to ProjectilePuncher and included Shulker bullet.

**Comment by ghost** [comment]
Fixed a bug that made the player swing forever. (The shit way)

**Comment by 1zun4secondary** [comment]
There should be a cps option to make sure you doesn't make too many clicks.

**Comment by ghost** [comment]
> There should be a cps option to make sure you doesn't make too many clicks.

That's fixed by clearing the target tracker list.

**Comment by 1zun4secondary** [comment]
> > There should be a cps option to make sure you doesn't make too many clicks.
> 
> That's fixed by clearing the target tracker list.

Yes, but what if there are many "projectiles" (example: anticheat check)

**Comment by ghost** [comment]
It loops around, checks for the closest fireball, one hit and it's gone. Many of them? It checks for the closest one, hits and clears the the entity on the target tracker and focuses to the next one. In game it should be really fast? Unless this isn't what you are talking about.

**Comment by 1zun4secondary** [comment]
Example: your connection lags
If you hit the closest fireball it will not go away and next tick will be selected AGAIN
and every tick you will attack it. 20 ticks, 20 clicks in one second. For the most anticheats enough to ban you.

**Comment by ghost** [comment]
Oh, makes sense now...

**Pull request merged**
