### PR TITLE
Improve mod name consistency

### PR DESCRIPTION
**Pull request by gabrielvicenteYT**
I'm just doing this for fun...

### CODE REVIEW

**Comment by CzechHek** [comment]
But why?

What consistency is in Fireball x BackTrack?

Since backtrack can be used as a verb, shouldn't it remain "Backtrack". 

Besides, do you know what refactoring is?

**Comment by opZywl** [comment]
'-'

**Comment by gabrielvicenteYT** [comment]
> But why?
> 
> What consistency is in Fireball x BackTrack?
> 
> Since backtrack can be used as a verb, shouldn't it remain "Backtrack".
> 
> Besides, do you know what refactoring is?

"Backtrack" just looks odd to me, I guess I'm too used to Sigma 5.0's design.

**Comment by 1zun4secondary** [comment]
It would make sense to use an IDE when you start refactoring.

**Comment by 1zun4secondary** [comment]
I feel like the names should stay like this. We don't go by consistency, but what looks better

**Pull request closed without merging**
