### PR TITLE
LEGACY: Scaffold Small Improvement

### PR DESCRIPTION
**Pull request by EclipsesDev**
Now it will display the current block name that are being use in scaffold

### CODE REVIEW

**Comment by Coccocoahelper** [comment]
Why?!? This is NOT an LB fork, this is the real deal!

**Comment by EclipsesDev** [comment]
> Why?!? This is NOT an LB fork, this is the real deal!

are u trying to tell me, that improving is now not LiquidBounce thing?

**Comment by EclipsesDev** [comment]
plus what does this have to do with lb fork??

**Comment by Coccocoahelper** [comment]
> plus what does this have to do with lb fork??

The module tags can change how it looks...

**Comment by EclipsesDev** [comment]
> > plus what does this have to do with lb fork??
> 
> The module tags can change how it looks...

Well it's called small improvement, and i see there are nothing wrong with it?

**Comment by 1zun4** [comment]
In this case I decline, because showing the block name gives no benefit, also no blocks instead of Blocks: 0 changes nothing as well.

**Comment by EclipsesDev** [comment]
> In this case I decline, because showing the block name gives no benefit, also no blocks instead of Blocks: 0 changes nothing as well.

hmm true ig, might do block display.. if thats any better?

**Pull request closed without merging**
