### PR TITLE
added a module in modulemanager because superblauberee forgot to

### PR DESCRIPTION
**Pull request by ghost**
+ did a bit of a cleanup just for the modules so as to be fresh thats all

### CODE REVIEW

**Comment by ghost** [comment]
How do u have multiple prs open at the same time?

**Comment by ghost** [comment]
Wait nvm, I see now

**Comment by ghost** [comment]
huh

**Comment by ghost** [comment]
Forget about it

**Comment by ghost** [comment]
yeah.. whatever

**Comment by 1zun4secondary** [comment]
Wait for https://github.com/CCBlueX/LiquidBounce/tree/nextgen_1.17. I'll merge it as soon it is done.

**Pull request closed without merging**
