### PR TITLE
feat(legacy): oldgrim noweb & nofluid

### PR DESCRIPTION
**Pull request by Husky272**

### CODE REVIEW

**Comment by SuicidalEeper** [comment]
Have you tested this on latest github grim?

**Comment by Husky272** [comment]
Test in loyisa,I dont know if their Grim is latest

**Comment by SuicidalEeper** [comment]
Test on anticheat-test think that's more updated and preferably latest git version on a local server but guess this will still bypass servers that haven't updated it either way but idk how many of those there are

**Comment by Husky272** [comment]
Patched yesterday...But an old bypass for this reborn,wait for tomorrow

**Comment by EclipsesDev** [comment]
let me know if this is ready

**Comment by Husky272** [comment]
ready

**Pull request merged**
