### PR TITLE
Fixed Equipprogress in Animations and removed Useless code from Animations, added Old Animation (1.7) and Fixed NoBob 

### PR DESCRIPTION
**Pull request by lynent**
wtf???

### CODE REVIEW

**Comment by derech1e** [comment]
I love those PRs that basically don't explain anything about the requested change.

**Comment by lynent** [comment]
derech1e so you want me to write a whole explanation of why small code has been changed? ok! noted.

**Comment by derech1e** [comment]
> derech1e so you want me to write a whole explanation of why small code has been changed? ok! noted.

Yeah, I mean "wtf???" is not very meaningful.

**Comment by lynent** [comment]
> > derech1e so you want me to write a whole explanation of why small code has been changed? ok! noted.
> 
> Yeah, I mean "wtf???" is not very meaningful.

That's true! my Apologies.

**Comment by CzechHek** [comment]
> > > derech1e so you want me to write a whole explanation of why small code has been changed? ok! noted.
> > 
> > 
> > Yeah, I mean "wtf???" is not very meaningful.
> 
> That's true! my Apologies.

This is exactly like a ChatGPT response, instead of only apologizing you should just edit the comment on what changes you've made.

**Comment by lynent** [comment]
> > > > derech1e so you want me to write a whole explanation of why small code has been changed? ok! noted.
> > > 
> > > 
> > > Yeah, I mean "wtf???" is not very meaningful.
> > 
> > 
> > That's true! my Apologies.
> 
> This is exactly like a ChatGPT response, instead of only apologizing you should just edit the comment on what changes you've made.

Hello CzechHek! I'm sorry that it's my first time really using pull requests with the help of the online code editor from github! I did not know that you could edit PRS and I've now corrected my mistake! I'm sorry if I insulted you in any way shape or form and hopefully you can continue your life without any worries! Thank you for giving me Advices.

Best Regards.

**Pull request merged**
