### PR TITLE
[LEGACY] Add Disabler module

### PR DESCRIPTION
**Pull request by gabrielvicenteYT**

### CODE REVIEW

**Comment by be4dev** [comment]
well, I can only say: use IDEA https://www.youtube.com/watch?v=diQyT3-BahU (just to make sure you understand how easy to use it (The biggest time loss is me, forgetting packet name), made pr from it

**Comment by gabrielvicenteYT** [comment]
> 

I literally do the exact same w/o IDEA. It might be easier for you all, but with IDEA or any other IDE except github.dev, I have only had issues.

**Comment by 1zun4** [comment]
> > 
> 
> I literally do the exact same w/o IDEA. It might be easier for you all, but with IDEA or any other IDE except github.dev, I have only had issues.

grafik

oh yes monkey brain who needs IDE anyway haha i code with pen and paper 🐒

**Comment by gabrielvicenteYT** [comment]
> > > 
> > 
> > 
> > I literally do the exact same w/o IDEA. It might be easier for you all, but with IDEA or any other IDE except github.dev, I have only had issues.
> 
> grafik
> 
> oh yes monkey brain who needs IDE anyway haha i code with pen and paper 🐒

I'm an AI, I learn by errors.

**Comment by gabrielvicenteYT** [comment]
> > > 
> > 
> > 
> > I literally do the exact same w/o IDEA. It might be easier for you all, but with IDEA or any other IDE except github.dev, I have only had issues.
> 
> grafik
> 
> oh yes monkey brain who needs IDE anyway haha i code with pen and paper 🐒

If you really think IDEs are that good, can you even teach me *how* to use an IDE properly? I don't even know WHICH EXTENSIONS to install…

**Comment by CzechHek** [comment]
> I don't even know WHICH EXTENSIONS to install…

None

**Comment by be4dev** [comment]
> > > > 
> > > 
> > > 
> > > I literally do the exact same w/o IDEA. It might be easier for you all, but with IDEA or any other IDE except github.dev, I have only had issues.
> > 
> > 
> > grafik
> > oh yes monkey brain who needs IDE anyway haha i code with pen and paper monkey
> 
> If you really think IDEs are that good, can you even teach me _how_ to use an IDE properly? I don't even know WHICH EXTENSIONS to install…

kotlin only, btw show us how you work in IDEA (tip: if something is marked with red, that it will mostly fail build) (can send me in discord if you dislike guilded (be4dev))

**Comment by be4dev** [comment]
> > > > > 
> > > > 
> > > > 
> > > > I literally do the exact same w/o IDEA. It might be easier for you all, but with IDEA or any other IDE except github.dev, I have only had issues.
> > > 
> > > 
> > > grafik
> > > oh yes monkey brain who needs IDE anyway haha i code with pen and paper monkey
> > 
> > 
> > If you really think IDEs are that good, can you even teach me _how_ to use an IDE properly? I don't even know WHICH EXTENSIONS to install…
> 
> kotlin only, btw show us how you work in IDEA (tip: if something is marked with red, that it will mostly fail build) (can send me in discord if you dislike guilded (be4dev))

another tip: you can use "show context menu", quite often is helps (first or second suggested solution)

**Comment by be4dev** [comment]
> > > 
> > 
> > 
> > I literally do the exact same w/o IDEA. It might be easier for you all, but with IDEA or any other IDE except github.dev, I have only had issues.
> 
> grafik
> 
> oh yes monkey brain who needs IDE anyway haha i code with pen and paper monkey

don't forget to turn off syntax highlighting irl, it makes you 10x times cooler :axodance:

**Comment by gabrielvicenteYT** [comment]
> > > > 
> > > 
> > > 
> > > I literally do the exact same w/o IDEA. It might be easier for you all, but with IDEA or any other IDE except github.dev, I have only had issues.
> > 
> > 
> > grafik
> > oh yes monkey brain who needs IDE anyway haha i code with pen and paper monkey
> 
> don't forget to turn off syntax highlighting irl, it makes you 10x times cooler :axodance:

It seems like it ain't that bad, but github.dev should add the auto-imports thing

**Comment by RtxOP** [comment]
The current implementation of the disabler module restricts players to selecting only one mode at a time. However, as the functionality to cancel various packets using different modes may be added in the future, the current approach of allowing only one mode to be active at once may not be practical or optimal.

**Comment by gabrielvicenteYT** [comment]
> The current implementation of the disabler module restricts players to selecting only one mode at a time. However, as the functionality to cancel various packets using different modes may be added in the future, the current approach of allowing only one mode to be active at once may not be practical or optimal.

Yeah, but people would falsely call LiquidBounce out for being skidded.

**Comment by RtxOP** [comment]
Skid from where?

> > The current implementation of the disabler module restricts players to selecting only one mode at a time. However, as the functionality to cancel various packets using different modes may be added in the future, the current approach of allowing only one mode to be active at once may not be practical or optimal.
> 
> Yeah, but people would falsely call LiquidBounce out for being skidded.

Skid from where?

**Comment by 1zun4** [comment]
Any progress on this? Otherwise I will close this in the next few days.

**Comment by gabrielvicenteYT** [comment]
> Any progress on this? Otherwise I will close this in the next few days.

Yeah, I'll close it, I'll have to re-do it, either way.

**Pull request closed without merging**
