### PR TITLE
feat(CustomAmbience): fog and precipitation

### LINKED ISSUE #4063: [FEATURE] Addition to CustomAmbience
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Allow for customization of fog color, fog density and fog start point. It can be a pretty looking effect if you configure it right and I'd say it fits in well with the "CustomAmbience" module in general.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ccetl**
closes: #4063

### CODE REVIEW

**Comment by DataM0del** [comment]
I might need to finally implement the fog mixin for this...

**Comment by ccetl** [comment]
> I might need to finally implement the fog mixin for this...

? You don't need to implement anything.

**Comment by DataM0del** [comment]
> > I might need to finally implement the fog mixin for this...
> 
> ? You don't need to implement anything.

I do need to implement the fog mixin so that the new fog setting in CustomAmbience works

**Comment by ccetl** [comment]
> > > I might need to finally implement the fog mixin for this...
> > 
> > 
> > ? You don't need to implement anything.
> 
> I do need to implement the fog mixin so that the new fog setting in CustomAmbience works

It already works.

**Comment by DataM0del** [comment]
Okay

**Pull request merged**
