### PR TITLE
Converted @ModuleInfo to constructor

### PR DESCRIPTION
**Pull request by CzechHek**
Rewritten all `@ModuleInfo` annotations to constructors.

Removed `ModuleInfo` file.

**Refactored** `module.array` to `module.inArray`
**Added** `module.defaultInArray`
* used by `HideCommand` to reset visibility

Made `ClickGui.inArray` default to false, like HUD.

Fixed description of Backtrack module: "Allows you to hit players by attacking their previous cached positions."

### CODE REVIEW

**Comment by CzechHek** [comment]
Tested, also with scripts, seems to work exactly the same as with `@ModuleInfo`.

**Comment by opZywl** [comment]
Strange

**Comment by CzechHek** [comment]
> Strange

image

**Comment by CzechHek** [comment]
Wait, why was default keybind previously Keyboard.CHAR_NONE and how does it differ from KEY_NONE.

image

**Pull request merged**
