### PR TITLE
Scaffold improvements

### PR DESCRIPTION
**Pull request by be4dev**
Lots of changes in scaffold

1. Added timer option to scaffold
2. Added zitter mode 

* smooth (now works properly, unlike legacy one)
* teleport

3. Added eagle options

* blocks to eagle
* eagle edge distance

4. Added rotation modes:

* Center
* Random
* Stabilized
* CloseRotation

5. Added Advanced rotation settings

* xRange
* yRange
* zRange
* step

6. Removed push velocity cause it has nothing in
7. Reformated translations, added missing entries
8. Fixed (hope) lb not launching without internet connection
9. Added keepRotationTicks
10. Cleaned up code (a bit)

### CODE REVIEW

**Comment by 1zun4** [comment]
Looks very good btw

**Comment by be4dev** [comment]
> Looks very good btw

Thanks, was hard to do

**Comment by 1zun4** [comment]
I will merge as soon I got the time to fix the merge conflicts. :)

**Comment by be4dev** [comment]
> I will merge as soon I got the time to fix the merge conflicts. :)

done, guess I have fixed it

**Comment by 1zun4** [comment]
ok great

**Pull request merged**
