### PR TITLE
fix(legacy): fix VerusGlide flags

### PR DESCRIPTION
**Pull request by Coccocoahelper**
This is (probably) not going to compile…

### CODE REVIEW

**Comment by EclipsesDev** [comment]
surprise it builds

**Comment by Coccocoahelper** [comment]
> surprise it builds

It is a surprise, actually.

**Comment by EclipsesDev** [comment]
why don't you use `isMoving`?

**Comment by Coccocoahelper** [comment]
> why don't you use `isMoving`?

Because the fix is for diagonal movement.

**Comment by EclipsesDev** [comment]
could u not use `player.movementInput.moveStrafe != 0f` ?

**Comment by Coccocoahelper** [comment]
> could u not use `player.movementInput.moveStrafe != 0f` ?

That's actually a good idea! I'll be sure to do that.

**Comment by Coccocoahelper** [comment]
Done.

**Pull request merged**
