### PR TITLE
new grim lowhop speed

### PR DESCRIPTION
**Pull request by TheColorfulGabibbo**
i made this because the old grim collide is patched
it works only on 1.8.x protocol

- [x] work on a lowhop
- [ ] find out a method to make the speed more fast (optional)

### CODE REVIEW

**Comment by ghost** [comment]
Do you even notice the difference with the `99E-5` offset?

**Comment by TheColorfulGabibbo** [comment]
> Do you even notice the difference with the `99E-5` offset?

yes? 0.4101

**Comment by TheColorfulGabibbo** [comment]
wait now its flagging
how

**Comment by TheColorfulGabibbo** [comment]
no bro i calculated it wrong

**Comment by SuicidalEeper** [comment]
Is this even 1% faster than vanilla?

**Comment by TheColorfulGabibbo** [comment]
> Is this even 1% faster than vanilla?

yes? normal jump motion is 0.42 with this it would become 0.41901 wich is almost 0.001 less

**Comment by TheColorfulGabibbo** [comment]
idk if its 1% or a minor value but it should be faster than vanilla

**Comment by TheColorfulGabibbo** [comment]
Cattura

**Comment by TheColorfulGabibbo** [comment]
the vulcan speed is like 7.5%

**Pull request closed without merging**
