### PR TITLE
Fixed KillAura not aiming and blocking when HurtTime < 10 from time to time

### LINKED ISSUE #1033: [BUG] [LEGACY] KillAura HurtTime issue
### LiquidBounce Build/Version

it affects b77 version and the latest build too

### Operating System

Windows 8.1

### Minecraft Version

1.8.9

### Describe the bug

If entity has hurttime greater than HurtTimeValue then this entity won't be added to targets; In the result, KillAura won't face and use autoblock; Video: https://youtu.be/JpS5n-uR-wk

Expected behavior:
If entity has hurttime greater than HurtTimeValue then KillAura shouldn't hit but still face and use autoblock;
Video: https://youtu.be/zjzIOZ5i2po (I have used HurtTimeValue = 10 and clickOnly option to reflect an expected behavior)

### Steps to reproduce

- Set KillAura hurtTimeValue to 0 (it can be from 0 to 9 but it's better to set it to 0 in order to see the bug easier)

### Client Log

```shell
none
```

### Screenshots

none

### PR DESCRIPTION
**Pull request by FDPUser443**
It's supposed to close #1033
See also #1034

Video: https://streamable.com/ua5yit

There is a question. Should it do fake swings when target's hurttime is greater than KillAura HurtTime value or just wait like in the video?

### CODE REVIEW

**Comment by ghost** [comment]
I think it's okay to keep doing fake swings.

**Comment by ghost** [comment]
Anything else you want to update? This looks ready to me.

**Comment by FDPUser443** [comment]
> I think it's okay to keep doing fake swings.

I will update it according to this. It will keep doing fake swings if FakeSwing option is enabled;

**Comment by FDPUser443** [comment]
Here is how it works: https://streamable.com/4h2j6i

**Pull request merged**
