### PR TITLE
AAC5 Velocity

### PR DESCRIPTION
**Pull request by Husky272**

### CODE REVIEW

**Comment by EclipsesDev** [comment]
Is this ported from script or clients?

**Comment by Husky272** [comment]
> Is this ported from script or clients?

from client

**Comment by EclipsesDev** [comment]
makesure u fix the conflicts first

**Comment by Husky272** [comment]
https://github.com/CCBlueX/LiquidBounce/commit/5760d654c6af22c29d5d96d5873da7b4d724e64c
also bypass

**Pull request closed without merging**
