### PR TITLE
ncp speed

### PR DESCRIPTION
**Pull request by larryngton2**
features:
- boost
- airstrafe option
- pulldown
           - ontick (what tick to pulldown on)
           - onhurt (-0.1 y motion when taking damage while ascending, doesnt work with damageboost that well)
- lowhop (0.4 jump height, only works on normal ncp)
- timerboost
- damageboost
- speedpot boost

not associated with #3584

### CODE REVIEW

**Comment by larryngton2** [comment]
im larryngton btw, this is my alt account

**Comment by larryngton2** [comment]
preview: https://streamable.com/jkkbec

**Comment by larryngton2** [comment]
ill do the speedpot boost later

**Comment by larryngton2** [comment]
the lowhop option only works correctly with 0.0 velocity btw

**Comment by larryngton2** [comment]
still needs improvements

**Comment by liquidsquid1** [comment]
image
I think this might just need a little more work

**Comment by larryngton2** [comment]
> image I think this might just need a little more work

it flagged a bit for me at the start but then it worked fine, lemme try reducing the airstrafe strength by a bit

**Comment by larryngton2** [comment]
dont tell alan about 0.0071832 and -0.1523351824467155

**Comment by larryngton2** [comment]
wait fuck i gotta fix one thing

**Comment by larryngton2** [comment]
its good now

**Comment by modelpackagespaceingrootjujummail** [comment]
> im larryngton btw, this is my alt account

https://github.com/user-attachments/assets/2caf4ed8-8c29-4caf-88a9-2e0c32c47248


Fake

**Comment by jesterwoohoo** [comment]
https://tenor.com/view/blueaca-blue-archive-seikanashi-seika-sei-ichijou-gif-10186447822204528512

**Comment by larryngton2** [comment]
> > im larryngton btw, this is my alt account
> 
> blueaca-blue-archive.mp4
> 
> Fake

no way izuna gaem

**Comment by 1zun4** [comment]
For what NoCheatPlus is this made? It flags after a few jumps.

**Comment by larryngton2** [comment]
> For what NoCheatPlus is this made? It flags after a few jumps.

it works flawlessly on old / normal ncp (old ncp on loyisa, normal ncp on actest), but you have to toggle off some options on updated ncp (i even tested it on a real ncp server and it worked fine)

(edit) never fucking mind it flags for morepackets, imma fix it rn

**Pull request merged**
