### PR TITLE
Zoot: Removed potion server-side.

### PR DESCRIPTION
**Pull request by ghost**
Server-sided too.

### CODE REVIEW

**Comment by 1zun4secondary** [comment]
RemoveEntityStatusEffectS2CPacket? This is a Server to Client Packet. Do you even know how the f*cking minecraft networking works?

**Comment by ghost** [comment]
> RemoveEntityStatusEffectS2CPacket? This is a Server to Client Packet. Do you even know how the f*cking minecraft networking works?

mixins it is then, no idea how mixins work.

**Comment by 1zun4secondary** [comment]
This has nothing to do with Mixins? wtf

**Comment by ghost** [comment]
> This has nothing to do with Mixins? wtf

Well there isn't any client-side packet which can do that, is there?

**Comment by 1zun4secondary** [comment]
You can't remove permanent potion effects.

**Comment by ghost** [comment]
Okay.

**Pull request closed without merging**
