### PR TITLE
LEGACY: Improved SameY

### PR DESCRIPTION
**Pull request by MaeTobiGeri**
Added an option to the scaffold module. Which ignores samey when the user is actively pressing space bar. Also fixed Expand Scaffold not working properly in combination with SameY

### CODE REVIEW

**Comment by MaeTobiGeri** [comment]
Ready for Review

**Comment by ghost** [comment]
Can you tell me what this addition does during gameplay?

**Comment by MaeTobiGeri** [comment]
> Can you tell me what this addition does during gameplay?

So first of all it allows the player to manually jump when using sameY (so it places blocks beneath you when manually jumping). But not when telly or your speed automatically jumps. Also it fixed expand scaffold only building one block forwards when using sameY. So you can now use expand scaffold and a bhop speed in combination.

**Comment by MaeTobiGeri** [comment]
It now kinda works like the current one in Next Gen.

**Comment by ghost** [comment]
Try making the code less repetitive. 

EDIT: Instead of adding the same check two times, just make a getter variable named `shouldJumpOnUserInput` (or whatever you like) that is assigned to this:

 (!jumpOnUserInput || !mc.gameSettings.keyBindJump.pressed)

So you can use it on the `shouldKeepLaunchPosition` like this:

```
  private val shouldKeepLaunchPosition
        get() = sameY && shouldJumpOnUserInput && scaffoldMode != "GodBridge"
```

And replace the other line (1107) with this:

```
 if (scaffoldMode == "GodBridge" && (autoJump || jumpAutomatically) || shouldJumpOnUserInput)
     return
```

**Comment by MaeTobiGeri** [comment]
> Try making the code less repetitive. 
> 
> EDIT: Instead of adding the same check two times, just make a getter variable named `shouldJumpOnUserInput` (or whatever you like) that is assigned to this:
> 
>  (!jumpOnUserInput || !mc.gameSettings.keyBindJump.pressed)
> 
> So you can use it on the `shouldKeepLaunchPosition` like this:
> 
> ```
>   private val shouldKeepLaunchPosition
>         get() = sameY && shouldJumpOnUserInput && scaffoldMode != "GodBridge"
> ```
> 
> And replace the other line (1107) with this:
> 
> ```
>  if (scaffoldMode == "GodBridge" && (autoJump || jumpAutomatically) || shouldJumpOnUserInput)
>      return
> ```
> 
> 

Yeah could do that as well but seems like you can just reuse ShouldKeepLaunchPosition at least that didn't produce an issue for me. But I can change it to what you suggested aswell ig.

**Comment by ghost** [comment]
Yes because the last one checks if the GodBridge mode is chosen, but the `shouldKeepLaunchPosition` variable checks for the opposite, not that much sense.

**Pull request merged**
