### PR TITLE
Better Strafe (Recode yorik100's StrafeRemade script to Kotlin)

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by kawaiinekololi** [comment]
bloody mess

**Comment by kawaiinekololi** [comment]
Please try to learn Kotlin and always test your code before creating a pull request.

**Comment by Teals53** [comment]
completely broken xD

**Comment by Mrmaniann** [comment]
It is bad.

**Comment by yorik100** [comment]
> It is bad.

NO

**Pull request merged**
