### PR TITLE
Added CrystalAura module.

### PR DESCRIPTION
**Pull request by ghost**
Completes yet another [requirement.](https://github.com/CCBlueX/LiquidBounce/issues/364)

### CODE REVIEW

**Review by superblaubeere27 — APPROVED** [review]
The code is fine, I am not sure if marco will accept this module addition

**Comment by ghost** [comment]
It's a part of the requirement topic, so I believe I am sure he will accept it, unless he wants to do it with another method.

**Comment by 1zun4secondary** [comment]
This is not what CrystalAura should do.

**Comment by ghost** [comment]
> This is not what CrystalAura should do.

What should it do instead?

**Comment by superblaubeere27** [comment]
Place and Destroy

**Comment by ghost** [comment]
Then it should be a part of the F word module, just a guess.

**Comment by superblaubeere27** [comment]
> 
> 
> Then it should be a part of the F word module, just a guess.

no

**Comment by ghost** [comment]
did it only break crystals or What?

**Comment by superblaubeere27** [comment]
> 
> 
> did it only break crystals or What?

It places and breaks them

**Comment by ghost** [comment]
Then I don't get how it isn't what crystal aura is meant to do, is it something else?

**Comment by superblaubeere27** [comment]
> 
> 
> Then I don't get how it isn't what crystal aura is meant to do, is it something else?

This code here does not place the block and is a bit too low quality for this repo

**Comment by ghost** [comment]
Ah ok

**Pull request closed without merging**
