### PR TITLE
feat: motion tower "slow" option

### PR DESCRIPTION
**Pull request by liquidsquid1**
adds a slow option that might help with some anticheats (ncp/bmc included)

### CODE REVIEW

**Comment by larryngton** [comment]
skidded from nightx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by levzzz5154** [comment]
skidded from nightx.

**Comment by larryngton** [comment]
liquidskid

**Comment by localpthebest** [comment]
SKIB!!

**Comment by larryngton** [comment]
> SKIB!!

idi

**Comment by ghost** [comment]
this is skidded from nightx old mmc tower velocity

**Comment by levzzz5154** [comment]
image

**Comment by localpthebest** [comment]
liquidskid moment

**Comment by larryngton** [comment]
you skidded from augustususususstyus

**Pull request merged**
