### PR TITLE
Intave speed

### PR DESCRIPTION
**Pull request by larryngton**
added a groundstrafe speed for intave

### CODE REVIEW

**Comment by larryngton** [comment]
next pr ill try to fix my intellij

**Comment by larryngton** [comment]
image

**Comment by 1zun4** [comment]
slower than vanilla sprint-jumping

**Comment by larryngton** [comment]
> slower than vanilla sprint-jumping

try setting the ground and air timer to 1

**Review by larryngton — COMMENTED** [review]
.

**Comment by larryngton** [comment]
ok let's not try to code through my phone

**Pull request closed without merging**
