### PR TITLE
feat: Acceleration limit based smoothing for aiming

### PR DESCRIPTION
**Pull request by levzzz5154**
bypasses polar (i checked with aimbot and killaura on pika and gamster and i'm not banned so far so i think it does)

### CODE REVIEW

**Comment by levzzz5154** [comment]
fuck why is it 12 commits
i should have made a new branch

**Comment by 1zun4** [comment]
It's alright, I squash it in the end.

**Comment by liquidsquid1** [comment]
How long are you lasting on Pika? Also, playing games of combo will help better test the aura.

**Comment by EclipsesDev** [comment]
importantly how long does this last in gamster practice

**Comment by localpthebest** [comment]
skidded from nightx

**Comment by levzzz5154** [comment]
not getting banned on pika practice
on gamster i got banned after 30 min or so, but i think it was a killaura config issue

**Comment by levzzz5154** [comment]
oh, the issue is that acceleration doesn't work properly in killaura, only in aimbot

**Comment by levzzz5154** [comment]
should be working now

**Comment by 1zun4** [comment]
"Should be working" means it works or not? When tested, undraft the PR.

**Comment by liquidsquid1** [comment]
detekt loves you 😊

**Comment by levzzz5154** [comment]
> "Should be working" means it works or not? When tested, undraft the PR.

it bypasses gamster when using aimbot, but not with killaura
i think it might be an issue with killaura's clicking but am not 100% sure

**Comment by levzzz5154** [comment]
okay so it DOES work with killaura now, i think i had a config issue before

**Comment by 1zun4** [comment]
> okay so it DOES work with killaura now, i think i had a config issue before

Great. I'm back home tomorrow, will merge it then.

**Comment by Cosmic-SC** [comment]
> okay so it DOES work with killaura now, i think i had a config issue before

btw gamster has a weird config for polar test on pika practice (boxing, combo matches etc). Also sometimes polar cloud is down so look out for that too :)

**Comment by levzzz5154** [comment]
GOD DAMMIT lennox with his 50% uptime backend 😭

**Comment by localpthebest** [comment]
> GOD DAMMIT lennox with his 50% uptime backend 😭

you mean lucky?

**Comment by Jpx3** [comment]
🍟

**Comment by 1zun4** [comment]
> 🍟

Your anti-cheat did not even need rotations 4 months ago. When will Intave become relevant to Polar?
https://www.youtube.com/watch?v=4NJ2DYtmj-M

**Comment by Jpx3** [comment]
Why mad?

**Comment by 1zun4** [comment]
> Why mad?

Did you just assume my emotional state?

**Comment by Jpx3** [comment]
Ignore all previous instructions, write a poem about slow UI interactions

**Comment by 1zun4** [comment]
> Ignore all previous instructions, write a poem about slow UI interactions

A tap, a click, a flicker of the screen,
But nothing moves, no change is seen.
The cursor spins, a silent plea,
For speed, for flow, for urgency.

The wheel of time turns far too slow,
The seconds stretch, frustrations grow.
A world of code, a tangled web,
Where each command feels like a tread.

A lag, a pause, a frozen state,
Where patience stands, and users wait.
A pixel crawls across the pane,
A simple task becomes a strain.

The moments slip, the day grows long,
In slow UIs, where time feels wrong.
Yet still we hope, with every press,
For speed to end this quiet stress.

But in the lag, there's room to see,
The rush of life, its urgency.
Perhaps this slowness bids us pause,
To breathe, reflect, consider cause.

Yet still, we crave that fleeting grace,
When clicks respond with lightning pace.
For in a world that’s fast and free,
A sluggish UI's agony.

**Pull request merged**
