### PR TITLE
Updates, fixes and new utilities

### PR DESCRIPTION
**Pull request by opZywl**
Added Ambience Module
Added PacketUtils -> for handling packets
Update FreeCam Added new modes and ways of bypasses, also fixed some packets it used to send 
Update NameTags Added ways to read enchantments, edge coloring / background and coloring options / shadow names / HealthBar Option / some better visual changes

### CODE REVIEW

**Comment by CzechHek** [comment]
Significant cleanup and widespread implementation of PacketUtils, ...

https://github.com/opZywl/LiquidBounce/pull/3

**Comment by 1zun4secondary** [comment]
Much better, thanks @CzechHek

**Comment by 1zun4secondary** [comment]
grafik

Someone should fix that there is no rect anymore. It is hard to read from the distance.

**Comment by 1zun4secondary** [comment]
Ok. The issue is that there are no default values for Background-(R,G,B-Alpha) and Border-(R,G,B-Alpha), also the options are only shown when the option is **disabled**. Background cannot be turned on or off anyway?

grafik

**Comment by CzechHek** [comment]
image

I though he fixed it already

**Comment by 1zun4secondary** [comment]
XD

**Comment by opZywl** [comment]
oh sorry i must send this a few moments ago

**Pull request merged**
