### PR TITLE
1.17 grim fastuse

### PR DESCRIPTION
**Pull request by aftercares0**
requires a fixed viaversion tho (i used https://github.com/MinusMC/ViaVersionPlugin)

### CODE REVIEW

**Comment by EclipsesDev** [comment]
Hmm interesting, I'll look onto this, currently we haven't fix the viaversion yet- tho I maybe could add the fixed viaversion

**Comment by EclipsesDev** [comment]
> requires a fixed viaversion tho (i used https://github.com/MinusMC/ViaVersionPlugin)

Also can u explain how to exactly use the fixed viaversion?

**Comment by 1zun4** [comment]
This exists in Nextgen, but instead of adding it as mode, we simply made it a selector which type of packet you want to use. But about the ViaVersionPlugin, this could be delivered via the launcher, since we do not bundle ViaForge with the client, but I am not really willing to rely on someone else than @FlorianMichael to keep it up-to-date.

**Comment by EclipsesDev** [comment]
> This exists in Nextgen, but instead of adding it as mode, we simply made it a selector which type of packet you want to use. But about the ViaVersionPlugin, this could be delivered via the launcher, since we do not bundle ViaForge with the client, but I am not really willing to rely on someone else than @FlorianMichael to keep it up-to-date.

so ig the viaversionplugin is used as a mod sorta?

**Comment by aftercares0** [comment]
> > requires a fixed viaversion tho (i used https://github.com/MinusMC/ViaVersionPlugin)
> 
> Also can u explain how to exactly use the fixed viaversion?

its basically a mod

**Comment by EclipsesDev** [comment]
> > > requires a fixed viaversion tho (i used https://github.com/MinusMC/ViaVersionPlugin)
> > 
> > 
> > Also can u explain how to exactly use the fixed viaversion?
> 
> its basically a mod

Yeah i tried to put it on mods folder, but it crash, maybe i did smth wrong.. I'll retry

**Comment by 1zun4** [comment]
i think its not worth to add in legacy anyway, when it depends on such hacky bs. use nextgen, which features packet type selection already (and therefore bypasses grim)

**Pull request closed without merging**
