### PR TITLE
feat(nextgen): BowAimbot improval

### PR DESCRIPTION
**Pull request by superblaubeere27**
https://github.com/CCBlueX/LiquidBounce/assets/22642852/69857485-a695-40ea-8a2f-092e46112cb6

### CODE REVIEW

**Comment by EclipsesDev** [comment]
Is this still on progress?

**Comment by 182exe** [comment]
this is cool :D

**Comment by superblaubeere27** [comment]
> Is this still on progress?

sure. The problem is that I currently have some trouble turning this into an assisting system.

It is currently fully autonomous, which means that it decides where it shoots. This is unfortunately useless in most game modes since players tend to change their movement once and so often.

So there are two options:
1. Create an utterly complex AI system that predicts where the player runs
2. Create an assistance system that just helps the user with aiming and predicting, because the user knows best what is happens next.

At the moment the controls are the main problem. I have to try some ideas out of how interactions with such a system could work...

**Comment by doesDeveloper** [comment]
Dont over complicate stuff.
Make a toggle for it to be strict/assistance mode.

**Comment by superblaubeere27** [comment]
> Dont over complicate stuff. Make a toggle for it to be strict/assistance mode.

yes that is exactly what I want to do

**Comment by superblaubeere27** [comment]
I have something like this in mind. I think if I polish this a lot more, it can actually be very useful...

https://github.com/CCBlueX/LiquidBounce/assets/22642852/d9c4cee5-0795-42a5-828e-1831b7a946be

**Comment by doesDeveloper** [comment]
This still is far more complex than anyone need.

**Comment by be4dev** [comment]
> I have something like this in mind. I think if I polish this a lot more, it can actually be very useful...
> java_Woy4zksGCc.mp4

that's fire

**Comment by superblaubeere27** [comment]
> This still is far more complex than anyone need.

Monke press location on screen, module will shoot position. I don't know if there is an easier compromise haha. The normal aimbot is still available. Even prediction can be deactivated.

**Comment by EclipsesDev** [comment]
> This still is far more complex than anyone need.

I mean why not? wouldn't that be better to have advanced aimbot prediction then the old one..

**Comment by 182exe** [comment]
yeah ong, i wish you luck with making this work :)
its super cool

**Comment by FengXiaoSkidGod** [comment]
I think you can add an ai in Liquidbounce nextgen
you don't should only use ai to bowaimbot
you can use it on everythings

**Comment by 1zun4** [comment]
> I think you can add an ai in Liquidbounce nextgen you don't should only use ai to bowaimbot you can use it on everythings

This is not AI. It is math.

**Comment by Razzy52** [comment]
any updates?

**Comment by superblaubeere27** [comment]
> any updates?

currently not, I have the source on another device which I wasn't able to access in the last few weeks haha

**Comment by SuicidalEeper** [comment]
Is this still being worked on at all?

**Comment by Husky272** [comment]
> I have something like this in mind. I think if I polish this a lot more, it can actually be very useful...
> 
>  java_Woy4zksGCc.mp4

cool

**Comment by SuicidalEeper** [comment]
@superblaubeere27 Is this being worked on at all?

**Comment by 1zun4** [comment]
I think this can be closed as it probably needs to be either merged or started from scratch as https://github.com/CCBlueX/LiquidBounce/pull/4952 has been merged.

**Pull request closed without merging**
