### PR TITLE
Update NoSlow.kt

### PR DESCRIPTION
**Pull request by 2933968621**
bypass AAC anti-cheat

### CODE REVIEW

**Comment by superblaubeere27** [comment]
Development is paused until the CrossVersion-Port is done.

**Comment by idkwhoisme** [comment]
yes but i hope it will look like noslow b66 :
image
and custom noslowdown like liquidbounce b73)))

**Comment by Teals53** [comment]
> yes but i hope it will look like noslow b66 :
> image
> and custom noslowdown like liquidbounce b73)))

wtf

**Comment by CzechHek** [comment]
wtf it aac mode just unblocks

**Comment by Teals53** [comment]
omg marco coming back ?

**Comment by Litely1222** [comment]
yes

**Pull request closed without merging**
