### PR TITLE
refactor(legacy): proper `mc.thePlayer` -> `player`

### PR DESCRIPTION
**Pull request by Coccocoahelper**
This should make development easier, and code smaller.

### CODE REVIEW

**Comment by Coccocoahelper** [comment]
Very buggy, can anyone help me fix?

**Comment by ghost** [comment]
chop chop

**Comment by EclipsesDev** [comment]
I deem this pull to be unnecessary, but if you still want to continue it, feel free to do so (whenever you feel ready, ping me to merge it) but unfortunately I won't be helping on this pull, since tbf this is quite unnecessary..

**Comment by 1zun4** [comment]
I think so too. Accessing nullable variables in certain situations can cause a lot of errors, this works for nextgen (because we do not run certain things without safe environment), but I do not think this is true for legacy.

**Pull request closed without merging**
