### PR TITLE
LEGACY: Add more AutoPlay modes

### PR DESCRIPTION
**Pull request by Coccocoahelper**
Ready for production, doing one last edit.

### CODE REVIEW

**Comment by EclipsesDev** [comment]
Any progress?

**Comment by Coccocoahelper** [comment]
> Any progress?

Trying to figure out the BW commands, but I'm banned on Hypixel.

**Comment by EclipsesDev** [comment]
> > Any progress?
> 
> Trying to figure out the BW commands, but I'm banned on Hypixel.

Just check hypixel forum, pretty sure there's tons of info there

**Comment by Coccocoahelper** [comment]
> > > Any progress?
> > 
> > 
> > Trying to figure out the BW commands, but I'm banned on Hypixel.
> 
> Just check hypixel forum, pretty sure there's tons of info there

Yep, thanks!

**Comment by EclipsesDev** [comment]
Also it would be nice to if u change "BlocksMC" mode to "Paper" since its useable for match queuing as long as there's paper

**Comment by Coccocoahelper** [comment]
> Also it would be nice to if u change "BlocksMC" mode to "Paper" since its useable for match queuing as long as there's paper

Done

**Comment by EclipsesDev** [comment]
check my review ^

**Comment by EclipsesDev** [comment]
K should be ready for merge now

**Pull request merged**
