### PR TITLE
feat(nextgen): Extend ScriptAPI functionallity

### PR DESCRIPTION
**Pull request by 1zun4**
- [x] Add support for creating and accessing settings
- [x] Add support for accessing other modules settings
- [x] Add support for registering choices to existing choice configurables (to existing modules or your own).
- [x] Simplify command creation via JS

### CODE REVIEW

**Comment by 1zun4** [comment]
```js
const script = registerScript({
    name: "MyScript",
    version: "1.0.0",
    authors: ["My Name"]
});

script.registerModule({
    name: "SpeedModule",
    category: "Misc",
    description: "An example module created with LiquidBounce's script API.",
    settings: {
        test: Setting.boolean("Test", true)
            .doNotInclude() // values marked as do not include will not show up in auto generated configs
    }
}, function (module) {
    module.on("enable", function() {
        client.displayChatMessage("§aHallo - du solltest funktionieren.");
    });

    module.on("disable", function() {
        client.displayChatMessage("§cTschüss - du solltest nicht mehr funktionieren.");
    });

    module.on("playerTick", function(event) {
        if (movementUtil.moving()) {
            movementUtil.strafeWithSpeed(0.3);
        }

        const speed = movementUtil.speed();
        client.displayChatMessage(typeof client.getModuleManager());

        // add velocity
        if (mc.player.onGround) {
            if (module.settings.test) {
                client.displayChatMessage("jump! :(");
            } else {
                client.displayChatMessage("jump! :)");
            }
            mc.player.jump();

            module.settings.test = !module.settings.test;
        } else if (mc.player.velocity.y < 0) {
            mc.player.addVelocity(new Vec3d(0.0, 0.0002, 0.0));
        } else {
            mc.player.velocity.y -= 0.1;
        }
    });
});

```

To access values from other modules you can simply write:
```js
const killAura = client.moduleManager.getModuleByName("KillAura");

if (killAura.settings.swing) {
    client.displayChatMessage("Swing is true");
} else {
    client.displayChatMessage("Swing is false");
}
killAura.settings.swing = !killAura.settings.swing;
```

**Comment by 1zun4** [comment]
image

It is not a good example, but now you can structure your scripts properly.

**Comment by 1zun4** [comment]
```js
script.registerCommand({
    name: "testconfig",
    aliases: ["tc"],
    hub: true,
    subcommands: [
        {
            name: "load",
            parameters: [
                {
                    name: "name",
                    required: true,
                },
                {
                    name: "local",
                    required: false,
                }
            ],
            onExecute(arg1, arg2) {
                client.displayChatMessage("Loaded local config " + arg1 + " " + arg2);
            }
        }
    ],
});

```

image

**Comment by 1zun4** [comment]
A full example for documentation @SenkJu 

```js
const script = registerScript({
    name: "MyScript",
    version: "1.0.0",
    authors: ["My Name"]
});

const speed = client.moduleManager.getModuleByName("Speed");
const killAura = client.moduleManager.getModuleByName("KillAura");

script.registerModule({
    name: "KillAuraSwingSwitch",
    category: "Misc",
    description: "An example module created with LiquidBounce's script API.",
    settings: {
        test: Setting.boolean("Test", true)
            .doNotInclude()
    }
}, function (module) {

    module.on("enable", function() {
        client.displayChatMessage("§aHallo - du solltest funktionieren.");
    });

    module.on("disable", function() {
        client.displayChatMessage("§cTschüss - du solltest nicht mehr funktionieren.");
    });

    module.on("playerTick", function(event) {
        if (killAura.settings.swing) {
            client.displayChatMessage("Swing is true");
        } else {
            client.displayChatMessage("Swing is false");
        }

        killAura.settings.swing = !killAura.settings.swing;
    });
});


script.registerChoice(speed.settings.Mode, {
    name: "Test",
    settings: {
        faster: Setting.boolean("Faster", true)
    }
}, function (choice) {

    choice.on("playerTick", function() {
        if (movementUtil.moving()) {
            if (choice.settings.faster) {
                movementUtil.strafeWithSpeed(0.5);
            } else {
                movementUtil.strafeWithSpeed(0.3);
            }
        }

        if (mc.player.onGround) {
            mc.player.jump();
        } else if (mc.player.velocity.y < 0) {
            mc.player.addVelocity(new Vec3d(0.0, 0.0002, 0.0));
        } else {
            mc.player.velocity.y -= 0.1;
        }
    });

})

script.registerCommand({
    name: "testconfig",
    aliases: ["tc"],
    hub: true,
    subcommands: [
        {
            name: "load",
            parameters: [
                {
                    name: "name",
                    required: true,
                },
                {
                    name: "local",
                    required: false,
                }
            ],
            onExecute(arg1, arg2) {
                client.displayChatMessage("Loaded local config " + arg1 + " " + arg2);
            }
        }
    ],
});
```

```kotlin
// Global functions
jsBindings.putMember("registerScript", RegisterScript())
```

The JsContextProvider currently features:
```kotlin
// Class bindings
// -> Client API
putMember("Setting", JsSetting)

// -> Minecraft API
putMember("Vec3i", Vec3i::class.java)
putMember("Vec3d", Vec3d::class.java)
putMember("MathHelper", MathHelper::class.java)
putMember("BlockPos", BlockPos::class.java)
putMember("Hand", Hand::class.java)

// Variable bindings
putMember("mc", mc)
putMember("client", JsClient)

// Register utilities
putMember("rotationUtil", JsRotationUtil)
putMember("itemUtil", JsItemUtil)
putMember("networkUtil", JsNetworkUtil)
putMember("interactionUtil", JsInteractionUtil)
putMember("blockUtil", JsBlockUtil)
putMember("movementUtil", JsMovementUtil)
putMember("reflectionUtil", JsReflectionUtil)
```

**Comment by superblaubeere27** [comment]
Great work 👍🏻

**Pull request merged**
