### PR TITLE
LEGACY: Optimized Transformer

### PR DESCRIPTION
**Pull request by EclipsesDev**

### CODE REVIEW

**Comment by EclipsesDev** [comment]
@1zun4 is it ok to add this?

**Comment by Razzy52** [comment]
your turning base lb into fdp client 💀

**Comment by EclipsesDev** [comment]
> your turning base lb into fdp client 💀

so ig no? I'm only trying to optimize the transformer..

**Comment by EclipsesDev** [comment]
I mean its not urgent, so close ig?

**Pull request closed without merging**
