### PR TITLE
feat: add more conditions to Eagle

### LINKED ISSUE #3923: [FEATURE] More Eagle settings
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Pitch check, direction check, and blocks only would be some nice quality of life features to be added to the eagle module.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MukjepScarlet**
image

(resolves #3923)

### CODE REVIEW

**Comment by Coccocoahelper** [comment]
Can you add min and max Eagle Edge Distance, too?

**Comment by MukjepScarlet** [comment]
What do you mean? I don't understand why you need a minimum value of that. You could describe it in detail.

**Comment by Husky272** [comment]
> What do you mean? I don't understand why you need a minimum value of that. You could describe it in detail.

He want a random edge distance

**Comment by Husky272** [comment]
> What do you mean? I don't understand why you need a minimum value of that. You could describe it in detail.

He want a random edge distance

**Comment by MukjepScarlet** [comment]
@superblaubeere27

**Pull request merged**
