### PR TITLE
Matrix inventorymove

### PR DESCRIPTION
**Pull request by TheFleksisCekcu**
Code share:
https://hastebin.com/utunenuveg.cpp

### CODE REVIEW

**Comment by derech1e** [comment]
Hint: Pull first the latest changes of the repo, before you commit something. It makes easier to see what you changed. (Command: git pull)

**Comment by superblaubeere27** [comment]
You commited every change of your custom fork. Can you please only add the changes to the branch which should be in the PR?

**Comment by TheFleksisCekcu** [comment]
ouch, i dont saw that. i made commit using phone

**Comment by superblaubeere27** [comment]
xD

**Pull request closed without merging**
