### PR TITLE
LEGACY: Added ItemPhysics Module

### PR DESCRIPTION
**Pull request by EclipsesDev**
Took about 2 hour to tweak, but there you go

### CODE REVIEW

**Comment by Cosmic-SC** [comment]
skidded from fdp *cough* *cough*

**Comment by EclipsesDev** [comment]
> skidded from fdp _cough_ _cough_

look at the comment on the code bud

**Comment by Cosmic-SC** [comment]
still contains code from fdp = skidding (even if you modified the original code)

**Comment by EclipsesDev** [comment]
sure partially the code contain from fdp, but is it wrong to do so? i mean "You are allowed to:

use
share
modify
This project entirely or partially for free and even commercially. However, please consider the following:

You must disclose the source code of your modified work and the source code you took from this project. This means you are not allowed to use code from this project (even partially) in a closed-source (or even obfuscated) application." and i gave a proper credit to it..

**Comment by EclipsesDev** [comment]
well ig its up to @mems01 to either merge it or not..

**Comment by Cosmic-SC** [comment]
> well ig its up to @mems01 to either merge it or not..

ye

**Comment by ghost** [comment]
FDP is a LiquidBounce Legacy fork and that's one good thing about this. What we should know is if the code is stolen from a closed source/paid client. If it is then I cannot merge this. Otherwise accepted.

EDIT: They are known for mostly stealing code from various hacked clients, this is why I'm asking. Either way, this question should be a must when it comes to things like this.

**Comment by 1zun4** [comment]
ItemPhysics is a mod. I have been using this one myself on Legacy for quite some time and we have never considered adding this as a module, since its already a well-known mod. If you actually want to implement this, take it from the original source and credit them for their work. Otherwise we will decline this PR.

https://modrinth.com/mod/itemphysic
https://github.com/CreativeMD/ItemPhysic/tree/1.8.9

**Comment by EclipsesDev** [comment]
> FDP is a LiquidBounce Legacy fork and that's one good thing about this. What we should know is if the code is stolen from a closed source/paid client. If it is then I cannot merge this. Otherwise accepted.
> 
> EDIT: They are known for mostly stealing code from various hacked clients, this is why I'm asking. Either way, this question should be a must when it comes to things like this.

what if i fully recode it? will it still considered as skidded from fdp? (just asking btw)

**Comment by ghost** [comment]
Just do it the way the ItemPhysics mod does it, read what 1zuna said.

**Comment by EclipsesDev** [comment]
> Just do it the way the ItemPhysics mod does it, read what 1zuna said.

idk man, seems complicated for newbie like me

**Comment by EclipsesDev** [comment]
> Just do it the way the ItemPhysics mod does it, read what 1zuna said.

ahh wait.. appearently fdp client got their itemphysics from the original lol.. tho they remove most of the unused original part

**Comment by EclipsesDev** [comment]
@mems01 after double checking yes, even tho most of fdp bypasses & hud are stolen from other client, but the itemphysics one are actualy based on the original mod, so does that prove this statement to be false? 

"FDP is a LiquidBounce Legacy fork and that's one good thing about this. What we should know is if the code is stolen from a closed source/paid client. If it is then I cannot merge this. Otherwise accepted.

EDIT: They are known for mostly stealing code from various hacked clients, this is why I'm asking. Either way, this question should be a must when it comes to things like this."

**Comment by EclipsesDev** [comment]
and yes you can compare both here.. tho the fdp version is more like a simplified one

https://github.com/CreativeMD/ItemPhysic/blob/1.8.9/src/main/java/com/creativemd/itemphysic/physics/ClientPhysic.java

https://github.com/SkidderMC/FDPClient/blob/main/src/main/java/net/ccbluex/liquidbounce/injection/forge/mixins/render/MixinRenderEntityItem.java

**Comment by EclipsesDev** [comment]
example from original: "if (!flag1)
        {
            float f3 = -0.0F * (float)(j - 1) * 0.5F;
            float f4 = -0.0F * (float)(j - 1) * 0.5F;
            float f5 = -0.09375F * (float)(j - 1) * 0.5F;
            GlStateManager.translate(f3, f4, f5);
        }"
        
fdp: 
"if (!flag) {
                float f6 = -0.0F * (float)(i - 1) * 0.5F;
                float f4 = -0.0F * (float)(i - 1) * 0.5F;
                float f5 = -0.046875F * (float)(i - 1) * 0.5F;
                GlStateManager.translate(f6, f4, f5);
            }"

**Comment by EclipsesDev** [comment]
> FDP is a LiquidBounce Legacy fork and that's one good thing about this. What we should know is if the code is stolen from a closed source/paid client. If it is then I cannot merge this. Otherwise accepted.
> 
> EDIT: They are known for mostly stealing code from various hacked clients, this is why I'm asking. Either way, this question should be a must when it comes to things like this.

so ig the code is not stolen, more to a simplified version of the original mod, so merge? @mems01

**Pull request closed without merging**
