### PR TITLE
Create FakeHackers.kt

### PR DESCRIPTION
**Pull request by Razzy52**
Added "Trolling" Module, allows you to make it so any player looks like they are using Killaura.

### CODE REVIEW

**Comment by Razzy52** [comment]
Am i missing something in the code i added?

**Comment by 1zun4secondary** [comment]
Please make use of kotlin functionallity and insert the description into en_US instead of hardcoding it. Also DO NOT USE kotlin auto translater. It was clearly Java code before.

**Comment by Razzy52** [comment]
I think i fixed the main issues with it? I added en_us like you asked, and added kotlin functionality I think? Im still fairly new to coding/ Developing so i will get a few things wrong.

**Comment by CzechHek** [comment]
This cannot be compiled, are you using an IDE?

You should take a look at structure of other modules.

**Comment by 1zun4secondary** [comment]
uhm tf? Now you override random files and the code looks like AI generated?

**Comment by CzechHek** [comment]
image
Ah, yes!

**Comment by Razzy52** [comment]
I have legitimately no clue what I've done, Maybe i'll come back to this at a later date.

**Pull request closed without merging**
