### PR TITLE
Tower Improvements.

### PR DESCRIPTION
**Pull request by mems01**
* Added the ability to return back to your previous slot automatically when you disable Tower.
* Added an AutoBlock mode.

### CODE REVIEW

**Comment by kawaiinekololi** [comment]
The idea of turning auto block into modes is good, but I don't like how they work.

**Review by kawaiinekololi — CHANGES_REQUESTED** [review]
Pick mode: Select item in hotbar (non silent)
Spoof: Select item in hotbar (silent)
Switch: Just switch on place (silent)

**Comment by mems01** [comment]
Done.

**Comment by mems01** [comment]
Done x2. If this is what you want then okay. I personally don't like your idea but you decide.

**Comment by kawaiinekololi** [comment]
well done @bestnub exactly what I wanted.

**Pull request merged**
