### PR TITLE
autoarmor bug fix

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by superblaubeere27** [comment]
What does this exactly fix?

**Comment by ghost** [comment]
> What does this exactly fix?

It probably fixes its purpose, not (re)placing armors.

**Comment by ghost** [comment]
There is a bug in 1.8.9 (idk about 1.12.2) where it doesnt replace armor if you have any armor on it just glitches out because of that line of code

**Comment by ghost** [comment]
yea, it would just keep switching 2 pieces of armour over and over until the other one was dropped

**Comment by superblaubeere27** [comment]
I would merge it rn, but for some reason the build fails 🤔

**Comment by ghost** [comment]
> I would merge it rn, but for some reason the build fails 🤔

I’m pretty sure it’s cause it’s trying to build next gen out of this

**Comment by ghost** [comment]
Wait nvm

**Comment by 1zun4** [comment]
Please merge the new changes from the nextgen branch into your pull request to fix the building issue.
https://github.com/CCBlueX/LiquidBounce/runs/2885107056
https://github.com/CCBlueX/LiquidBounce/commit/5551db87d307dcefd8486b65dca47290c606ba85

**Comment by 1zun4secondary** [comment]
Please try to pull the newest changes from the legacy branch into your pull request.
https://github.com/CCBlueX/LiquidBounce/commit/ffae8c3895ecd63c3df5607093d357bfa6503ccc

Building should be fixed from this commit.

**Comment by ghost** [comment]
nvm cant do it from site, will do it later

**Comment by ghost** [comment]
> nvm cant do it from site, will do it later

Isn't there a `Fetch upstream` button on your branch ? Click that and it's done.

**Comment by ghost** [comment]
> 
> 
> > nvm cant do it from site, will do it later
> 
> Isn't there a `Fetch upstream` button on your branch ? Click that and it's done.

there is but it for what ever reason tries to merge from from nextgen branch

**Comment by ghost** [comment]
https://github.com/Haizive/LiquidBounce/tree/patch-2

**Pull request closed without merging**
