### PR TITLE
Legacy: fix the bug of arraylist slide animation

### PR DESCRIPTION
**Pull request by gaoyu06**
#1907 the slide mode didn't work.

### CODE REVIEW

**Comment by gaoyu06** [comment]
wtf i pushed sth wrong

**Comment by superblaubeere27** [comment]
Hey, you stole my profile picture :o

**Comment by gaoyu06** [comment]
> Hey, you stole my profile picture :o

Yes, I'm truly sorry. I once watched your videos on YouTube to learn how to make Minecraft clients and I have been using your avatar as mine out of admiration for a few years. If this has caused any problems, I will replace it.

**Comment by superblaubeere27** [comment]
> > Hey, you stole my profile picture :o
> 
> Yes, I'm truly sorry. I once watched your videos on YouTube to learn how to make Minecraft clients and I have been using your avatar as mine out of admiration for a few years. If this has caused any problems, I will replace it.

I just got confused, because I thought I made this PR for a second haha. If I wanted you to change it I would have already asked.

It's fine, you can keep it ;)

**Comment by gaoyu06** [comment]
Thank you very much

**Pull request closed without merging**
