### PR TITLE
[LEGACY] Update TimerRange

### PR DESCRIPTION
**Pull request by EclipsesDev**
Added Teams support to TimerRange

### CODE REVIEW

**Comment by EclipsesDev** [comment]
@mems01 this is ready btw.. 👌

**Comment by CzechHek** [comment]
You don't need anything except isSelected look at its source?

**Comment by EclipsesDev** [comment]
> You don't need anything except isSelected look at its source?

oh damn, didn't realize it already have the other checks in the entityutils.. maybe you could help me changed it, since Im on my phone rn, and I gotta go sleep, or maybe I'll fix it tomorrow

**Comment by EclipsesDev** [comment]
> You don't need anything except isSelected look at its source?

#1664 Can u check this out?

**Pull request merged**
