### PR TITLE
Chinese translation

### PR DESCRIPTION
**Pull request by guosic**
First time using pull request...

### CODE REVIEW

**Comment by guosic** [comment]
Completed

**Comment by 1zun4secondary** [comment]
grafik

Our font renderer is not supporting chinese characters so well and falls back to the Minecraft font renderer, needs to be fixed in order to be merged.

**Comment by 1zun4** [comment]
Good news.

I have now fixed the font renderer conflicting with chinese/unicode characters:
grafik
grafik
grafik

But it still is very buggy to this point. I need to put a little bit more work into this.

**Comment by guosic** [comment]
> 

@1zun4 A few questions:
1. Chinese font size issue
屏幕截图 2023-06-08 205423
屏幕截图 2023-06-08 205445

2. Issues with mixing Chinese and English text
屏幕截图 2023-06-08 205601

3. Inconsistent English fonts
屏幕截图 2023-06-08 210013

4. Text exceeding the background box/background box too long
屏幕截图 2023-06-08 210153
屏幕截图 2023-06-08 210220

**Comment by 1zun4** [comment]
Ok alright. It seems it needs a little bit more work...

**Pull request merged**
