### PR TITLE
Updated Commands

### PR DESCRIPTION
**Pull request by derech1e**
- changed some module specific commands to have a better overview

### CODE REVIEW

**Comment by kawaiinekololi** [comment]
I don't really like the idea of splitting the commands up into own classes, but might be better.
 Did you added the block blacklist command, because there is no way to save/load the blocks from a config yet.

**Comment by kawaiinekololi** [comment]
I think I can merge it, but I'll need to add something to load and save the blacklisted blocks.

**Comment by derech1e** [comment]
> I think I can merge it, but I'll need to add something to load and save the blacklisted blocks.

Oh no, I forgot to remove it. I tested something for the InvCleaner recode. It's not finally at all. Sry

**Comment by derech1e** [comment]
> I don't really like the idea of splitting the commands up into own classes, but might be better.
>  Did you added the block blacklist command, because there is no way to save/load the blocks from a config yet.

The command was only a test for the invcleaner recode.

**Comment by kawaiinekololi** [comment]
Oh. I'll remove it later, but maybe it's not a bad idea to add a command like that. But it's not so useful right now.

**Pull request merged**
