### PR TITLE
Portuguese (Portugal) translation

### PR DESCRIPTION
**Pull request by gabrielvicenteYT**
I'll keep it as a draft for a while

### CODE REVIEW

**Comment by opZywl** [comment]
Many things missing/errors 
please fix

**Comment by 1zun4secondary** [comment]
> Many things missing/errors please fix

It is still a draft. I guess he is working on it.

**Comment by gabrielvicenteYT** [comment]
> > Many things missing/errors please fix
> 
> It is still a draft. I guess he is working on it.

I am, it's just that I don't translate everything using Google Translate unlike Zywl (I used my language skills to detect that)

**Comment by 1zun4secondary** [comment]
I am fine with translators, they can be pretty good, but it needs to be done with a proper one like DeepL or using AI tools (ChatGPT) which perform much better as translater than Google Translate or else. Especially AI Tools can understand the context of the message much better if you give him at least detail what they are about. It does not need to be a 1 to 1 translation.

**Comment by opZywl** [comment]
> > > Many things missing/errors please fix
> > 
> > 
> > It is still a draft. I guess he is working on it.
> 
> I am, it's just that I don't translate everything using Google Translate unlike Zywl (I used my language skills to detect that)

💀 sure okay 'unlike zywl' but believe it or not
 I'm really portuguese and I live in Brazil!!

**Comment by gabrielvicenteYT** [comment]
> > > > Many things missing/errors please fix
> > > 
> > > 
> > > It is still a draft. I guess he is working on it.
> > 
> > 
> > I am, it's just that I don't translate everything using Google Translate unlike Zywl (I used my language skills to detect that)
> 
> 💀 sure okay 'unlike zywl' but believe it or not I'm really portuguese and I live in Brazil!!

I know that you are Brazilian, but Brazil =/ Portugal except in the essence of the language itself; the accent is entirely different, along with other things. In a way, people from Portugal can actually speak both Brazilian Portuguese, and Portuguese from Portugal, since in Brazil, "Informal" doesn't really exist, therefore Brazilians have less knowledge to learn Portuguese from Portugal. Hope I have clarified a few things, good luck :)

**Comment by opZywl** [comment]
> I know that you are Brazilian, but Brazil =/ Portugal except in the essence of the language itself; the accent is entirely different, along with other things. In a way, people from Portugal can actually speak both Brazilian Portuguese, and Portuguese from Portugal, since in Brazil, "Informal" doesn't really exist, therefore Brazilians have less knowledge to learn Portuguese from Portugal. Hope I have clarified a few things, good luck :)

What you said is completely wrong, but if this is your information about teaching Portuguese ok. just finish your translation I correct it myself if I find errors

**Comment by gabrielvicenteYT** [comment]
> > I know that you are Brazilian, but Brazil =/ Portugal except in the essence of the language itself; the accent is entirely different, along with other things. In a way, people from Portugal can actually speak both Brazilian Portuguese, and Portuguese from Portugal, since in Brazil, "Informal" doesn't really exist, therefore Brazilians have less knowledge to learn Portuguese from Portugal. Hope I have clarified a few things, good luck :)
> 
> What you said is completely wrong, but if this is your information about teaching Portuguese ok. just finish your translation I correct it myself if I find errors

Not really; though Brazilian DOES have Informal, it is nothing like (Portugal) Portuguese...

**Comment by gabrielvicenteYT** [comment]
> I am fine with translators, they can be pretty good, but it needs to be done with a proper one like DeepL or using AI tools (ChatGPT) which perform much better as translater than Google Translate or else. Especially AI Tools can understand the context of the message much better if you give him at least detail what they are about. It does not need to be a 1 to 1 translation.

Yeah; but in Zywl's Brazilian Portuguese translation, there are multiple inconsistencies, making it seem like Google Translate is used in the place of a human.

**Comment by 1zun4** [comment]
How is it going?

**Comment by gabrielvicenteYT** [comment]
Meh, I'm lazy. I'll make this able to be merged, and I'll improve it later.

**Comment by gabrielvicenteYT** [comment]
@1zun4 merge

**Comment by 1zun4** [comment]
It cannot be merged yet, because it is not listed in the client.

**Pull request merged**
