### PR TITLE
intave velocity

### PR DESCRIPTION
**Pull request by larryngton2**
ported intave velocity from legacy and added reduce from dexland mode

### CODE REVIEW

**Comment by ghost** [comment]
isnt dexland (nextgen) and intave (legacy) velo basically the same thing? if not please explain

**Comment by larryngton2** [comment]
> isnt dexland (nextgen) and intave (legacy) velo basically the same thing? if not please explain

legacy's intave velo doesnt reduce, it only jump resets

**Comment by larryngton2** [comment]
image
never coding on my phone again wtf is this

**Comment by larryngton2** [comment]
merg

**Pull request merged**
