### PR TITLE
Changes to bug_report.yml

### PR DESCRIPTION
**Pull request by ghost**
IOS Is the one for phones lol

### CODE REVIEW

**Comment by ghost** [comment]
Windows vista does not meet the minecraft system requirements so I removed it
Also macOS is the pc os, iOS is the one for phones and tablets

**Comment by derech1e** [comment]
> Windows vista does not meet the minecraft system requirements so I removed it
> 
> Also macOS is the pc os, iOS is the one for phones and tablets

Looks good. I had overlooked that with Vista and iOS.

**Comment by ghost** [comment]
Ty man

**Comment by ghost** [comment]
The new templates look really good otherwise, nice job!

**Comment by CzechHek** [comment]
alphabetically (1 is technically in front of 7 but it makes more sense like this):
    - Linux
    - macOS
    - Windows 7
    - Windows 8
    - Windows 8.1
    - Windows 10

**Comment by ghost** [comment]
> alphabetically (1 is technically in front of 7 but it makes more sense like this):
> - Linux
> - macOS
> - Windows 7
> - Windows 8
> - Windows 8.1
> - Windows 10

Ig it does make more sense although it’s not alphabetical, but I think it’s easier if 10 s near the top since the most people will probably be using it

**Pull request merged**
