### PR TITLE
feat: added rotation prediction to godbridge scaffold 

### PR DESCRIPTION
**Pull request by larryngton2**
when prediction is enabled and scaffold fails to place a block, it will fallback to the predictions of the normal mode using ScaffoldNormalTechnique.getRotations(target). (even if its called getRotations the prediction doesn't actually get affected by the normal mode's rotations because of the CenterTargetPositionFactory setting - line 102)

### CODE REVIEW

**Review by 1zun4 — CHANGES_REQUESTED** [review]
Prediction causes head jitter - without Prediction GodBridge keeps falling and does not work anymore.

**Comment by larryngton2** [comment]
when you test it check if you have ledge enabled before trying to use it without predictions, it never worked without it. and you need to have atleast a bit of pitch jitter so you dont fall with the predictions

**Comment by 1zun4** [comment]
It is still broken. It aims at the wrong block when trying to tower, it flicks its head a lot when near another block, etc.

**Comment by larryngton2** [comment]
fuck this

**Pull request closed without merging**
