### PR TITLE
feat: improve the help command

### PR DESCRIPTION
**Pull request by ccetl**
Video showing the changes:
https://streamable.com/pbxkb4

### CODE REVIEW

**Comment by 1zun4** [comment]
Please revert commit 9f95fcdb7d6580e2d0d5c20c9a8b6c1e6510f7c2

**Comment by ccetl** [comment]
> Please revert commit [9f95fcd](https://github.com/CCBlueX/LiquidBounce/commit/9f95fcdb7d6580e2d0d5c20c9a8b6c1e6510f7c2)

I did so in #3291.

**Comment by 1zun4** [comment]
> > Please revert commit [9f95fcd](https://github.com/CCBlueX/LiquidBounce/commit/9f95fcdb7d6580e2d0d5c20c9a8b6c1e6510f7c2)
> 
> I did so in #3291.

Yes but this PR still has the commit attached to it. I force-pushed to clean-up the revert mess.

**Comment by ccetl** [comment]
Oh, I'll create a new PR.

**Pull request closed without merging**
