### PR TITLE
Packethandler patch

### PR DESCRIPTION
**Pull request by papejik**

### CODE REVIEW

**Comment by superblaubeere27** [comment]
The commits in your PR are not well organized. I am scared of merging this since it might cause the entire `nextgen` branch to break (which happened in the past).

To create multiple PRs at once do the following:
1. Pull the latest version from the repository
2. Create a new branch for your PR and check it out
3. Do your changes on the branch, commit and them
4. Create your PR
5. If you want to create a new PR, check the master branch (In this case `main`) out and start at point `1`

**Comment by papejik** [comment]
Can u help me in discord a bit pls?

**Comment by superblaubeere27** [comment]
> 
> 
> Can u help me in discord a bit pls?

sure

**Comment by papejik** [comment]
pepej#2403

**Pull request closed without merging**
