### PR TITLE
feat: theme accent color

### PR DESCRIPTION
**Pull request by 1zun4**

### CODE REVIEW

**Comment by Ell1ott** [comment]
I suppose you want to later make use of the theme accent color in the default theme? I tried doing something along those lines a little while ago. It's [here](https://github.com/Ell1ott/LiquidBounce/tree/changeable-colors) if you would like to take a look at it for inspiration. I stopped because, with CSS variables, I didn't have access to all the SCSS functions like darken, etc. This made it a very tedious process to convert it to base CSS. Maybe there is a better solution?

**Comment by 1zun4** [comment]
I only did this because breadcrumbs has an awful standard color

**Comment by Ell1ott** [comment]
Ah, okay. Well, it would be nice if you, in the future, could control the theme's colors using a setting.

**Comment by 1zun4** [comment]
Will do this properly instead.

**Pull request closed without merging**
