### PR TITLE
[LEGACY] Remove skidded code

### PR DESCRIPTION
**Pull request by gabrielvicenteYT**
I will also consider removing the AAC5 mode, but whatever.

### CODE REVIEW

**Comment by RtxOP** [comment]
Everybody and their mother has these noslows kinda funny

**Comment by Euro-pol** [comment]
then remove ur entire coda n😱gga

**Comment by gabrielvicenteYT** [comment]
> then remove ur entire coda n😱gga

The code that I publish is not skidded, taking inspiration != skidded. Actually, I hardly ever check other clients' code.

**Comment by Euro-pol** [comment]
> > then remove ur entire coda n😱gga
> 
> The code that I publish is not skidded, taking inspiration != skidded. Actually, I hardly ever check other clients' code.

yeah on god

**Pull request merged**
