### PR TITLE
[NEXTGEN] Added Nametags + Retired RenderEngine

### LINKED ISSUE #1520: [FEATURE] NameTags (nextgen)
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Please add nametags module (fix it).

<details>
<summary>Me when no nametags</summary>
<picture>

</picture>
</details>
<details>
<summary>Me when nametags</summary>
<picture>

</picture>
</details>

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by superblaubeere27**
Progress:
- [X] Remake NameTags Module
- [X] Add font loading
- [x] Sword/Armor-Rendering
- [x] Use WorldToScreen function

How it looks:
grafik

### CODE REVIEW

**Comment by Ell1ott** [comment]
Very nice! Looks slightly weird tho how the nametags that are closer to the middle are smaller than the ones out to the sides
image

**Comment by superblaubeere27** [comment]
> Very nice! Looks slightly weird tho how the nametags that are closer to the middle are smaller than the ones out to the sides image

Yes. That is a known bug that comes from affine transformation. You can also see it in legacy. Older nextgen versions used a WorldToScreen-function which I would like to use too, but I wasn't able to create a working world to screen function :/

**Comment by Ell1ott** [comment]
> > Very nice! Looks slightly weird tho how the nametags that are closer to the middle are smaller than the ones out to the sides image
> 
> Yes. That is a known bug that comes from affine transformation. You can also see it in legacy. Older nextgen versions used a WorldToScreen-function which I would like to use too, but I wasn't able to create a working world to screen function :/

Yes, i tried too to create some WorldToScreen but didn't work. If we could somehow get the FOV for the current frame, the math shouldn't pose too much af a problem.

**Comment by superblaubeere27** [comment]
I was finally able to create a working world to screen function :D

**Comment by superblaubeere27** [comment]
Ok, this might take a while...
grafik

**Comment by superblaubeere27** [comment]
ok, it works. 
grafik

**Pull request merged**
