### PR TITLE
Nextgen: MCEF and RestAPI/WebSocket support

### PR DESCRIPTION
**Pull request by 1zun4**
**Integration**
- [x] MCEF Integration
- [x] RestAPI and WS
- [x] Theme Managment

**Svelte Theme Integration**
- [x] Svelte Router (Virtual Screen Implementation)
- [x] Title
- [x] HUD
- [x] Alt Manager (rewrite to Svelte)
- [x] Proxy Manager (rewrite to Svelte)
- [x] Splash Screen (rewrite to Svelte)

**ClickGUI**
- [x] ClickGUI Panels
- [x] ClickGUI Search Bar
- [x] ClickGUI Settings (Boolean)
- [x] ClickGUI Settings (Choice)
- [x] ClickGUI Settings (Choose)
- [x] ClickGUI Settings (Color)
- [x] ClickGUI Settings (Configurable)
- [x] ClickGUI Settings (Range)
- [x] ClickGUI Settings (Text)
- [x] ClickGUI Settings (Toggleable Configurable)
- [x] ClickGUI Settings Write Testing

### CODE REVIEW

**Comment by Ell1ott** [comment]
Will this fix #1556?

**Comment by 1zun4** [comment]
> Will this fix #1556?

I don't know?

**Comment by Ell1ott** [comment]
> > Will this fix #1556?
> 
> I don't know? 

Like, how is mcef/jcef performance wise? Ultralight had some problems, and was getting leggy when you just got a lot of notifications. Do you have any idea of how this would perform in mcef?

**Comment by Ell1ott** [comment]
> > Will this fix #1556?
> 
> I don't know? 

Like, how is mcef/jcef performance wise? Ultralight had some problems, and was getting leggy when you just got a lot of notifications. Do you have any idea of how this would perform in mcef?

**Comment by SenkJu** [comment]
> Like, how is mcef/jcef performance wise? Ultralight had some problems, and was getting leggy when you just got a lot of notifications. Do you have any idea of how this would perform in mcef?

We can't tell yet.

**Comment by 1zun4** [comment]
A demo of the event websocket

https://github.com/CCBlueX/LiquidBounce/assets/12410754/663eb059-35a0-453e-a4f2-552cbe8b40dd

_After some design tweaks:_
image

**Comment by 1zun4** [comment]
RestAPI supported now
Self written using netty :)

image
image
image

**Comment by 1zun4** [comment]
CEF currently restricted to 30fps. Looking into this...

image

image
image

**Comment by 1zun4** [comment]
https://github.com/CCBlueX/java-cef/commit/24d2ebf00e6c7315ac8ac33e8731c2d80bcef14b

image

Now runs at 120 fps. I am wondering on how CEF came up with 30 fps
https://github.com/chromiumembedded/cef/blob/a98cd4cdc0fdc49b6c38ba10cec800922745441e/tests/cefclient/browser/main_context_impl.cc#L82-L87

**Comment by 1zun4** [comment]
JCEF Demo with Subway Surfers

https://youtu.be/eFr3szM79jI

**Comment by 1zun4** [comment]
Bug 1:
Toggleable Enabled value not being written correctly.

image

**Pull request merged**
