### PR TITLE
Added Enderpearl Fly mode.

### PR DESCRIPTION
**Pull request by ghost**
What it does is simply place an enderpearl below and then makes you fly just when you land. This mode might fit more as a Long/High Jump mode, if you want me to change it, I will.

### CODE REVIEW

**Comment by Ali00035** [comment]
> What it does is simply place an enderpearl below and then makes you fly just when you land. This mode might fit more as a Long/High Jump mode, if you want me to change it, I will.

I wonder why anticheats disable themselves when you throw an ender pearl

Works on ViperHCF btw

**Comment by Ali00035** [comment]
> > What it does is simply place an enderpearl below and then makes you fly just when you land. This mode might fit more as a Long/High Jump mode, if you want me to change it, I will.
> 
> I wonder why anticheats disable themselves when you throw an ender pearl
> 
> Works on ViperHCF btw

Oooh I found out why,

If you want to know use matrix anticheat in eu.loyisa.cn and type /back

it false flags lol

**Comment by ghost** [comment]
I need to make this more smart.

**Comment by Ali00035** [comment]
> I need to make this more smart.

ok

**Comment by ghost** [comment]
And for some reason as of today it bypasses Jartex:

[Video...](https://streamable.com/8y9qwv)

**Comment by Ali00035** [comment]
> And for some reason as of today it bypasses Jartex:
> 
> [Video...](https://streamable.com/8y9qwv)

LMAOOOOOO

**Comment by fucksophie** [comment]
Craziest matrix bypass known to man!! Literally epearl = full fly bypass 👍🏽 !!

I also built a version of this, here: 
[client (1).zip](https://github.com/CCBlueX/LiquidBounce/files/7397938/client.1.zip)

**Comment by ghost** [comment]
Don't get too hyped because it only works when you are connected with 1.17.x version.

**Comment by Ali00035** [comment]
> Don't get too hyped because it only works when you are connected with 1.17.x version.

alright

(viaforge moment)

**Pull request merged**
