### PR TITLE
feat(legacy): add MinRotationDiffFromEnemyToIgnore to SuperKnockback

### PR DESCRIPTION
**Pull request by Coccocoahelper**
Good against 'runners', that usually turn backwards when getting comboed

### CODE REVIEW

**Comment by Coccocoahelper** [comment]
EclipsesDev made it compile, should be testable.

**Comment by Coccocoahelper** [comment]
Might work, not 100% sure, though.

**Comment by ghost** [comment]
Might? Have you even tested?

**Comment by ghost** [comment]
The logic has been improved a bit. Yes, the name is a bit longer, but it's better for non-experienced cheaters.

**Pull request merged**
