### PR TITLE
[LEGACY] Legit modules and AttackEffects

### PR DESCRIPTION
**Pull request by zyklone4096**
Add AttackEffects
Add LegitSpeed (SpeedMode)
Add AutoRod

### CODE REVIEW

**Comment by 1zun4secondary** [comment]
The code needs a lot of cleanup.

**Comment by zyklone4096** [comment]
> The code needs a lot of cleanup.

which of them? i cant find

**Comment by 1zun4secondary** [comment]
all of them 💀 I mean did you even test them? For example: LegitSpeed will throw errors 24/7. I see that from looking at the code already.

**Comment by zyklone4096** [comment]
fixed npe in AutoRod, no errors found when testing LegitSpeed and AttackEffects

**Comment by contionability** [comment]
bro, I think you forgot a '!' before MovementUtils.isOnGround(0.5)

**Comment by zyklone4096** [comment]
> bro, I think you forgot a '!' before MovementUtils.isOnGround(0.5)

you are right, thx

**Review by zyklone4096 — COMMENTED** [review]
?

**Comment by 1zun4secondary** [comment]
> ?

Please wait until we reviewed your pull request. It might take some days.

**Comment by exampleContributor** [comment]
Cleanup your code I really don't like the way you code. It would be useful if you would know the Java conventions 🤕

**Comment by 1zun4secondary** [comment]
AutoRod is literally just spamming the rod?

**Comment by 1zun4secondary** [comment]
AutoRod still sucks, but not as much as before. There are a lot of things missing for it to be a "good" autorod.

**Comment by 1zun4secondary** [comment]
and AttackEffects? What the fuck is this code and it doesn't even work because it is missing all sound files.

**Comment by 1zun4secondary** [comment]
ah shit I forgot about cleaning up the velocity changes and speed... what ever

**Comment by 1zun4secondary** [comment]
Anyway @tumuidle please take a look at the changes and try making better code in the future.

**Pull request merged**
