### PR TITLE
Edit slider value(s) via the keyboard

### PR DESCRIPTION
**Pull request by Ell1ott**
By clicking the number/numbers above the slider you can edit them using the keyboard 

https://github.com/CCBlueX/LiquidBounce/assets/85990359/6997f1fa-0624-4e32-be65-1d6506704833

### CODE REVIEW

**Comment by superblaubeere27** [comment]
Thank you for your contribution. I will test it and review. @SenkJu is responsible for UI.

**Comment by Ell1ott** [comment]
> Thank you for your contribution. I will test it and review. @SenkJu is responsible for UI.

Thanks!

**Comment by 1zun4** [comment]
Very cool! But does it prevent the user from typing in characters instead of numbers. It does not seem so.

**Comment by Ell1ott** [comment]
> Very cool! But does it prevent the user from typing in characters instead of numbers. It does not seem so.

Thanks for checking it out. No, currently it will not immediately block the user from typing characters, but when closing and opening the click GUI, it will display the correct numbers again. It also won't break the module and will keep working (even when not opening the GUI again). If this is a dealbreaker, I will have a look into it and see if I can change it. I tried doing it by changing the input type to number, but it didn't seem to change anything.

**Comment by superblaubeere27** [comment]
> Very cool! But does it prevent the user from typing in characters instead of numbers. It does not seem so.

Ultralight is not HTML5 compliant when it comes to number inputs. It is impossible anyway to input invalid values and it does not even crash the client or something.

**Review by superblaubeere27 — APPROVED** [review]
👍🏻

**Comment by Ell1ott** [comment]
Sorry, that was an accident

**Pull request merged**
