### PR TITLE
Fixed a bug? in Disabler module.

### PR DESCRIPTION
**Pull request by mems01**
That is kind of weird... I was on Hypixel mode, yet I was having RedeskyOld's timer value, so I fixed it this way.

EDIT: I realized there are also bugs in Fly module, or basically every other module with modes that have repeatable sequences.

### CODE REVIEW

**Comment by 1zuna-chan** [comment]
What is the issue?

**Comment by 1zuna-chan** [comment]
I just noticed that there is a timer reset missing, but everything else should be fine.

**Comment by mems01** [comment]
As I said, fly also has a small bug for example. You are in Vanilla mode, but fly up just like Jetpack mode. I think it's supposed to be applied in the specific mode instead in all of them.

**Comment by 1zuna-chan** [comment]
I'll try it later, that should not happen.

**Pull request closed without merging**
