### PR TITLE
Fixed XRay not displaying blocks.

### PR DESCRIPTION
**Pull request by mems01**
* I replaced IBlock with Block (net.minecraft.block.Block) in those 3 files and it seems to work, don't know why IBlock doesn't work though.

* Also did a comparison with b72 and it is the same, according to the tests I've done.

### CODE REVIEW

**Comment by TheFleksisCekcu** [comment]
IBlock was made for 1.12.2, I think, because in 1.12.2 I have IBlock arraylist and it works.

**Comment by TheFleksisCekcu** [comment]
Also, this problem was here because of wrapping blocknames

**Comment by TheFleksisCekcu** [comment]
This crossversion system is just bloody mess, this mess was made on 1.12.2 MC Engine, so then it should not work on 1.8.9 normally

**Comment by mems01** [comment]
At least it works, that's all I care. Now if the others have any problems with me replacing IBlock with Block, it's their choice if they want to merge it or not.

**Comment by kawaiinekololi** [comment]
There are better solutions to solve the issue. I'll leave it open as a "issue".

**Comment by kawaiinekololi** [comment]
> This crossversion system is just bloody mess, this mess was made on 1.12.2 MC Engine, so then it should not work on 1.8.9 normally

It is. That's why we are working on https://github.com/CCBlueX/LiquidBounce/tree/nextgen

**Comment by TheFleksisCekcu** [comment]
> > This crossversion system is just bloody mess, this mess was made on 1.12.2 MC Engine, so then it should not work on 1.8.9 normally
> 
> It is. That's why we are working on https://github.com/CCBlueX/LiquidBounce/tree/nextgen. It may take a while until we're done, but the code of the old client is just fucked up by unoptimized, messy code (which is caused by many people just crumpling their into into my old code)

This crossversion system was really bad idea, 2 MCs in one...

**Comment by kawaiinekololi** [comment]
https://github.com/CCBlueX/LiquidBounce/issues/298

**Pull request closed without merging**
