### PR TITLE
made intave consumeable noslow not instant ban

### PR DESCRIPTION
**Pull request by larryngton**
my dear izuna. there is a reason why i split those ifs
image

### CODE REVIEW

**Comment by larryngton** [comment]
OOPS

**Comment by larryngton** [comment]
testing something rn

**Review by ccetl — COMMENTED** [review]
Both functions are functionally identical.

**Comment by larryngton** [comment]
oh ok great, i was getting instant banned with the other noslow but now its fine

like what the actual fuck

**Pull request closed without merging**
