### PR TITLE
LEGACY: Create Local Themes & Cleanup

### PR DESCRIPTION
**Pull request by Coccocoahelper**
Very big change, ready to merge. Also cleans up some things.

### CODE REVIEW

**Comment by Coccocoahelper** [comment]
Showcase: https://streamable.com/91n98p

(thanks to Sprinp for recording for me)

**Comment by EclipsesDev** [comment]
I'll check this out later

**Comment by EclipsesDev** [comment]
@Coccocoahelper Why would u want to use the same folder as settings? settings folder is to save localconfigs, and also why does localthemes saves the module configs.. and not the hud, clickgui and etc?

**Comment by EclipsesDev** [comment]
and when it failed to save.. why does it still print success 

"[16:15:02] [Client thread/INFO]: [CHAT] §8[§9§lLiquidBounce§8]§r §3§9Creating theme...
[16:15:02] [Client thread/INFO]: [CHAT] §8[§9§lLiquidBounce§8]§r §3§9Saving theme...
[16:15:02] [Client thread/ERROR]: [FileManager] Failed to load config file: hud.json.
com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonArray but was com.google.gson.JsonPrimitive
	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:897) ~[TypeAdapters$35$1.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:927) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:865) ~[Gson.class:?]
	at net.ccbluex.liquidbounce.file.configs.HudConfig.loadConfig(HudConfig.kt:31) ~[HudConfig.class:?]
	at net.ccbluex.liquidbounce.file.FileManager.loadConfig(FileManager.kt:101) [FileManager.class:?]
	at net.ccbluex.liquidbounce.features.command.commands.LocalThemesCommand.execute(LocalThemesCommand.kt:77) [LocalThemesCommand.class:?]
	at net.ccbluex.liquidbounce.features.command.CommandManager.executeCommands(CommandManager.kt:73) [CommandManager.class:?]
	at net.minecraft.client.gui.GuiScreen.handler$messageSend$zbj000(GuiScreen.java:882) [GuiScreen.class:?]
	at net.minecraft.client.gui.GuiScreen.sendChatMessage(GuiScreen.java) [GuiScreen.class:?]
	at net.minecraft.client.gui.GuiScreen.sendChatMessage(GuiScreen.java:437) [GuiScreen.class:?]
	at net.minecraft.client.gui.GuiChat.keyTyped(GuiChat.java:111) [GuiChat.class:?]
	at net.minecraft.client.gui.GuiScreen.handleKeyboardInput(GuiScreen.java:578) [GuiScreen.class:?]
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:534) [GuiScreen.class:?]
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1674) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1024) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:349) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:95) [start/:?]
	at GradleStart.main(GradleStart.java:24) [start/:?]
[16:15:02] [Client thread/INFO]: [CHAT] §8[§9§lLiquidBounce§8]§r §3§6Theme saved successfully."

**Comment by EclipsesDev** [comment]
also when i check the theme file on settings which i called the theme "theme1" this is what inside of it https://paste.ccbluex.net/ded2d7633

**Comment by EclipsesDev** [comment]
> @Coccocoahelper Why would u want to use the same folder as settings? settings folder is to save localconfigs, and also why does localthemes saves the module configs.. and not the hud, clickgui and etc?

And this too, since when i try to .localthemes load.. it will also shows localconfig saves.. so pls make new folder just for themes.. and fix the rest above ^

**Comment by EclipsesDev** [comment]
And since it's themes.. then it shouldn't only save hud.json but also clickgui.json and probably values.json too

**Comment by Coccocoahelper** [comment]
> > @Coccocoahelper Why would u want to use the same folder as settings? settings folder is to save localconfigs, and also why does localthemes saves the module configs.. and not the hud, clickgui and etc?
> 
> And this too, since when i try to .localthemes load.. it will also shows localconfig saves.. so pls make new folder just for themes.. and fix the rest above ^

Not an intented behavior. EDIT: Fixed

**Comment by Coccocoahelper** [comment]
LocalThemes.kt's code
```
/*
 * LiquidBounce Hacked Client
 * A free open source mixin-based injection hacked client for Minecraft using Minecraft Forge.
 * https://github.com/CCBlueX/LiquidBounce/
 */
package net.ccbluex.liquidbounce.features.command.commands

import net.ccbluex.liquidbounce.features.command.Command
import net.ccbluex.liquidbounce.file.FileManager.dir
import net.ccbluex.liquidbounce.file.FileManager.themesDir
import net.ccbluex.liquidbounce.file.FileManager.hudConfig
import net.ccbluex.liquidbounce.file.FileManager.loadConfig
import net.ccbluex.liquidbounce.ui.client.hud.HUD.addNotification
import net.ccbluex.liquidbounce.ui.client.hud.element.elements.Notification
import net.ccbluex.liquidbounce.utils.ClientUtils.LOGGER
import net.ccbluex.liquidbounce.utils.misc.StringUtils
import java.awt.Desktop
import java.io.File
import java.io.IOException

object LocalThemesCommand : Command("localthemes", "localtheme") {
    /**
     * Execute commands with provided [args]
     */
    override fun execute(args: Array<String>) {
        val usedAlias = args[0].lowercase()

        if (args.size <= 1) {
            chatSyntax("$usedAlias <load/save/list/delete/folder>")
            return
        }

        when (args[1].lowercase()) {
            "load" -> {
                if (args.size <= 2) {
                    chatSyntax("$usedAlias load <name>")
                    return
                }

                val themeFile = File(themesDir, args[2])
                val hudFile = File(dir, "hud.json")

                if (!themeFile.exists()) {
                    chat("§cTheme file does not exist!")
                    return
                }

                try {
                    chat("§9Loading theme...")
                    themeFile.copyTo(hudFile, true)
                    loadConfig(hudConfig)
                    chat("§6Theme applied successfully.")
                    addNotification(Notification("Updated Theme"))
                    playEdit()
                } catch (e: IOException) {
                    e.printStackTrace()
                }
            }

            "save" -> {
                if (args.size <= 2) {
                    chatSyntax("$usedAlias save <name>...")
                    return
                }

                val themeFile = File(themesDir, args[2])

                try {
                    if (themeFile.exists())
                        themeFile.delete()

                    chat("§9Creating theme...")
                    themeFile.createNewFile()

                    chat("§9Saving theme...")
                    File(dir, "hud.json").copyTo(themeFile, true)
                    loadConfig(hudConfig)

                    chat("§6Theme saved successfully.")
                } catch (throwable: Throwable) {
                    chat("§cFailed to create local theme: §3${throwable.message}")
                    LOGGER.error("Failed to create local theme.", throwable)
                }
            }

            "delete" -> {
                if (args.size <= 2) {
                    chatSyntax("$usedAlias delete <name>")
                    return
                }

                val themeFile = File(themesDir, args[2])

                if (!themeFile.exists()) {
                    chat("§cTheme file does not exist!")
                    return
                }

                themeFile.delete()
                chat("§6Theme file deleted successfully.")
            }

            "list" -> {
                chat("§cThemes:")

                val themes = getLocalThemes() ?: return

                for (file in themes) {
                    chat("> " + file.name)
                }
            }

            "folder" -> {
                Desktop.getDesktop().open(themesDir)
            }
        }
    }

    override fun tabComplete(args: Array<String>): List<String> {
        if (args.isEmpty()) return emptyList()

        return when (args.size) {
            1 -> listOf("delete", "list", "load", "save").filter { it.startsWith(args[0], true) }

            2 ->
                when (args[0].lowercase()) {
                    "delete", "load" -> {
                        val themes = getLocalThemes() ?: return emptyList()

                        themes
                            .map { it.name }
                            .filter { it.startsWith(args[1], true) }
                    }

                    else -> emptyList()
                }

            else -> emptyList()
        }
    }

    private fun getLocalThemes() = themesDir.listFiles()
}
```

**Comment by EclipsesDev** [comment]
@Coccocoahelper Ok cool it worked now.. but instead of saving it on settings folder.. u could've make new folder `Themes` and make it get saved there instead

**Comment by EclipsesDev** [comment]
I will merge this after you do that 👍

**Comment by EclipsesDev** [comment]
And optionally you could make it save the clickgui style too

**Comment by Coccocoahelper** [comment]
> I will merge this after you do that 👍

I did that, I think: https://github.com/CCBlueX/LiquidBounce/pull/2959/commits/96d0b6a891bfcd36d25ef04d787b3c02be240f6e

**Comment by Coccocoahelper** [comment]
> And optionally you could make it save the clickgui style too

Difficult to do, since ClickGUI is a module, and I don't want to add bugs.

**Comment by EclipsesDev** [comment]
> > I will merge this after you do that 👍
> 
> I did that, I think: [96d0b6a](https://github.com/CCBlueX/LiquidBounce/commit/96d0b6a891bfcd36d25ef04d787b3c02be240f6e)

Oh ok lemme check again

**Comment by EclipsesDev** [comment]
ooh it seems like u forgot to add a check if the folder doesn't exist then it should create one.. ig i'll fix it for u

**Comment by EclipsesDev** [comment]
Also @Coccocoahelper wouldn't it be a great idea, if you make it possible to load themes from liquidcloud too?

**Comment by Coccocoahelper** [comment]
> Also @Coccocoahelper wouldn't it be a great idea, if you make it possible to load themes from liquidcloud too?

I was thinking about that. I'm going to try to impl it.

**Comment by EclipsesDev** [comment]
> > Also @Coccocoahelper wouldn't it be a great idea, if you make it possible to load themes from liquidcloud too?
> 
> I was thinking about that. I'm going to try to impl it.

Oh well ig that'd be great, i'll wait until it gets implemented before merging this 👍

**Comment by Coccocoahelper** [comment]
> > > Also @Coccocoahelper wouldn't it be a great idea, if you make it possible to load themes from liquidcloud too?
> > 
> > 
> > I was thinking about that. I'm going to try to impl it.
> 
> Oh well ig that'd be great, i'll wait until it gets implemented before merging this 👍

Also, do you have a Matrix.org account? Would be easier to communicate with you + it's end to end encrypted.

**Comment by EclipsesDev** [comment]
> Matrix.org

Why not discord?

**Comment by Coccocoahelper** [comment]
> > Matrix.org
> 
> Why not discord?

Messages stored in plain text.

**Comment by EclipsesDev** [comment]
> > > Matrix.org
> > 
> > 
> > Why not discord?
> 
> Messages stored in plain text.

Huh?

**Comment by Coccocoahelper** [comment]
> > > Also @Coccocoahelper wouldn't it be a great idea, if you make it possible to load themes from liquidcloud too?
> > 
> > 
> > I was thinking about that. I'm going to try to impl it.
> 
> Oh well ig that'd be great, i'll wait until it gets implemented before merging this 👍

I actually can't do it yet (I'm not very good at coding), but I'll clean up other code.

**Comment by EclipsesDev** [comment]
dw, when i have time.. I'll help u with this

**Comment by Coccocoahelper** [comment]
> dw, when i have time.. I'll help u with this

Want to know my cleanup progress?

**Comment by EclipsesDev** [comment]
have you test it yet?

**Comment by 182exe** [comment]
o.O

**Comment by Coccocoahelper** [comment]
> have you test it yet?

Not yet, but fixing potential performance regressions from the cleanup.

**Comment by EclipsesDev** [comment]
> > have you test it yet?
> 
> Not yet, but fixing potential performance regressions from the cleanup.

Okay yeah, makesure that u test everything that it doesn't conflict with things

**Comment by Coccocoahelper** [comment]
> > > have you test it yet?
> > 
> > 
> > Not yet, but fixing potential performance regressions from the cleanup.
> 
> Okay yeah, makesure that u test everything that it doesn't conflict with things

It doesn't appear to.

**Comment by EclipsesDev** [comment]
> > > > have you test it yet?
> > > 
> > > 
> > > Not yet, but fixing potential performance regressions from the cleanup.
> > 
> > 
> > Okay yeah, makesure that u test everything that it doesn't conflict with things
> 
> It doesn't appear to.

Not only conflicts.. but like actually does the command work or no.. and etc

**Comment by Coccocoahelper** [comment]
> > > > > have you test it yet?
> > > > 
> > > > 
> > > > Not yet, but fixing potential performance regressions from the cleanup.
> > > 
> > > 
> > > Okay yeah, makesure that u test everything that it doesn't conflict with things
> > 
> > 
> > It doesn't appear to.
> 
> Not only conflicts.. but like actually does the command work or no.. and etc

It works.

**Comment by EclipsesDev** [comment]
Hmm alright @Coccocoahelper ready to merge?

**Comment by 182exe** [comment]
do it do it do it :3

**Comment by Coccocoahelper** [comment]
> [EclipsesDev](/EclipsesDev)
> Hmm alright @Coccocoahelper ready to merge?
ya

**Pull request merged**
