### PR TITLE
Matrix timer

### PR DESCRIPTION
**Pull request by suprohub**
(needs test and fixes because sometimes flags on bad packets)
Very cool if someone write disabler or something like this for matrix

### CODE REVIEW

**Comment by EclipsesDev** [comment]
bro this is literally just timerbalancing 💀

**Comment by larryngton2** [comment]
you should rename the speed to just "timer" since it works on most anticheats with the correct config

**Comment by larryngton2** [comment]
> bro this is literally just timerbalancing 💀

we commented at the same time :skull:

**Comment by EclipsesDev** [comment]
> > bro this is literally just timerbalancing 💀
> 
> we commented at the same time 💀

xd

**Comment by EclipsesDev** [comment]
alright this is quite literally useless, it already exist in customspeed but u could add timerbalance(normal/slow timer) there

**Pull request closed without merging**
