### PR TITLE
[LEGACY] Scaffold Improvements

### PR DESCRIPTION
**Pull request by gabrielvicenteYT**

### CODE REVIEW

**Comment by RtxOP** [comment]
Why did you rename off ground ticks to ground ticks that makes no sense

**Comment by CzechHek** [comment]
Why tf are there spaces in off ground ticks value?

**Comment by RtxOP** [comment]
> Why tf are there spaces in off ground ticks value?

I actually didnt notice that

**Comment by ghost** [comment]
Rename it back to OffGroundTicks.

**Pull request merged**
