### PR TITLE
2 module conversions.

### PR DESCRIPTION
**Pull request by mems01**

### CODE REVIEW

**Comment by kawaiinekololi** [comment]
hell nah auto translator

**Comment by mems01** [comment]
lol why would i auto-translate these

**Comment by kawaiinekololi** [comment]
at least optimize the code for Kotlin.

**Comment by mems01** [comment]
How should I optimize it? What I only know so far is to both convert the files from java to Kotlin and change stuff to kotlin..

**Comment by kawaiinekololi** [comment]
well you could maybe read the kotlin docs or optimized kotlin code (see nextgen lb as example). Kotlin is also a great language to learn, so maybe use it for new projects. 👍🏼

**Comment by mems01** [comment]
At least I managed to translate those 2 modules to kotlin after spending 2 hours on it. I don't know if it messes up the performance in game.

**Comment by mems01** [comment]
I've done a bit of optimization on the spammer module, if it's even considered optimization.. The thing is that it doesn't have any errors and works as it should in game.

**Pull request closed without merging**
